package com.fipa.dto;

// Generated Oct 10, 2018 11:57:51 AM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * FnaAutoAlter generated by hbm2java
 */
public class FnaAutoAlter implements java.io.Serializable {

	private String altId;
	private String fnaId;
	private String modelUid;
	private String attrName;
	private String attrOrgValue;
	private String attrNewValue;
	private String attrCrtdBy;
	private Date attrCrtdDate;

	public FnaAutoAlter() {
	}

	public FnaAutoAlter(String altId, String fnaId) {
		this.altId = altId;
		this.fnaId = fnaId;
	}

	public FnaAutoAlter(String altId, String fnaId, String modelUid,
			String attrName, String attrOrgValue, String attrNewValue,
			String attrCrtdBy, Date attrCrtdDate) {
		this.altId = altId;
		this.fnaId = fnaId;
		this.modelUid = modelUid;
		this.attrName = attrName;
		this.attrOrgValue = attrOrgValue;
		this.attrNewValue = attrNewValue;
		this.attrCrtdBy = attrCrtdBy;
		this.attrCrtdDate = attrCrtdDate;
	}

	public String getAltId() {
		return this.altId;
	}

	public void setAltId(String altId) {
		this.altId = altId;
	}

	public String getFnaId() {
		return this.fnaId;
	}

	public void setFnaId(String fnaId) {
		this.fnaId = fnaId;
	}

	public String getModelUid() {
		return this.modelUid;
	}

	public void setModelUid(String modelUid) {
		this.modelUid = modelUid;
	}

	public String getAttrName() {
		return this.attrName;
	}

	public void setAttrName(String attrName) {
		this.attrName = attrName;
	}

	public String getAttrOrgValue() {
		return this.attrOrgValue;
	}

	public void setAttrOrgValue(String attrOrgValue) {
		this.attrOrgValue = attrOrgValue;
	}

	public String getAttrNewValue() {
		return this.attrNewValue;
	}

	public void setAttrNewValue(String attrNewValue) {
		this.attrNewValue = attrNewValue;
	}

	public String getAttrCrtdBy() {
		return this.attrCrtdBy;
	}

	public void setAttrCrtdBy(String attrCrtdBy) {
		this.attrCrtdBy = attrCrtdBy;
	}

	public Date getAttrCrtdDate() {
		return this.attrCrtdDate;
	}

	public void setAttrCrtdDate(Date attrCrtdDate) {
		this.attrCrtdDate = attrCrtdDate;
	}

}
