package com.fipa.dto;

// Generated May 17, 2018 11:20:36 AM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * FnaAssetOtherdets generated by hbm2java
 */
public class FnaAssetOtherdets implements java.io.Serializable {

	private String othId;//
	private FnaSelfspouseDets fnaSelfspouseDets;
	private Double othasstSelfPers;//
	private Double othasstSpousePers;//
	private Double othasstJointPers;//
	private Double othasstLoansPers;//
	private String othasstRemarksPers;//
	private Double othasstSelfClub;//
	private Double othasstSpouseClub;//
	private Double othasstJointClub;//
	private Double othasstLoansClub;//
	private String othasstRemarksClub;//
	private Double othasstSelfBusi;//
	private Double othasstSpouseBusi;//
	private Double othasstJointBusi;//
	private Double othasstLoansBusi;//
	private String othasstRemarksBusi;//
	private Double othasstSelfOth;//
	private Double othasstSpouseOth;//
	private Double othasstJointOth;//
	private Double othasstLoansOth;//
	private String othasstRemarksOth;//
	private Double othasstSelfTot;//
	private Double othasstSpouseTot;//
	private Double othasstJointTot;//
	private Double othasstLoansTot;//
	private String othasstRemarksTot;
	private String othasstNotes;//
	private String othasstCreatedBy;
	private Date othasstCreatedDate;
	private String othasstModifiedBy;
	private Date othasstModifiedDate;
	private String othasstDesPers;
	private String othasstDesClub;
	private String othasstDesBusi;
	private String othasstDesOth;
	private String othasstPersItems;
	private String othasstClubOwnrship;
	private String othasstBusiOwnrship;
	private String othasstOthersAssets;

  
	public String getOthasstDesPers() {
		return othasstDesPers;
	}

	public void setOthasstDesPers(String othasstDesPers) {
		this.othasstDesPers = othasstDesPers;
	}

	public String getOthasstDesClub() {
		return othasstDesClub;
	}

	public void setOthasstDesClub(String othasstDesClub) {
		this.othasstDesClub = othasstDesClub;
	}

	public String getOthasstDesBusi() {
		return othasstDesBusi;
	}

	public void setOthasstDesBusi(String othasstDesBusi) {
		this.othasstDesBusi = othasstDesBusi;
	}

	public String getOthasstDesOth() {
		return othasstDesOth;
	}

	public void setOthasstDesOth(String othasstDesOth) {
		this.othasstDesOth = othasstDesOth;
	}

	public String getOthasstPersItems() {
		return othasstPersItems;
	}

	public void setOthasstPersItems(String othasstPersItems) {
		this.othasstPersItems = othasstPersItems;
	}

	public String getOthasstClubOwnrship() {
		return othasstClubOwnrship;
	}

	public void setOthasstClubOwnrship(String othasstClubOwnrship) {
		this.othasstClubOwnrship = othasstClubOwnrship;
	}

	public String getOthasstBusiOwnrship() {
		return othasstBusiOwnrship;
	}

	public void setOthasstBusiOwnrship(String othasstBusiOwnrship) {
		this.othasstBusiOwnrship = othasstBusiOwnrship;
	}

	public String getOthasstOthersAssets() {
		return othasstOthersAssets;
	}

	public void setOthasstOthersAssets(String othasstOthersAssets) {
		this.othasstOthersAssets = othasstOthersAssets;
	}

	public FnaAssetOtherdets() {
	}

	public FnaAssetOtherdets(String othId) {
		this.othId = othId;
	}

	public FnaAssetOtherdets(String othId, FnaSelfspouseDets fnaSelfspouseDets,
			Double othasstSelfPers, Double othasstSpousePers,
			Double othasstJointPers, Double othasstLoansPers,
			String othasstRemarksPers, Double othasstSelfClub,
			Double othasstSpouseClub, Double othasstJointClub,
			Double othasstLoansClub, String othasstRemarksClub,
			Double othasstSelfBusi, Double othasstSpouseBusi,
			Double othasstJointBusi, Double othasstLoansBusi,
			String othasstRemarksBusi, Double othasstSelfOth,
			Double othasstSpouseOth, Double othasstJointOth,
			Double othasstLoansOth, String othasstRemarksOth,
			Double othasstSelfTot, Double othasstSpouseTot,
			Double othasstJointTot, Double othasstLoansTot,
			String othasstRemarksTot, String othasstNotes,
			String othasstCreatedBy, Date othasstCreatedDate,
			String othasstModifiedBy, Date othasstModifiedDate) {
		this.othId = othId;
		this.fnaSelfspouseDets = fnaSelfspouseDets;
		this.othasstSelfPers = othasstSelfPers;
		this.othasstSpousePers = othasstSpousePers;
		this.othasstJointPers = othasstJointPers;
		this.othasstLoansPers = othasstLoansPers;
		this.othasstRemarksPers = othasstRemarksPers;
		this.othasstSelfClub = othasstSelfClub;
		this.othasstSpouseClub = othasstSpouseClub;
		this.othasstJointClub = othasstJointClub;
		this.othasstLoansClub = othasstLoansClub;
		this.othasstRemarksClub = othasstRemarksClub;
		this.othasstSelfBusi = othasstSelfBusi;
		this.othasstSpouseBusi = othasstSpouseBusi;
		this.othasstJointBusi = othasstJointBusi;
		this.othasstLoansBusi = othasstLoansBusi;
		this.othasstRemarksBusi = othasstRemarksBusi;
		this.othasstSelfOth = othasstSelfOth;
		this.othasstSpouseOth = othasstSpouseOth;
		this.othasstJointOth = othasstJointOth;
		this.othasstLoansOth = othasstLoansOth;
		this.othasstRemarksOth = othasstRemarksOth;
		this.othasstSelfTot = othasstSelfTot;
		this.othasstSpouseTot = othasstSpouseTot;
		this.othasstJointTot = othasstJointTot;
		this.othasstLoansTot = othasstLoansTot;
		this.othasstRemarksTot = othasstRemarksTot;
		this.othasstNotes = othasstNotes;
		this.othasstCreatedBy = othasstCreatedBy;
		this.othasstCreatedDate = othasstCreatedDate;
		this.othasstModifiedBy = othasstModifiedBy;
		this.othasstModifiedDate = othasstModifiedDate;
	}

	public String getOthId() {
		return this.othId;
	}

	public void setOthId(String othId) {
		this.othId = othId;
	}

	public FnaSelfspouseDets getFnaSelfspouseDets() {
		return this.fnaSelfspouseDets;
	}

	public void setFnaSelfspouseDets(FnaSelfspouseDets fnaSelfspouseDets) {
		this.fnaSelfspouseDets = fnaSelfspouseDets;
	}

	public Double getOthasstSelfPers() {
		return this.othasstSelfPers;
	}

	public void setOthasstSelfPers(Double othasstSelfPers) {
		this.othasstSelfPers = othasstSelfPers;
	}

	public Double getOthasstSpousePers() {
		return this.othasstSpousePers;
	}

	public void setOthasstSpousePers(Double othasstSpousePers) {
		this.othasstSpousePers = othasstSpousePers;
	}

	public Double getOthasstJointPers() {
		return this.othasstJointPers;
	}

	public void setOthasstJointPers(Double othasstJointPers) {
		this.othasstJointPers = othasstJointPers;
	}

	public Double getOthasstLoansPers() {
		return this.othasstLoansPers;
	}

	public void setOthasstLoansPers(Double othasstLoansPers) {
		this.othasstLoansPers = othasstLoansPers;
	}

	public String getOthasstRemarksPers() {
		return this.othasstRemarksPers;
	}

	public void setOthasstRemarksPers(String othasstRemarksPers) {
		this.othasstRemarksPers = othasstRemarksPers;
	}

	public Double getOthasstSelfClub() {
		return this.othasstSelfClub;
	}

	public void setOthasstSelfClub(Double othasstSelfClub) {
		this.othasstSelfClub = othasstSelfClub;
	}

	public Double getOthasstSpouseClub() {
		return this.othasstSpouseClub;
	}

	public void setOthasstSpouseClub(Double othasstSpouseClub) {
		this.othasstSpouseClub = othasstSpouseClub;
	}

	public Double getOthasstJointClub() {
		return this.othasstJointClub;
	}

	public void setOthasstJointClub(Double othasstJointClub) {
		this.othasstJointClub = othasstJointClub;
	}

	public Double getOthasstLoansClub() {
		return this.othasstLoansClub;
	}

	public void setOthasstLoansClub(Double othasstLoansClub) {
		this.othasstLoansClub = othasstLoansClub;
	}

	public String getOthasstRemarksClub() {
		return this.othasstRemarksClub;
	}

	public void setOthasstRemarksClub(String othasstRemarksClub) {
		this.othasstRemarksClub = othasstRemarksClub;
	}

	public Double getOthasstSelfBusi() {
		return this.othasstSelfBusi;
	}

	public void setOthasstSelfBusi(Double othasstSelfBusi) {
		this.othasstSelfBusi = othasstSelfBusi;
	}

	public Double getOthasstSpouseBusi() {
		return this.othasstSpouseBusi;
	}

	public void setOthasstSpouseBusi(Double othasstSpouseBusi) {
		this.othasstSpouseBusi = othasstSpouseBusi;
	}

	public Double getOthasstJointBusi() {
		return this.othasstJointBusi;
	}

	public void setOthasstJointBusi(Double othasstJointBusi) {
		this.othasstJointBusi = othasstJointBusi;
	}

	public Double getOthasstLoansBusi() {
		return this.othasstLoansBusi;
	}

	public void setOthasstLoansBusi(Double othasstLoansBusi) {
		this.othasstLoansBusi = othasstLoansBusi;
	}

	public String getOthasstRemarksBusi() {
		return this.othasstRemarksBusi;
	}

	public void setOthasstRemarksBusi(String othasstRemarksBusi) {
		this.othasstRemarksBusi = othasstRemarksBusi;
	}

	public Double getOthasstSelfOth() {
		return this.othasstSelfOth;
	}

	public void setOthasstSelfOth(Double othasstSelfOth) {
		this.othasstSelfOth = othasstSelfOth;
	}

	public Double getOthasstSpouseOth() {
		return this.othasstSpouseOth;
	}

	public void setOthasstSpouseOth(Double othasstSpouseOth) {
		this.othasstSpouseOth = othasstSpouseOth;
	}

	public Double getOthasstJointOth() {
		return this.othasstJointOth;
	}

	public void setOthasstJointOth(Double othasstJointOth) {
		this.othasstJointOth = othasstJointOth;
	}

	public Double getOthasstLoansOth() {
		return this.othasstLoansOth;
	}

	public void setOthasstLoansOth(Double othasstLoansOth) {
		this.othasstLoansOth = othasstLoansOth;
	}

	public String getOthasstRemarksOth() {
		return this.othasstRemarksOth;
	}

	public void setOthasstRemarksOth(String othasstRemarksOth) {
		this.othasstRemarksOth = othasstRemarksOth;
	}

	public Double getOthasstSelfTot() {
		return this.othasstSelfTot;
	}

	public void setOthasstSelfTot(Double othasstSelfTot) {
		this.othasstSelfTot = othasstSelfTot;
	}

	public Double getOthasstSpouseTot() {
		return this.othasstSpouseTot;
	}

	public void setOthasstSpouseTot(Double othasstSpouseTot) {
		this.othasstSpouseTot = othasstSpouseTot;
	}

	public Double getOthasstJointTot() {
		return this.othasstJointTot;
	}

	public void setOthasstJointTot(Double othasstJointTot) {
		this.othasstJointTot = othasstJointTot;
	}

	public Double getOthasstLoansTot() {
		return this.othasstLoansTot;
	}

	public void setOthasstLoansTot(Double othasstLoansTot) {
		this.othasstLoansTot = othasstLoansTot;
	}

	public String getOthasstRemarksTot() {
		return this.othasstRemarksTot;
	}

	public void setOthasstRemarksTot(String othasstRemarksTot) {
		this.othasstRemarksTot = othasstRemarksTot;
	}

	public String getOthasstNotes() {
		return this.othasstNotes;
	}

	public void setOthasstNotes(String othasstNotes) {
		this.othasstNotes = othasstNotes;
	}

	public String getOthasstCreatedBy() {
		return this.othasstCreatedBy;
	}

	public void setOthasstCreatedBy(String othasstCreatedBy) {
		this.othasstCreatedBy = othasstCreatedBy;
	}

	public Date getOthasstCreatedDate() {
		return this.othasstCreatedDate;
	}

	public void setOthasstCreatedDate(Date othasstCreatedDate) {
		this.othasstCreatedDate = othasstCreatedDate;
	}

	public String getOthasstModifiedBy() {
		return this.othasstModifiedBy;
	}

	public void setOthasstModifiedBy(String othasstModifiedBy) {
		this.othasstModifiedBy = othasstModifiedBy;
	}

	public Date getOthasstModifiedDate() {
		return this.othasstModifiedDate;
	}

	public void setOthasstModifiedDate(Date othasstModifiedDate) {
		this.othasstModifiedDate = othasstModifiedDate;
	}

}
