package com.fipa.dto;

// Generated May 17, 2018 11:20:36 AM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * FnaApptypes generated by hbm2java
 */
public class FnaApptypes implements java.io.Serializable {

	private String appTypeid;//
	private MasterAnalysisTypes masterAnalysisTypes;//
	private FnaSelfspouseDets fnaSelfspouseDets;//
	private String anaCrtdBy;
	private Date anaCrtdDate;

	public FnaApptypes() {
	}

	public FnaApptypes(String appTypeid, String anaCrtdBy, Date anaCrtdDate) {
		this.appTypeid = appTypeid;
		this.anaCrtdBy = anaCrtdBy;
		this.anaCrtdDate = anaCrtdDate;
	}

	public FnaApptypes(String appTypeid,
			MasterAnalysisTypes masterAnalysisTypes,
			FnaSelfspouseDets fnaSelfspouseDets, String anaCrtdBy,
			Date anaCrtdDate) {
		this.appTypeid = appTypeid;
		this.masterAnalysisTypes = masterAnalysisTypes;
		this.fnaSelfspouseDets = fnaSelfspouseDets;
		this.anaCrtdBy = anaCrtdBy;
		this.anaCrtdDate = anaCrtdDate;
	}

	public String getAppTypeid() {
		return this.appTypeid;
	}

	public void setAppTypeid(String appTypeid) {
		this.appTypeid = appTypeid;
	}

	public MasterAnalysisTypes getMasterAnalysisTypes() {
		return this.masterAnalysisTypes;
	}

	public void setMasterAnalysisTypes(MasterAnalysisTypes masterAnalysisTypes) {
		this.masterAnalysisTypes = masterAnalysisTypes;
	}

	public FnaSelfspouseDets getFnaSelfspouseDets() {
		return this.fnaSelfspouseDets;
	}

	public void setFnaSelfspouseDets(FnaSelfspouseDets fnaSelfspouseDets) {
		this.fnaSelfspouseDets = fnaSelfspouseDets;
	}

	public String getAnaCrtdBy() {
		return this.anaCrtdBy;
	}

	public void setAnaCrtdBy(String anaCrtdBy) {
		this.anaCrtdBy = anaCrtdBy;
	}

	public Date getAnaCrtdDate() {
		return this.anaCrtdDate;
	}

	public void setAnaCrtdDate(Date anaCrtdDate) {
		this.anaCrtdDate = anaCrtdDate;
	}

}
