package com.fipa.dto;

// Generated Aug 2, 2018 5:16:44 PM by Hibernate Tools 4.0.0
 
import java.io.Serializable; 
import java.util.Date;

/**
 * FnaAttachments generated by hbm2java
 */
public class FnaAttachments implements java.io.Serializable {

	private String docid;
	private String fnaId;
//	private Serializable document;
	private String attachCategId;
	private String attachCategName;
	private String documentTitle;
	private String pageNo;
	private String filename;
	private String filesize;
	private String filetype;
	private String createdBy;
	private Date attachDate;
	private String remarks;
	private Date createdDate;
	private String moduleRef;
	private String referenceId;

	public FnaAttachments() {
	}

	public FnaAttachments(String docid,
			String documentTitle, Date attachDate) {
		this.docid = docid;
//		this.document = document;
		this.documentTitle = documentTitle;
		this.attachDate = attachDate;
	}

	public FnaAttachments(String docid, String fnaId,  String attachCategId,
			String attachCategName, String documentTitle, String pageNo,
			String filename, String filesize, String filetype,
			String createdBy, Date attachDate, String remarks,
			Date createdDate, String moduleRef, String referenceId) {
		this.docid = docid;
		this.fnaId = fnaId; 
		this.attachCategId = attachCategId;
		this.attachCategName = attachCategName;
		this.documentTitle = documentTitle;
		this.pageNo = pageNo;
		this.filename = filename;
		this.filesize = filesize;
		this.filetype = filetype;
		this.createdBy = createdBy;
		this.attachDate = attachDate;
		this.remarks = remarks;
		this.createdDate = createdDate;
		this.moduleRef = moduleRef;
		this.referenceId = referenceId;
	}

	public String getDocid() {
		return this.docid;
	}

	public void setDocid(String docid) {
		this.docid = docid;
	}

	public String getFnaId() {
		return this.fnaId;
	}

	public void setFnaId(String fnaId) {
		this.fnaId = fnaId;
	}
 

	public String getAttachCategId() {
		return this.attachCategId;
	}

	public void setAttachCategId(String attachCategId) {
		this.attachCategId = attachCategId;
	}

	public String getAttachCategName() {
		return this.attachCategName;
	}

	public void setAttachCategName(String attachCategName) {
		this.attachCategName = attachCategName;
	}

	public String getDocumentTitle() {
		return this.documentTitle;
	}

	public void setDocumentTitle(String documentTitle) {
		this.documentTitle = documentTitle;
	}

	public String getPageNo() {
		return this.pageNo;
	}

	public void setPageNo(String pageNo) {
		this.pageNo = pageNo;
	}

	public String getFilename() {
		return this.filename;
	}

	public void setFilename(String filename) {
		this.filename = filename;
	}

	public String getFilesize() {
		return this.filesize;
	}

	public void setFilesize(String filesize) {
		this.filesize = filesize;
	}

	public String getFiletype() {
		return this.filetype;
	}

	public void setFiletype(String filetype) {
		this.filetype = filetype;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getAttachDate() {
		return this.attachDate;
	}

	public void setAttachDate(Date attachDate) {
		this.attachDate = attachDate;
	}

	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public String getModuleRef() {
		return this.moduleRef;
	}

	public void setModuleRef(String moduleRef) {
		this.moduleRef = moduleRef;
	}

	public String getReferenceId() {
		return this.referenceId;
	}

	public void setReferenceId(String referenceId) {
		this.referenceId = referenceId;
	}

}
