package com.fipa.dto;

// Generated May 21, 2018 6:03:08 PM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * FnaAssetCashdets generated by hbm2java
 */
public class FnaAssetCashdets implements java.io.Serializable {

	private String casstId;//
	private FnaSelfspouseDets fnaSelfspouseDets;
	private Double casstSelfSavingfd;//
	private Double casstSelfRegsaving;//
	private Double casstSelfCashequ;//
	private Double casstSelfSrs;//
	private Double casstSpsSavingfd;//
	private Double casstSpsRegsaving;//
	private Double casstSpsCashequ;//
	private Double casstSpsSrs;//
	private Double casstFamSavingfd;//
	private Double casstFamRegsaving;//
	private Double casstFamCashequ;//
	private Double casstRpSavingfd;//
	private Double casstRpRegsaving;//
	private Double casstRpCashequ;//
	private Double casstRpSrs;//
	private String casstRemSavingfd;//
	private String casstRemRegsaving;//
	private String casstRemCashequ;//
	private String casstRemSrs;//
	private Double casstSpsRpSavingfd;//
	private Double casstSpsRpRegsaving;//
	private Double casstSpsRpCashequ;//
	private Double casstSpsRpSrs;//
	private String casstSpsRemSavingfd;//
	private String casstSpsRemRegsaving;//
	private String casstSpsRemCashequ;//
	private String casstSpsRemSrs;//
	private Double casstFamRpSavingfd;//
	private Double casstFamRpRegsaving;//
	private Double casstFamRpCashequ;//
	private String casstFamRemSavingfd;//
	private String casstFamRemRegsaving;//
	private String casstFamRemCashequ;//
	private Double casstFamSrs;//
	private Double casstFamRpSrs;//
	private String casstFamRemSrs;//
	private Double casstSelfTotal;//
	private Double casstSpsTotal;//
	private Double casstFamTotal;//
	private String casstCreatedBy;//
	private Date casstCreatedDate;//
	private String casstModifiedBy;
	private Date casstModifiedDate;

	public FnaAssetCashdets() {
	}

	public FnaAssetCashdets(String casstId) {
		this.casstId = casstId;
	}

	public FnaAssetCashdets(String casstId,
			FnaSelfspouseDets fnaSelfspouseDets, Double casstSelfSavingfd,
			Double casstSelfRegsaving, Double casstSelfCashequ,
			Double casstSelfSrs, Double casstSpsSavingfd,
			Double casstSpsRegsaving, Double casstSpsCashequ,
			Double casstSpsSrs, Double casstFamSavingfd,
			Double casstFamRegsaving, Double casstFamCashequ,
			Double casstRpSavingfd, Double casstRpRegsaving,
			Double casstRpCashequ, Double casstRpSrs, String casstRemSavingfd,
			String casstRemRegsaving, String casstRemCashequ,
			String casstRemSrs, Double casstSpsRpSavingfd,
			Double casstSpsRpRegsaving, Double casstSpsRpCashequ,
			Double casstSpsRpSrs, String casstSpsRemSavingfd,
			String casstSpsRemRegsaving, String casstSpsRemCashequ,
			String casstSpsRemSrs, Double casstFamRpSavingfd,
			Double casstFamRpRegsaving, Double casstFamRpCashequ,
			String casstFamRemSavingfd, String casstFamRemRegsaving,
			String casstFamRemCashequ, Double casstFamSrs,
			Double casstFamRpSrs, String casstFamRemSrs, Double casstSelfTotal,
			Double casstSpsTotal, Double casstFamTotal, String casstCreatedBy,
			Date casstCreatedDate, String casstModifiedBy,
			Date casstModifiedDate) {
		this.casstId = casstId;
		this.fnaSelfspouseDets = fnaSelfspouseDets;
		this.casstSelfSavingfd = casstSelfSavingfd;
		this.casstSelfRegsaving = casstSelfRegsaving;
		this.casstSelfCashequ = casstSelfCashequ;
		this.casstSelfSrs = casstSelfSrs;
		this.casstSpsSavingfd = casstSpsSavingfd;
		this.casstSpsRegsaving = casstSpsRegsaving;
		this.casstSpsCashequ = casstSpsCashequ;
		this.casstSpsSrs = casstSpsSrs;
		this.casstFamSavingfd = casstFamSavingfd;
		this.casstFamRegsaving = casstFamRegsaving;
		this.casstFamCashequ = casstFamCashequ;
		this.casstRpSavingfd = casstRpSavingfd;
		this.casstRpRegsaving = casstRpRegsaving;
		this.casstRpCashequ = casstRpCashequ;
		this.casstRpSrs = casstRpSrs;
		this.casstRemSavingfd = casstRemSavingfd;
		this.casstRemRegsaving = casstRemRegsaving;
		this.casstRemCashequ = casstRemCashequ;
		this.casstRemSrs = casstRemSrs;
		this.casstSpsRpSavingfd = casstSpsRpSavingfd;
		this.casstSpsRpRegsaving = casstSpsRpRegsaving;
		this.casstSpsRpCashequ = casstSpsRpCashequ;
		this.casstSpsRpSrs = casstSpsRpSrs;
		this.casstSpsRemSavingfd = casstSpsRemSavingfd;
		this.casstSpsRemRegsaving = casstSpsRemRegsaving;
		this.casstSpsRemCashequ = casstSpsRemCashequ;
		this.casstSpsRemSrs = casstSpsRemSrs;
		this.casstFamRpSavingfd = casstFamRpSavingfd;
		this.casstFamRpRegsaving = casstFamRpRegsaving;
		this.casstFamRpCashequ = casstFamRpCashequ;
		this.casstFamRemSavingfd = casstFamRemSavingfd;
		this.casstFamRemRegsaving = casstFamRemRegsaving;
		this.casstFamRemCashequ = casstFamRemCashequ;
		this.casstFamSrs = casstFamSrs;
		this.casstFamRpSrs = casstFamRpSrs;
		this.casstFamRemSrs = casstFamRemSrs;
		this.casstSelfTotal = casstSelfTotal;
		this.casstSpsTotal = casstSpsTotal;
		this.casstFamTotal = casstFamTotal;
		this.casstCreatedBy = casstCreatedBy;
		this.casstCreatedDate = casstCreatedDate;
		this.casstModifiedBy = casstModifiedBy;
		this.casstModifiedDate = casstModifiedDate;
	}

	public String getCasstId() {
		return this.casstId;
	}

	public void setCasstId(String casstId) {
		this.casstId = casstId;
	}

	public FnaSelfspouseDets getFnaSelfspouseDets() {
		return this.fnaSelfspouseDets;
	}

	public void setFnaSelfspouseDets(FnaSelfspouseDets fnaSelfspouseDets) {
		this.fnaSelfspouseDets = fnaSelfspouseDets;
	}

	public Double getCasstSelfSavingfd() {
		return this.casstSelfSavingfd;
	}

	public void setCasstSelfSavingfd(Double casstSelfSavingfd) {
		this.casstSelfSavingfd = casstSelfSavingfd;
	}

	public Double getCasstSelfRegsaving() {
		return this.casstSelfRegsaving;
	}

	public void setCasstSelfRegsaving(Double casstSelfRegsaving) {
		this.casstSelfRegsaving = casstSelfRegsaving;
	}

	public Double getCasstSelfCashequ() {
		return this.casstSelfCashequ;
	}

	public void setCasstSelfCashequ(Double casstSelfCashequ) {
		this.casstSelfCashequ = casstSelfCashequ;
	}

	public Double getCasstSelfSrs() {
		return this.casstSelfSrs;
	}

	public void setCasstSelfSrs(Double casstSelfSrs) {
		this.casstSelfSrs = casstSelfSrs;
	}

	public Double getCasstSpsSavingfd() {
		return this.casstSpsSavingfd;
	}

	public void setCasstSpsSavingfd(Double casstSpsSavingfd) {
		this.casstSpsSavingfd = casstSpsSavingfd;
	}

	public Double getCasstSpsRegsaving() {
		return this.casstSpsRegsaving;
	}

	public void setCasstSpsRegsaving(Double casstSpsRegsaving) {
		this.casstSpsRegsaving = casstSpsRegsaving;
	}

	public Double getCasstSpsCashequ() {
		return this.casstSpsCashequ;
	}

	public void setCasstSpsCashequ(Double casstSpsCashequ) {
		this.casstSpsCashequ = casstSpsCashequ;
	}

	public Double getCasstSpsSrs() {
		return this.casstSpsSrs;
	}

	public void setCasstSpsSrs(Double casstSpsSrs) {
		this.casstSpsSrs = casstSpsSrs;
	}

	public Double getCasstFamSavingfd() {
		return this.casstFamSavingfd;
	}

	public void setCasstFamSavingfd(Double casstFamSavingfd) {
		this.casstFamSavingfd = casstFamSavingfd;
	}

	public Double getCasstFamRegsaving() {
		return this.casstFamRegsaving;
	}

	public void setCasstFamRegsaving(Double casstFamRegsaving) {
		this.casstFamRegsaving = casstFamRegsaving;
	}

	public Double getCasstFamCashequ() {
		return this.casstFamCashequ;
	}

	public void setCasstFamCashequ(Double casstFamCashequ) {
		this.casstFamCashequ = casstFamCashequ;
	}

	public Double getCasstRpSavingfd() {
		return this.casstRpSavingfd;
	}

	public void setCasstRpSavingfd(Double casstRpSavingfd) {
		this.casstRpSavingfd = casstRpSavingfd;
	}

	public Double getCasstRpRegsaving() {
		return this.casstRpRegsaving;
	}

	public void setCasstRpRegsaving(Double casstRpRegsaving) {
		this.casstRpRegsaving = casstRpRegsaving;
	}

	public Double getCasstRpCashequ() {
		return this.casstRpCashequ;
	}

	public void setCasstRpCashequ(Double casstRpCashequ) {
		this.casstRpCashequ = casstRpCashequ;
	}

	public Double getCasstRpSrs() {
		return this.casstRpSrs;
	}

	public void setCasstRpSrs(Double casstRpSrs) {
		this.casstRpSrs = casstRpSrs;
	}

	public String getCasstRemSavingfd() {
		return this.casstRemSavingfd;
	}

	public void setCasstRemSavingfd(String casstRemSavingfd) {
		this.casstRemSavingfd = casstRemSavingfd;
	}

	public String getCasstRemRegsaving() {
		return this.casstRemRegsaving;
	}

	public void setCasstRemRegsaving(String casstRemRegsaving) {
		this.casstRemRegsaving = casstRemRegsaving;
	}

	public String getCasstRemCashequ() {
		return this.casstRemCashequ;
	}

	public void setCasstRemCashequ(String casstRemCashequ) {
		this.casstRemCashequ = casstRemCashequ;
	}

	public String getCasstRemSrs() {
		return this.casstRemSrs;
	}

	public void setCasstRemSrs(String casstRemSrs) {
		this.casstRemSrs = casstRemSrs;
	}

	public Double getCasstSpsRpSavingfd() {
		return this.casstSpsRpSavingfd;
	}

	public void setCasstSpsRpSavingfd(Double casstSpsRpSavingfd) {
		this.casstSpsRpSavingfd = casstSpsRpSavingfd;
	}

	public Double getCasstSpsRpRegsaving() {
		return this.casstSpsRpRegsaving;
	}

	public void setCasstSpsRpRegsaving(Double casstSpsRpRegsaving) {
		this.casstSpsRpRegsaving = casstSpsRpRegsaving;
	}

	public Double getCasstSpsRpCashequ() {
		return this.casstSpsRpCashequ;
	}

	public void setCasstSpsRpCashequ(Double casstSpsRpCashequ) {
		this.casstSpsRpCashequ = casstSpsRpCashequ;
	}

	public Double getCasstSpsRpSrs() {
		return this.casstSpsRpSrs;
	}

	public void setCasstSpsRpSrs(Double casstSpsRpSrs) {
		this.casstSpsRpSrs = casstSpsRpSrs;
	}

	public String getCasstSpsRemSavingfd() {
		return this.casstSpsRemSavingfd;
	}

	public void setCasstSpsRemSavingfd(String casstSpsRemSavingfd) {
		this.casstSpsRemSavingfd = casstSpsRemSavingfd;
	}

	public String getCasstSpsRemRegsaving() {
		return this.casstSpsRemRegsaving;
	}

	public void setCasstSpsRemRegsaving(String casstSpsRemRegsaving) {
		this.casstSpsRemRegsaving = casstSpsRemRegsaving;
	}

	public String getCasstSpsRemCashequ() {
		return this.casstSpsRemCashequ;
	}

	public void setCasstSpsRemCashequ(String casstSpsRemCashequ) {
		this.casstSpsRemCashequ = casstSpsRemCashequ;
	}

	public String getCasstSpsRemSrs() {
		return this.casstSpsRemSrs;
	}

	public void setCasstSpsRemSrs(String casstSpsRemSrs) {
		this.casstSpsRemSrs = casstSpsRemSrs;
	}

	public Double getCasstFamRpSavingfd() {
		return this.casstFamRpSavingfd;
	}

	public void setCasstFamRpSavingfd(Double casstFamRpSavingfd) {
		this.casstFamRpSavingfd = casstFamRpSavingfd;
	}

	public Double getCasstFamRpRegsaving() {
		return this.casstFamRpRegsaving;
	}

	public void setCasstFamRpRegsaving(Double casstFamRpRegsaving) {
		this.casstFamRpRegsaving = casstFamRpRegsaving;
	}

	public Double getCasstFamRpCashequ() {
		return this.casstFamRpCashequ;
	}

	public void setCasstFamRpCashequ(Double casstFamRpCashequ) {
		this.casstFamRpCashequ = casstFamRpCashequ;
	}

	public String getCasstFamRemSavingfd() {
		return this.casstFamRemSavingfd;
	}

	public void setCasstFamRemSavingfd(String casstFamRemSavingfd) {
		this.casstFamRemSavingfd = casstFamRemSavingfd;
	}

	public String getCasstFamRemRegsaving() {
		return this.casstFamRemRegsaving;
	}

	public void setCasstFamRemRegsaving(String casstFamRemRegsaving) {
		this.casstFamRemRegsaving = casstFamRemRegsaving;
	}

	public String getCasstFamRemCashequ() {
		return this.casstFamRemCashequ;
	}

	public void setCasstFamRemCashequ(String casstFamRemCashequ) {
		this.casstFamRemCashequ = casstFamRemCashequ;
	}

	public Double getCasstFamSrs() {
		return this.casstFamSrs;
	}

	public void setCasstFamSrs(Double casstFamSrs) {
		this.casstFamSrs = casstFamSrs;
	}

	public Double getCasstFamRpSrs() {
		return this.casstFamRpSrs;
	}

	public void setCasstFamRpSrs(Double casstFamRpSrs) {
		this.casstFamRpSrs = casstFamRpSrs;
	}

	public String getCasstFamRemSrs() {
		return this.casstFamRemSrs;
	}

	public void setCasstFamRemSrs(String casstFamRemSrs) {
		this.casstFamRemSrs = casstFamRemSrs;
	}

	public Double getCasstSelfTotal() {
		return this.casstSelfTotal;
	}

	public void setCasstSelfTotal(Double casstSelfTotal) {
		this.casstSelfTotal = casstSelfTotal;
	}

	public Double getCasstSpsTotal() {
		return this.casstSpsTotal;
	}

	public void setCasstSpsTotal(Double casstSpsTotal) {
		this.casstSpsTotal = casstSpsTotal;
	}

	public Double getCasstFamTotal() {
		return this.casstFamTotal;
	}

	public void setCasstFamTotal(Double casstFamTotal) {
		this.casstFamTotal = casstFamTotal;
	}

	public String getCasstCreatedBy() {
		return this.casstCreatedBy;
	}

	public void setCasstCreatedBy(String casstCreatedBy) {
		this.casstCreatedBy = casstCreatedBy;
	}

	public Date getCasstCreatedDate() {
		return this.casstCreatedDate;
	}

	public void setCasstCreatedDate(Date casstCreatedDate) {
		this.casstCreatedDate = casstCreatedDate;
	}

	public String getCasstModifiedBy() {
		return this.casstModifiedBy;
	}

	public void setCasstModifiedBy(String casstModifiedBy) {
		this.casstModifiedBy = casstModifiedBy;
	}

	public Date getCasstModifiedDate() {
		return this.casstModifiedDate;
	}

	public void setCasstModifiedDate(Date casstModifiedDate) {
		this.casstModifiedDate = casstModifiedDate;
	}

}
