package com.fipa.dto;

// Generated May 17, 2018 11:20:36 AM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * FnaAssetBusiandpersdets generated by hbm2java
 */
public class FnaAssetBusiandpersdets implements java.io.Serializable {

	private String busipersId;
	private FnaSelfspouseDets fnaSelfspouseDets;
	private String assetCateg;
	private String acctHolder;
	private String typeOfAsset;
	private String nameOfAsset;
	private Double purInvValue;
	private Double currValue;
	private Double osValue;
	private Double estApprValue;
	private String yrs2keep;
	private Double childEdnPrcnt;
	private Double retPlanPrcnt;
	private String remarks;
	private String crtdBy;
	private Date crtdDate;
	private String modBy;
	private Date modDate;

	public FnaAssetBusiandpersdets() {
	}

	public FnaAssetBusiandpersdets(String busipersId) {
		this.busipersId = busipersId;
	}

	public FnaAssetBusiandpersdets(String busipersId,
			FnaSelfspouseDets fnaSelfspouseDets, String assetCateg,
			String acctHolder, String typeOfAsset, String nameOfAsset,
			Double purInvValue, Double currValue, Double osValue,
			Double estApprValue, String yrs2keep, Double childEdnPrcnt,
			Double retPlanPrcnt, String remarks, String crtdBy, Date crtdDate,
			String modBy, Date modDate) {
		this.busipersId = busipersId;
		this.fnaSelfspouseDets = fnaSelfspouseDets;
		this.assetCateg = assetCateg;
		this.acctHolder = acctHolder;
		this.typeOfAsset = typeOfAsset;
		this.nameOfAsset = nameOfAsset;
		this.purInvValue = purInvValue;
		this.currValue = currValue;
		this.osValue = osValue;
		this.estApprValue = estApprValue;
		this.yrs2keep = yrs2keep;
		this.childEdnPrcnt = childEdnPrcnt;
		this.retPlanPrcnt = retPlanPrcnt;
		this.remarks = remarks;
		this.crtdBy = crtdBy;
		this.crtdDate = crtdDate;
		this.modBy = modBy;
		this.modDate = modDate;
	}

	public String getBusipersId() {
		return this.busipersId;
	}

	public void setBusipersId(String busipersId) {
		this.busipersId = busipersId;
	}

	public FnaSelfspouseDets getFnaSelfspouseDets() {
		return this.fnaSelfspouseDets;
	}

	public void setFnaSelfspouseDets(FnaSelfspouseDets fnaSelfspouseDets) {
		this.fnaSelfspouseDets = fnaSelfspouseDets;
	}

	public String getAssetCateg() {
		return this.assetCateg;
	}

	public void setAssetCateg(String assetCateg) {
		this.assetCateg = assetCateg;
	}

	public String getAcctHolder() {
		return this.acctHolder;
	}

	public void setAcctHolder(String acctHolder) {
		this.acctHolder = acctHolder;
	}

	public String getTypeOfAsset() {
		return this.typeOfAsset;
	}

	public void setTypeOfAsset(String typeOfAsset) {
		this.typeOfAsset = typeOfAsset;
	}

	public String getNameOfAsset() {
		return this.nameOfAsset;
	}

	public void setNameOfAsset(String nameOfAsset) {
		this.nameOfAsset = nameOfAsset;
	}

	public Double getPurInvValue() {
		return this.purInvValue;
	}

	public void setPurInvValue(Double purInvValue) {
		this.purInvValue = purInvValue;
	}

	public Double getCurrValue() {
		return this.currValue;
	}

	public void setCurrValue(Double currValue) {
		this.currValue = currValue;
	}

	public Double getOsValue() {
		return this.osValue;
	}

	public void setOsValue(Double osValue) {
		this.osValue = osValue;
	}

	public Double getEstApprValue() {
		return this.estApprValue;
	}

	public void setEstApprValue(Double estApprValue) {
		this.estApprValue = estApprValue;
	}

	public String getYrs2keep() {
		return this.yrs2keep;
	}

	public void setYrs2keep(String yrs2keep) {
		this.yrs2keep = yrs2keep;
	}

	public Double getChildEdnPrcnt() {
		return this.childEdnPrcnt;
	}

	public void setChildEdnPrcnt(Double childEdnPrcnt) {
		this.childEdnPrcnt = childEdnPrcnt;
	}

	public Double getRetPlanPrcnt() {
		return this.retPlanPrcnt;
	}

	public void setRetPlanPrcnt(Double retPlanPrcnt) {
		this.retPlanPrcnt = retPlanPrcnt;
	}

	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	public String getCrtdBy() {
		return this.crtdBy;
	}

	public void setCrtdBy(String crtdBy) {
		this.crtdBy = crtdBy;
	}

	public Date getCrtdDate() {
		return this.crtdDate;
	}

	public void setCrtdDate(Date crtdDate) {
		this.crtdDate = crtdDate;
	}

	public String getModBy() {
		return this.modBy;
	}

	public void setModBy(String modBy) {
		this.modBy = modBy;
	}

	public Date getModDate() {
		return this.modDate;
	}

	public void setModDate(Date modDate) {
		this.modDate = modDate;
	}

}
