package com.fipa.dto;

// Generated May 17, 2018 11:20:36 AM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * FnaCashAtBank generated by hbm2java
 */
public class FnaCashAtBank implements java.io.Serializable {

	private String cashBankId;
	private FnaSelfspouseDets fnaSelfspouseDets;
	private String mainAccountHolder;
	private String suppAccountHolder;
	private String relationship;
	private String ownershipType;
	private String bankName;
	private String bankAccNo;
	private String accountType;
	private Double currentBalance;
	private Double regularDeposit;
	private String depositFrequency;
	private Date periodFrom;
	private Date periodTo;
	private String objective;
	private Double retirementPrcnt;
	private String childName;
	private String remarks;
	private String bankAccCrtdBy;
	private Date bankAccCrtdDate;
	private String bankAccModifiedBy;
	private Date bankAccModifiedDate;
	private String cbRefId;
	private String fnaDescription;
	private Double periodRegularDeposit;
	
	

	

	public FnaCashAtBank() {
	}

	public FnaCashAtBank(String cashBankId, String mainAccountHolder,
			String bankName, String bankAccNo, String bankAccCrtdBy,
			Date bankAccCrtdDate) {
		this.cashBankId = cashBankId;
		this.mainAccountHolder = mainAccountHolder;
		this.bankName = bankName;
		this.bankAccNo = bankAccNo;
		this.bankAccCrtdBy = bankAccCrtdBy;
		this.bankAccCrtdDate = bankAccCrtdDate;
	}

	

	public FnaCashAtBank(String cashBankId, FnaSelfspouseDets fnaSelfspouseDets, String mainAccountHolder,
			String suppAccountHolder, String relationship, String ownershipType, String bankName, String bankAccNo,
			String accountType, Double currentBalance, Double regularDeposit, String depositFrequency, Date periodFrom,
			Date periodTo, String objective, Double retirementPrcnt, String childName, String remarks,
			String bankAccCrtdBy, Date bankAccCrtdDate, String bankAccModifiedBy, Date bankAccModifiedDate,
			String cbRefId,String fnaDescription,Double periodRegularDeposit) {
	 
		this.cashBankId = cashBankId;
		this.fnaSelfspouseDets = fnaSelfspouseDets;
		this.mainAccountHolder = mainAccountHolder;
		this.suppAccountHolder = suppAccountHolder;
		this.relationship = relationship;
		this.ownershipType = ownershipType;
		this.bankName = bankName;
		this.bankAccNo = bankAccNo;
		this.accountType = accountType;
		this.currentBalance = currentBalance;
		this.regularDeposit = regularDeposit;
		this.depositFrequency = depositFrequency;
		this.periodFrom = periodFrom;
		this.periodTo = periodTo;
		this.objective = objective;
		this.retirementPrcnt = retirementPrcnt;
		this.childName = childName;
		this.remarks = remarks;
		this.bankAccCrtdBy = bankAccCrtdBy;
		this.bankAccCrtdDate = bankAccCrtdDate;
		this.bankAccModifiedBy = bankAccModifiedBy;
		this.bankAccModifiedDate = bankAccModifiedDate;
		this.cbRefId = cbRefId;
		this.fnaDescription = fnaDescription;
		this.periodRegularDeposit = periodRegularDeposit;
	}

	public String getCbRefId() {
		return this.cbRefId;
	}

	public void setCbRefId(String cbRefId) {
		this.cbRefId = cbRefId;
	}

	public String getCashBankId() {
		return this.cashBankId;
	}

	public void setCashBankId(String cashBankId) {
		this.cashBankId = cashBankId;
	}

	public FnaSelfspouseDets getFnaSelfspouseDets() {
		return this.fnaSelfspouseDets;
	}

	public void setFnaSelfspouseDets(FnaSelfspouseDets fnaSelfspouseDets) {
		this.fnaSelfspouseDets = fnaSelfspouseDets;
	}

	public String getMainAccountHolder() {
		return this.mainAccountHolder;
	}

	public void setMainAccountHolder(String mainAccountHolder) {
		this.mainAccountHolder = mainAccountHolder;
	}

	public String getSuppAccountHolder() {
		return this.suppAccountHolder;
	}

	public void setSuppAccountHolder(String suppAccountHolder) {
		this.suppAccountHolder = suppAccountHolder;
	}

	public String getRelationship() {
		return this.relationship;
	}

	public void setRelationship(String relationship) {
		this.relationship = relationship;
	}

	public String getOwnershipType() {
		return this.ownershipType;
	}

	public void setOwnershipType(String ownershipType) {
		this.ownershipType = ownershipType;
	}

	public String getBankName() {
		return this.bankName;
	}

	public void setBankName(String bankName) {
		this.bankName = bankName;
	}

	public String getBankAccNo() {
		return this.bankAccNo;
	}

	public void setBankAccNo(String bankAccNo) {
		this.bankAccNo = bankAccNo;
	}

	public String getAccountType() {
		return this.accountType;
	}

	public void setAccountType(String accountType) {
		this.accountType = accountType;
	}

	public Double getCurrentBalance() {
		return this.currentBalance;
	}

	public void setCurrentBalance(Double currentBalance) {
		this.currentBalance = currentBalance;
	}

	public Double getRegularDeposit() {
		return this.regularDeposit;
	}

	public void setRegularDeposit(Double regularDeposit) {
		this.regularDeposit = regularDeposit;
	}

	public String getDepositFrequency() {
		return this.depositFrequency;
	}

	public void setDepositFrequency(String depositFrequency) {
		this.depositFrequency = depositFrequency;
	}

	public Date getPeriodFrom() {
		return this.periodFrom;
	}

	public void setPeriodFrom(Date periodFrom) {
		this.periodFrom = periodFrom;
	}

	public Date getPeriodTo() {
		return this.periodTo;
	}

	public void setPeriodTo(Date periodTo) {
		this.periodTo = periodTo;
	}

	public String getObjective() {
		return this.objective;
	}

	public void setObjective(String objective) {
		this.objective = objective;
	}

	public Double getRetirementPrcnt() {
		return this.retirementPrcnt;
	}

	public void setRetirementPrcnt(Double retirementPrcnt) {
		this.retirementPrcnt = retirementPrcnt;
	}

	public String getChildName() {
		return this.childName;
	}

	public void setChildName(String childName) {
		this.childName = childName;
	}

	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	public String getFnaDescription() {
		return fnaDescription;
	}

	public void setFnaDescription(String fnaDescription) {
		this.fnaDescription = fnaDescription;
	}
	public String getBankAccCrtdBy() {
		return this.bankAccCrtdBy;
	}

	public void setBankAccCrtdBy(String bankAccCrtdBy) {
		this.bankAccCrtdBy = bankAccCrtdBy;
	}

	public Date getBankAccCrtdDate() {
		return this.bankAccCrtdDate;
	}

	public void setBankAccCrtdDate(Date bankAccCrtdDate) {
		this.bankAccCrtdDate = bankAccCrtdDate;
	}

	public String getBankAccModifiedBy() {
		return this.bankAccModifiedBy;
	}

	public void setBankAccModifiedBy(String bankAccModifiedBy) {
		this.bankAccModifiedBy = bankAccModifiedBy;
	}

	public Date getBankAccModifiedDate() {
		return this.bankAccModifiedDate;
	}

	public void setBankAccModifiedDate(Date bankAccModifiedDate) {
		this.bankAccModifiedDate = bankAccModifiedDate;
	}
	
	public Double getPeriodRegularDeposit() {
		return periodRegularDeposit;
	}

	public void setPeriodRegularDeposit(Double periodRegularDeposit) {
		this.periodRegularDeposit = periodRegularDeposit;
	}

}
