package com.fipa.dto;

// Generated May 17, 2018 11:20:36 AM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * FnaCpfBalanceDets generated by hbm2java
 */
public class FnaCpfBalanceDets implements java.io.Serializable {

	private String cpfId;//
	private MasterCpfAcctype masterCpfAcctype;
	private FnaSelfspouseDets fnaSelfspouseDets;
	private Double cpfSelfBalance;
	private String cpfSelfOrSps;
	private String cpfCrtdBy;
	private Date cpfCrtdDate;
	private String cpfModBy;
	private Date cpfModDate;

	public FnaCpfBalanceDets() {
	}

	public FnaCpfBalanceDets(String cpfId) {
		this.cpfId = cpfId;
	}

	public FnaCpfBalanceDets(String cpfId, MasterCpfAcctype masterCpfAcctype,
			FnaSelfspouseDets fnaSelfspouseDets, Double cpfSelfBalance,
			String cpfSelfOrSps, String cpfCrtdBy, Date cpfCrtdDate,
			String cpfModBy, Date cpfModDate) {
		this.cpfId = cpfId;
		this.masterCpfAcctype = masterCpfAcctype;
		this.fnaSelfspouseDets = fnaSelfspouseDets;
		this.cpfSelfBalance = cpfSelfBalance;
		this.cpfSelfOrSps = cpfSelfOrSps;
		this.cpfCrtdBy = cpfCrtdBy;
		this.cpfCrtdDate = cpfCrtdDate;
		this.cpfModBy = cpfModBy;
		this.cpfModDate = cpfModDate;
	}

	public String getCpfId() {
		return this.cpfId;
	}

	public void setCpfId(String cpfId) {
		this.cpfId = cpfId;
	}

	public MasterCpfAcctype getMasterCpfAcctype() {
		return this.masterCpfAcctype;
	}

	public void setMasterCpfAcctype(MasterCpfAcctype masterCpfAcctype) {
		this.masterCpfAcctype = masterCpfAcctype;
	}

	public FnaSelfspouseDets getFnaSelfspouseDets() {
		return this.fnaSelfspouseDets;
	}

	public void setFnaSelfspouseDets(FnaSelfspouseDets fnaSelfspouseDets) {
		this.fnaSelfspouseDets = fnaSelfspouseDets;
	}

	public Double getCpfSelfBalance() {
		return this.cpfSelfBalance;
	}

	public void setCpfSelfBalance(Double cpfSelfBalance) {
		this.cpfSelfBalance = cpfSelfBalance;
	}

	public String getCpfSelfOrSps() {
		return this.cpfSelfOrSps;
	}

	public void setCpfSelfOrSps(String cpfSelfOrSps) {
		this.cpfSelfOrSps = cpfSelfOrSps;
	}

	public String getCpfCrtdBy() {
		return this.cpfCrtdBy;
	}

	public void setCpfCrtdBy(String cpfCrtdBy) {
		this.cpfCrtdBy = cpfCrtdBy;
	}

	public Date getCpfCrtdDate() {
		return this.cpfCrtdDate;
	}

	public void setCpfCrtdDate(Date cpfCrtdDate) {
		this.cpfCrtdDate = cpfCrtdDate;
	}

	public String getCpfModBy() {
		return this.cpfModBy;
	}

	public void setCpfModBy(String cpfModBy) {
		this.cpfModBy = cpfModBy;
	}

	public Date getCpfModDate() {
		return this.cpfModDate;
	}

	public void setCpfModDate(Date cpfModDate) {
		this.cpfModDate = cpfModDate;
	}

}
