package com.fipa.dto;

// Generated May 17, 2018 11:20:36 AM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * FnaCurassDets generated by hbm2java
 */
public class FnaCurassDets implements java.io.Serializable {

	private String caId;//
	private FnaSelfspouseDets fnaSelfspouseDets;
	private Double caSelfRoi;//
	private Double caSpsRoi;//
	private Double caFamRoi;//
	private Double caGenInfrate;//
	private Double caEdnInfrate;//
	private Double caSavingDeprate;//
	private Double caBonds;//
	private Double caUtilp;//
	private Double caShares;//
	private Double caOthinv;//
	private String caCreatedBy;//
	private Date caCreatedDate;//
	private String caModifiedBy;
	private Date caModifiedDate;
	private Double caProjSelfRoi;
	private Double caProjSpsRoi;
	private Double caProjFamRoi;
//	 <!--changes done 19/06/2019 --> 
	private Double caSRSSatRetAge;
	

	public FnaCurassDets() {
	}

	public FnaCurassDets(String caId) {
		this.caId = caId;
	}

	public FnaCurassDets(String caId, FnaSelfspouseDets fnaSelfspouseDets,
			Double caSelfRoi, Double caSpsRoi, Double caFamRoi,
			Double caGenInfrate, Double caEdnInfrate, Double caSavingDeprate,
			Double caBonds, Double caUtilp, Double caShares, Double caOthinv,
			String caCreatedBy, Date caCreatedDate, String caModifiedBy,
			Date caModifiedDate,Double caProjSelfRoi,Double caProjSpsRoi,
			Double caProjFamRoi,Double caSRSSatRetAge) {
		this.caId = caId;
		this.fnaSelfspouseDets = fnaSelfspouseDets;
		this.caSelfRoi = caSelfRoi;
		this.caSpsRoi = caSpsRoi;
		this.caFamRoi = caFamRoi;
		this.caGenInfrate = caGenInfrate;
		this.caEdnInfrate = caEdnInfrate;
		this.caSavingDeprate = caSavingDeprate;
		this.caBonds = caBonds;
		this.caUtilp = caUtilp;
		this.caShares = caShares;
		this.caOthinv = caOthinv;
		this.caCreatedBy = caCreatedBy;
		this.caCreatedDate = caCreatedDate;
		this.caModifiedBy = caModifiedBy;
		this.caModifiedDate = caModifiedDate;
		this.caProjSelfRoi=caProjSelfRoi;
		this.caProjSpsRoi=caProjSpsRoi;
		this.caProjFamRoi=caProjFamRoi;
		this.caSRSSatRetAge=caSRSSatRetAge;
	}

	public String getCaId() {
		return this.caId;
	}

	public void setCaId(String caId) {
		this.caId = caId;
	}

	public FnaSelfspouseDets getFnaSelfspouseDets() {
		return this.fnaSelfspouseDets;
	}

	public void setFnaSelfspouseDets(FnaSelfspouseDets fnaSelfspouseDets) {
		this.fnaSelfspouseDets = fnaSelfspouseDets;
	}

	public Double getCaSRSSatRetAge() {
		return this.caSRSSatRetAge;
	}

	public void setCaSRSSatRetAge(Double caSRSSatRetAge) {
		this.caSRSSatRetAge = caSRSSatRetAge;
	}

	public Double getCaSelfRoi() {
		return this.caSelfRoi;
	}

	public void setCaSelfRoi(Double caSelfRoi) {
		this.caSelfRoi = caSelfRoi;
	}

	public Double getCaSpsRoi() {
		return this.caSpsRoi;
	}

	public void setCaSpsRoi(Double caSpsRoi) {
		this.caSpsRoi = caSpsRoi;
	}

	public Double getCaFamRoi() {
		return this.caFamRoi;
	}

	public void setCaFamRoi(Double caFamRoi) {
		this.caFamRoi = caFamRoi;
	}

	public Double getCaGenInfrate() {
		return this.caGenInfrate;
	}

	public void setCaGenInfrate(Double caGenInfrate) {
		this.caGenInfrate = caGenInfrate;
	}

	public Double getCaEdnInfrate() {
		return this.caEdnInfrate;
	}

	public void setCaEdnInfrate(Double caEdnInfrate) {
		this.caEdnInfrate = caEdnInfrate;
	}

	public Double getCaSavingDeprate() {
		return this.caSavingDeprate;
	}

	public void setCaSavingDeprate(Double caSavingDeprate) {
		this.caSavingDeprate = caSavingDeprate;
	}

	public Double getCaBonds() {
		return this.caBonds;
	}

	public void setCaBonds(Double caBonds) {
		this.caBonds = caBonds;
	}

	public Double getCaUtilp() {
		return this.caUtilp;
	}

	public void setCaUtilp(Double caUtilp) {
		this.caUtilp = caUtilp;
	}

	public Double getCaShares() {
		return this.caShares;
	}

	public void setCaShares(Double caShares) {
		this.caShares = caShares;
	}

	public Double getCaOthinv() {
		return this.caOthinv;
	}

	public void setCaOthinv(Double caOthinv) {
		this.caOthinv = caOthinv;
	}

	public String getCaCreatedBy() {
		return this.caCreatedBy;
	}

	public void setCaCreatedBy(String caCreatedBy) {
		this.caCreatedBy = caCreatedBy;
	}

	public Date getCaCreatedDate() {
		return this.caCreatedDate;
	}

	public void setCaCreatedDate(Date caCreatedDate) {
		this.caCreatedDate = caCreatedDate;
	}

	public String getCaModifiedBy() {
		return this.caModifiedBy;
	}

	public void setCaModifiedBy(String caModifiedBy) {
		this.caModifiedBy = caModifiedBy;
	}

	public Date getCaModifiedDate() {
		return this.caModifiedDate;
	}

	public void setCaModifiedDate(Date caModifiedDate) {
		this.caModifiedDate = caModifiedDate;
	}

	public Double getCaProjSelfRoi() {
		return caProjSelfRoi;
	}

	public void setCaProjSelfRoi(Double caProjSelfRoi) {
		this.caProjSelfRoi = caProjSelfRoi;
	}

	public Double getCaProjSpsRoi() {
		return caProjSpsRoi;
	}

	public void setCaProjSpsRoi(Double caProjSpsRoi) {
		this.caProjSpsRoi = caProjSpsRoi;
	}

	public Double getCaProjFamRoi() {
		return caProjFamRoi;
	}

	public void setCaProjFamRoi(Double caProjFamRoi) {
		this.caProjFamRoi = caProjFamRoi;
	}

}
