package com.fipa.dto;

// Generated May 17, 2018 11:20:36 AM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * FnaChilddetails generated by hbm2java
 */
public class FnaChilddetails implements java.io.Serializable {

	private String fnaChildId;
	private FnaSelfspouseDets fnaSelfspouseDets;
	private String childName;
	private Date childDob;
	private String childAge;
	private String childRelation;
	private String childGender;
	private String childYrs2tertiary;
	private String childCource;
	private String childUniversity;
	private String childYrsofeducation;
	private Double childPerannEducost;
	private Double childPerannLivingcost;
	private Double childAvailEdnfund;
	private String childRemarks;
	private String childCrtdBy;
	private Date childCrtdDate;
	private String childModifiedBy;
	private Date childModifiedDate;
	private String childRb;
	private String childWard;
	private String childHosptype;

	public FnaChilddetails() {
	}

	public FnaChilddetails(String fnaChildId, String childCrtdBy,
			Date childCrtdDate) {
		this.fnaChildId = fnaChildId;
		this.childCrtdBy = childCrtdBy;
		this.childCrtdDate = childCrtdDate;
	}

	public FnaChilddetails(String fnaChildId,
			FnaSelfspouseDets fnaSelfspouseDets, String childName,
			Date childDob, String childAge, String childRelation,
			String childGender, String childYrs2tertiary, String childCource,
			String childUniversity, String childYrsofeducation,
			Double childPerannEducost, Double childPerannLivingcost,
			Double childAvailEdnfund, String childRemarks, String childCrtdBy,
			Date childCrtdDate, String childModifiedBy, Date childModifiedDate,
			String childRb, String childWard, String childHosptype) {
		this.fnaChildId = fnaChildId;
		this.fnaSelfspouseDets = fnaSelfspouseDets;
		this.childName = childName;
		this.childDob = childDob;
		this.childAge = childAge;
		this.childRelation = childRelation;
		this.childGender = childGender;
		this.childYrs2tertiary = childYrs2tertiary;
		this.childCource = childCource;
		this.childUniversity = childUniversity;
		this.childYrsofeducation = childYrsofeducation;
		this.childPerannEducost = childPerannEducost;
		this.childPerannLivingcost = childPerannLivingcost;
		this.childAvailEdnfund = childAvailEdnfund;
		this.childRemarks = childRemarks;
		this.childCrtdBy = childCrtdBy;
		this.childCrtdDate = childCrtdDate;
		this.childModifiedBy = childModifiedBy;
		this.childModifiedDate = childModifiedDate;
		this.childRb = childRb;
		this.childWard = childWard;
		this.childHosptype = childHosptype;
	}

	public String getFnaChildId() {
		return this.fnaChildId;
	}

	public void setFnaChildId(String fnaChildId) {
		this.fnaChildId = fnaChildId;
	}

	public FnaSelfspouseDets getFnaSelfspouseDets() {
		return this.fnaSelfspouseDets;
	}

	public void setFnaSelfspouseDets(FnaSelfspouseDets fnaSelfspouseDets) {
		this.fnaSelfspouseDets = fnaSelfspouseDets;
	}

	public String getChildName() {
		return this.childName;
	}

	public void setChildName(String childName) {
		this.childName = childName;
	}

	public Date getChildDob() {
		return this.childDob;
	}

	public void setChildDob(Date childDob) {
		this.childDob = childDob;
	}

	public String getChildAge() {
		return this.childAge;
	}

	public void setChildAge(String childAge) {
		this.childAge = childAge;
	}

	public String getChildRelation() {
		return this.childRelation;
	}

	public void setChildRelation(String childRelation) {
		this.childRelation = childRelation;
	}

	public String getChildGender() {
		return this.childGender;
	}

	public void setChildGender(String childGender) {
		this.childGender = childGender;
	}

	public String getChildYrs2tertiary() {
		return this.childYrs2tertiary;
	}

	public void setChildYrs2tertiary(String childYrs2tertiary) {
		this.childYrs2tertiary = childYrs2tertiary;
	}

	public String getChildCource() {
		return this.childCource;
	}

	public void setChildCource(String childCource) {
		this.childCource = childCource;
	}

	public String getChildUniversity() {
		return this.childUniversity;
	}

	public void setChildUniversity(String childUniversity) {
		this.childUniversity = childUniversity;
	}

	public String getChildYrsofeducation() {
		return this.childYrsofeducation;
	}

	public void setChildYrsofeducation(String childYrsofeducation) {
		this.childYrsofeducation = childYrsofeducation;
	}

	public Double getChildPerannEducost() {
		return this.childPerannEducost;
	}

	public void setChildPerannEducost(Double childPerannEducost) {
		this.childPerannEducost = childPerannEducost;
	}

	public Double getChildPerannLivingcost() {
		return this.childPerannLivingcost;
	}

	public void setChildPerannLivingcost(Double childPerannLivingcost) {
		this.childPerannLivingcost = childPerannLivingcost;
	}

	public Double getChildAvailEdnfund() {
		return this.childAvailEdnfund;
	}

	public void setChildAvailEdnfund(Double childAvailEdnfund) {
		this.childAvailEdnfund = childAvailEdnfund;
	}

	public String getChildRemarks() {
		return this.childRemarks;
	}

	public void setChildRemarks(String childRemarks) {
		this.childRemarks = childRemarks;
	}

	public String getChildCrtdBy() {
		return this.childCrtdBy;
	}

	public void setChildCrtdBy(String childCrtdBy) {
		this.childCrtdBy = childCrtdBy;
	}

	public Date getChildCrtdDate() {
		return this.childCrtdDate;
	}

	public void setChildCrtdDate(Date childCrtdDate) {
		this.childCrtdDate = childCrtdDate;
	}

	public String getChildModifiedBy() {
		return this.childModifiedBy;
	}

	public void setChildModifiedBy(String childModifiedBy) {
		this.childModifiedBy = childModifiedBy;
	}

	public Date getChildModifiedDate() {
		return this.childModifiedDate;
	}

	public void setChildModifiedDate(Date childModifiedDate) {
		this.childModifiedDate = childModifiedDate;
	}

	public String getChildRb() {
		return this.childRb;
	}

	public void setChildRb(String childRb) {
		this.childRb = childRb;
	}

	public String getChildWard() {
		return this.childWard;
	}

	public void setChildWard(String childWard) {
		this.childWard = childWard;
	}

	public String getChildHosptype() {
		return this.childHosptype;
	}

	public void setChildHosptype(String childHosptype) {
		this.childHosptype = childHosptype;
	}

}
