package com.fipa.dto;

// Generated May 17, 2018 11:20:36 AM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * FnaCpfMonthcontDets generated by hbm2java
 */
public class FnaCpfMonthcontDets implements java.io.Serializable {

	private String ccPkId;
	private FnaSelfspouseDets fnaSelfspouseDets;
	private String ccSelfOrSps;
	private Double ccEmpleContrb;
	private Double ccEmplrContrb;
	private String ccCrtdBy;
	private Date ccCrtdDate;
	private String ccModBy;
	private Date ccModDate;

	public FnaCpfMonthcontDets() {
	}

	public FnaCpfMonthcontDets(String ccPkId) {
		this.ccPkId = ccPkId;
	}

	public FnaCpfMonthcontDets(String ccPkId,
			FnaSelfspouseDets fnaSelfspouseDets, String ccSelfOrSps,
			Double ccEmpleContrb, Double ccEmplrContrb, String ccCrtdBy,
			Date ccCrtdDate, String ccModBy, Date ccModDate) {
		this.ccPkId = ccPkId;
		this.fnaSelfspouseDets = fnaSelfspouseDets;
		this.ccSelfOrSps = ccSelfOrSps;
		this.ccEmpleContrb = ccEmpleContrb;
		this.ccEmplrContrb = ccEmplrContrb;
		this.ccCrtdBy = ccCrtdBy;
		this.ccCrtdDate = ccCrtdDate;
		this.ccModBy = ccModBy;
		this.ccModDate = ccModDate;
	}

	public String getCcPkId() {
		return this.ccPkId;
	}

	public void setCcPkId(String ccPkId) {
		this.ccPkId = ccPkId;
	}

	public FnaSelfspouseDets getFnaSelfspouseDets() {
		return this.fnaSelfspouseDets;
	}

	public void setFnaSelfspouseDets(FnaSelfspouseDets fnaSelfspouseDets) {
		this.fnaSelfspouseDets = fnaSelfspouseDets;
	}

	public String getCcSelfOrSps() {
		return this.ccSelfOrSps;
	}

	public void setCcSelfOrSps(String ccSelfOrSps) {
		this.ccSelfOrSps = ccSelfOrSps;
	}

	public Double getCcEmpleContrb() {
		return this.ccEmpleContrb;
	}

	public void setCcEmpleContrb(Double ccEmpleContrb) {
		this.ccEmpleContrb = ccEmpleContrb;
	}

	public Double getCcEmplrContrb() {
		return this.ccEmplrContrb;
	}

	public void setCcEmplrContrb(Double ccEmplrContrb) {
		this.ccEmplrContrb = ccEmplrContrb;
	}

	public String getCcCrtdBy() {
		return this.ccCrtdBy;
	}

	public void setCcCrtdBy(String ccCrtdBy) {
		this.ccCrtdBy = ccCrtdBy;
	}

	public Date getCcCrtdDate() {
		return this.ccCrtdDate;
	}

	public void setCcCrtdDate(Date ccCrtdDate) {
		this.ccCrtdDate = ccCrtdDate;
	}

	public String getCcModBy() {
		return this.ccModBy;
	}

	public void setCcModBy(String ccModBy) {
		this.ccModBy = ccModBy;
	}

	public Date getCcModDate() {
		return this.ccModDate;
	}

	public void setCcModDate(Date ccModDate) {
		this.ccModDate = ccModDate;
	}

}
