package com.fipa.dto;

// Generated May 17, 2018 11:20:36 AM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * FnaDependantDets generated by hbm2java
 */
public class FnaDependantDets implements java.io.Serializable {

	private String depnId;
	private FnaSelfspouseDets fnaSelfspouseDets;
	private String depnName;
	private String depnRelationship;
	private Date depnDob;
	private String depnAge;
	private String depnGender;
	private String depnYrssupport;
	private Double depnMonthcontr;
	private Double depnProvSelf;
	private Double depnProvSpouse;
	private String depnCreatedBy;
	private Date depnCreatedDate;
	private String depnModifiedBy;
	private Date depnModifiedDate;

	public FnaDependantDets() {
	}

	public FnaDependantDets(String depnId) {
		this.depnId = depnId;
	}

	public FnaDependantDets(String depnId, FnaSelfspouseDets fnaSelfspouseDets,
			String depnName, String depnRelationship, Date depnDob,
			String depnAge, String depnGender, String depnYrssupport,
			Double depnMonthcontr, Double depnProvSelf, Double depnProvSpouse,
			String depnCreatedBy, Date depnCreatedDate, String depnModifiedBy,
			Date depnModifiedDate) {
		this.depnId = depnId;
		this.fnaSelfspouseDets = fnaSelfspouseDets;
		this.depnName = depnName;
		this.depnRelationship = depnRelationship;
		this.depnDob = depnDob;
		this.depnAge = depnAge;
		this.depnGender = depnGender;
		this.depnYrssupport = depnYrssupport;
		this.depnMonthcontr = depnMonthcontr;
		this.depnProvSelf = depnProvSelf;
		this.depnProvSpouse = depnProvSpouse;
		this.depnCreatedBy = depnCreatedBy;
		this.depnCreatedDate = depnCreatedDate;
		this.depnModifiedBy = depnModifiedBy;
		this.depnModifiedDate = depnModifiedDate;
	}

	public String getDepnId() {
		return this.depnId;
	}

	public void setDepnId(String depnId) {
		this.depnId = depnId;
	}

	public FnaSelfspouseDets getFnaSelfspouseDets() {
		return this.fnaSelfspouseDets;
	}

	public void setFnaSelfspouseDets(FnaSelfspouseDets fnaSelfspouseDets) {
		this.fnaSelfspouseDets = fnaSelfspouseDets;
	}

	public String getDepnName() {
		return this.depnName;
	}

	public void setDepnName(String depnName) {
		this.depnName = depnName;
	}

	public String getDepnRelationship() {
		return this.depnRelationship;
	}

	public void setDepnRelationship(String depnRelationship) {
		this.depnRelationship = depnRelationship;
	}

	public Date getDepnDob() {
		return this.depnDob;
	}

	public void setDepnDob(Date depnDob) {
		this.depnDob = depnDob;
	}

	public String getDepnAge() {
		return this.depnAge;
	}

	public void setDepnAge(String depnAge) {
		this.depnAge = depnAge;
	}

	public String getDepnGender() {
		return this.depnGender;
	}

	public void setDepnGender(String depnGender) {
		this.depnGender = depnGender;
	}

	public String getDepnYrssupport() {
		return this.depnYrssupport;
	}

	public void setDepnYrssupport(String depnYrssupport) {
		this.depnYrssupport = depnYrssupport;
	}

	public Double getDepnMonthcontr() {
		return this.depnMonthcontr;
	}

	public void setDepnMonthcontr(Double depnMonthcontr) {
		this.depnMonthcontr = depnMonthcontr;
	}

	public Double getDepnProvSelf() {
		return this.depnProvSelf;
	}

	public void setDepnProvSelf(Double depnProvSelf) {
		this.depnProvSelf = depnProvSelf;
	}

	public Double getDepnProvSpouse() {
		return this.depnProvSpouse;
	}

	public void setDepnProvSpouse(Double depnProvSpouse) {
		this.depnProvSpouse = depnProvSpouse;
	}

	public String getDepnCreatedBy() {
		return this.depnCreatedBy;
	}

	public void setDepnCreatedBy(String depnCreatedBy) {
		this.depnCreatedBy = depnCreatedBy;
	}

	public Date getDepnCreatedDate() {
		return this.depnCreatedDate;
	}

	public void setDepnCreatedDate(Date depnCreatedDate) {
		this.depnCreatedDate = depnCreatedDate;
	}

	public String getDepnModifiedBy() {
		return this.depnModifiedBy;
	}

	public void setDepnModifiedBy(String depnModifiedBy) {
		this.depnModifiedBy = depnModifiedBy;
	}

	public Date getDepnModifiedDate() {
		return this.depnModifiedDate;
	}

	public void setDepnModifiedDate(Date depnModifiedDate) {
		this.depnModifiedDate = depnModifiedDate;
	}

}
