package com.fipa.dto;

// Generated May 17, 2018 11:20:36 AM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * FnaExpenditureDets generated by hbm2java
 */
public class FnaExpenditureDets implements java.io.Serializable {

	private String expdId;//
	private FnaSelfspouseDets fnaSelfspouseDets;
	private Double expdSelfRent;//
	private Double expdSelfUtil;//
	private Double expdSelfGrocery;//
	private Double expdSelfEatingout;//
	private Double expdSelfClothing;//
	private Double expdSelfTransport;//
	private Double expdSelfMedical;//
	private Double expdSelfPersonal;//
	private Double expdSelfDepntcontr;//
	private Double expdSelfTaxes;//
	private Double expdSelfEntertain;//
	private Double expdSelfFestiv;//
	private Double expdSelfVacations;//
	private Double expdSelfCharity;//
	private Double expdSelfProploan;//
	private Double expdSelfVehiloan;//
	private Double expdSelfInsurance;//
	private Double expdSelfOthers;//
	private Double expdSpsRent;//
	private Double expdSpsUtil;//
	private Double expdSpsGrocery;//
	private Double expdSpsEatingout;//
	private Double expdSpsClothing;//
	private Double expdSpsTransport;//
	private Double expdSpsMedical;//
	private Double expdSpsPersonal;//
	private Double expdSpsDepntcontr;//
	private Double expdSpsTaxes;//
	private Double expdSpsEntertain;//
	private Double expdSpsFestiv;//
	private Double expdSpsVacations;//
	private Double expdSpsCharity;//
	private Double expdSpsProploan;//
	private Double expdSpsVehiloan;//
	private Double expdSpsInsurance;//
	private Double expdSpsOthers;//
	private Double expdFamilyRent;//
	private Double expdFamilyUtil;//
	private Double expdFamilyGrocery;//
	private Double expdFamilyEatingout;//
	private Double expdFamilyClothing;//
	private Double expdFamilyTransport;//
	private Double expdFamilyMedical;//
	private Double expdFamilyPersonal;//
	private Double expdFamilyHousehold;//
	private Double expdFamilyDomestic;//
	private Double expdFamilyEnhance;//
	private Double expdFamilyTaxes;//
	private Double expdFamilyEntertain;//
	private Double expdFamilyFestiv;//
	private Double expdFamilyVacations;//
	private Double expdFamilyCharity;//
	private Double expdFamilyProploan;//
	private Double expdFamilyVehiloan;
	private Double expdFamilyInsurance;//
	private Double expdFamilyOthers;//
	private Double expdSelfLoanrepay;//
	private Double expdSpsLoanrepay;//
	private Double expdFamilyLoanrepay;//
	private Double expdSelfGi;//
	private Double expdSpsGi;//
	private Double expdFamilyGi;//
	private Double expdSelfTotalannl;//
	private Double expdSpsTotalannl;//
	private Double expdFamilyTotalannl;//
	private String expdRemarks;
	private String expdCreatedBy;//
	private Date expdCreatedDate;//
	private String expdModifiedBy;
	private Date expdModifiedDate;

	public FnaExpenditureDets() {
	}

	public FnaExpenditureDets(String expdId) {
		this.expdId = expdId;
	}

	public FnaExpenditureDets(String expdId,
			FnaSelfspouseDets fnaSelfspouseDets, Double expdSelfRent,
			Double expdSelfUtil, Double expdSelfGrocery,
			Double expdSelfEatingout, Double expdSelfClothing,
			Double expdSelfTransport, Double expdSelfMedical,
			Double expdSelfPersonal, Double expdSelfDepntcontr,
			Double expdSelfTaxes, Double expdSelfEntertain,
			Double expdSelfFestiv, Double expdSelfVacations,
			Double expdSelfCharity, Double expdSelfProploan,
			Double expdSelfVehiloan, Double expdSelfInsurance,
			Double expdSelfOthers, Double expdSpsRent, Double expdSpsUtil,
			Double expdSpsGrocery, Double expdSpsEatingout,
			Double expdSpsClothing, Double expdSpsTransport,
			Double expdSpsMedical, Double expdSpsPersonal,
			Double expdSpsDepntcontr, Double expdSpsTaxes,
			Double expdSpsEntertain, Double expdSpsFestiv,
			Double expdSpsVacations, Double expdSpsCharity,
			Double expdSpsProploan, Double expdSpsVehiloan,
			Double expdSpsInsurance, Double expdSpsOthers,
			Double expdFamilyRent, Double expdFamilyUtil,
			Double expdFamilyGrocery, Double expdFamilyEatingout,
			Double expdFamilyClothing, Double expdFamilyTransport,
			Double expdFamilyMedical, Double expdFamilyPersonal,
			Double expdFamilyHousehold, Double expdFamilyDomestic,
			Double expdFamilyEnhance, Double expdFamilyTaxes,
			Double expdFamilyEntertain, Double expdFamilyFestiv,
			Double expdFamilyVacations, Double expdFamilyCharity,
			Double expdFamilyProploan, Double expdFamilyVehiloan,
			Double expdFamilyInsurance, Double expdFamilyOthers,
			Double expdSelfLoanrepay, Double expdSpsLoanrepay,
			Double expdFamilyLoanrepay, Double expdSelfGi, Double expdSpsGi,
			Double expdFamilyGi, Double expdSelfTotalannl,
			Double expdSpsTotalannl, Double expdFamilyTotalannl,
			String expdRemarks, String expdCreatedBy, Date expdCreatedDate,
			String expdModifiedBy, Date expdModifiedDate) {
		this.expdId = expdId;
		this.fnaSelfspouseDets = fnaSelfspouseDets;
		this.expdSelfRent = expdSelfRent;
		this.expdSelfUtil = expdSelfUtil;
		this.expdSelfGrocery = expdSelfGrocery;
		this.expdSelfEatingout = expdSelfEatingout;
		this.expdSelfClothing = expdSelfClothing;
		this.expdSelfTransport = expdSelfTransport;
		this.expdSelfMedical = expdSelfMedical;
		this.expdSelfPersonal = expdSelfPersonal;
		this.expdSelfDepntcontr = expdSelfDepntcontr;
		this.expdSelfTaxes = expdSelfTaxes;
		this.expdSelfEntertain = expdSelfEntertain;
		this.expdSelfFestiv = expdSelfFestiv;
		this.expdSelfVacations = expdSelfVacations;
		this.expdSelfCharity = expdSelfCharity;
		this.expdSelfProploan = expdSelfProploan;
		this.expdSelfVehiloan = expdSelfVehiloan;
		this.expdSelfInsurance = expdSelfInsurance;
		this.expdSelfOthers = expdSelfOthers;
		this.expdSpsRent = expdSpsRent;
		this.expdSpsUtil = expdSpsUtil;
		this.expdSpsGrocery = expdSpsGrocery;
		this.expdSpsEatingout = expdSpsEatingout;
		this.expdSpsClothing = expdSpsClothing;
		this.expdSpsTransport = expdSpsTransport;
		this.expdSpsMedical = expdSpsMedical;
		this.expdSpsPersonal = expdSpsPersonal;
		this.expdSpsDepntcontr = expdSpsDepntcontr;
		this.expdSpsTaxes = expdSpsTaxes;
		this.expdSpsEntertain = expdSpsEntertain;
		this.expdSpsFestiv = expdSpsFestiv;
		this.expdSpsVacations = expdSpsVacations;
		this.expdSpsCharity = expdSpsCharity;
		this.expdSpsProploan = expdSpsProploan;
		this.expdSpsVehiloan = expdSpsVehiloan;
		this.expdSpsInsurance = expdSpsInsurance;
		this.expdSpsOthers = expdSpsOthers;
		this.expdFamilyRent = expdFamilyRent;
		this.expdFamilyUtil = expdFamilyUtil;
		this.expdFamilyGrocery = expdFamilyGrocery;
		this.expdFamilyEatingout = expdFamilyEatingout;
		this.expdFamilyClothing = expdFamilyClothing;
		this.expdFamilyTransport = expdFamilyTransport;
		this.expdFamilyMedical = expdFamilyMedical;
		this.expdFamilyPersonal = expdFamilyPersonal;
		this.expdFamilyHousehold = expdFamilyHousehold;
		this.expdFamilyDomestic = expdFamilyDomestic;
		this.expdFamilyEnhance = expdFamilyEnhance;
		this.expdFamilyTaxes = expdFamilyTaxes;
		this.expdFamilyEntertain = expdFamilyEntertain;
		this.expdFamilyFestiv = expdFamilyFestiv;
		this.expdFamilyVacations = expdFamilyVacations;
		this.expdFamilyCharity = expdFamilyCharity;
		this.expdFamilyProploan = expdFamilyProploan;
		this.expdFamilyVehiloan = expdFamilyVehiloan;
		this.expdFamilyInsurance = expdFamilyInsurance;
		this.expdFamilyOthers = expdFamilyOthers;
		this.expdSelfLoanrepay = expdSelfLoanrepay;
		this.expdSpsLoanrepay = expdSpsLoanrepay;
		this.expdFamilyLoanrepay = expdFamilyLoanrepay;
		this.expdSelfGi = expdSelfGi;
		this.expdSpsGi = expdSpsGi;
		this.expdFamilyGi = expdFamilyGi;
		this.expdSelfTotalannl = expdSelfTotalannl;
		this.expdSpsTotalannl = expdSpsTotalannl;
		this.expdFamilyTotalannl = expdFamilyTotalannl;
		this.expdRemarks = expdRemarks;
		this.expdCreatedBy = expdCreatedBy;
		this.expdCreatedDate = expdCreatedDate;
		this.expdModifiedBy = expdModifiedBy;
		this.expdModifiedDate = expdModifiedDate;
	}

	public String getExpdId() {
		return this.expdId;
	}

	public void setExpdId(String expdId) {
		this.expdId = expdId;
	}

	public FnaSelfspouseDets getFnaSelfspouseDets() {
		return this.fnaSelfspouseDets;
	}

	public void setFnaSelfspouseDets(FnaSelfspouseDets fnaSelfspouseDets) {
		this.fnaSelfspouseDets = fnaSelfspouseDets;
	}

	public Double getExpdSelfRent() {
		return this.expdSelfRent;
	}

	public void setExpdSelfRent(Double expdSelfRent) {
		this.expdSelfRent = expdSelfRent;
	}

	public Double getExpdSelfUtil() {
		return this.expdSelfUtil;
	}

	public void setExpdSelfUtil(Double expdSelfUtil) {
		this.expdSelfUtil = expdSelfUtil;
	}

	public Double getExpdSelfGrocery() {
		return this.expdSelfGrocery;
	}

	public void setExpdSelfGrocery(Double expdSelfGrocery) {
		this.expdSelfGrocery = expdSelfGrocery;
	}

	public Double getExpdSelfEatingout() {
		return this.expdSelfEatingout;
	}

	public void setExpdSelfEatingout(Double expdSelfEatingout) {
		this.expdSelfEatingout = expdSelfEatingout;
	}

	public Double getExpdSelfClothing() {
		return this.expdSelfClothing;
	}

	public void setExpdSelfClothing(Double expdSelfClothing) {
		this.expdSelfClothing = expdSelfClothing;
	}

	public Double getExpdSelfTransport() {
		return this.expdSelfTransport;
	}

	public void setExpdSelfTransport(Double expdSelfTransport) {
		this.expdSelfTransport = expdSelfTransport;
	}

	public Double getExpdSelfMedical() {
		return this.expdSelfMedical;
	}

	public void setExpdSelfMedical(Double expdSelfMedical) {
		this.expdSelfMedical = expdSelfMedical;
	}

	public Double getExpdSelfPersonal() {
		return this.expdSelfPersonal;
	}

	public void setExpdSelfPersonal(Double expdSelfPersonal) {
		this.expdSelfPersonal = expdSelfPersonal;
	}

	public Double getExpdSelfDepntcontr() {
		return this.expdSelfDepntcontr;
	}

	public void setExpdSelfDepntcontr(Double expdSelfDepntcontr) {
		this.expdSelfDepntcontr = expdSelfDepntcontr;
	}

	public Double getExpdSelfTaxes() {
		return this.expdSelfTaxes;
	}

	public void setExpdSelfTaxes(Double expdSelfTaxes) {
		this.expdSelfTaxes = expdSelfTaxes;
	}

	public Double getExpdSelfEntertain() {
		return this.expdSelfEntertain;
	}

	public void setExpdSelfEntertain(Double expdSelfEntertain) {
		this.expdSelfEntertain = expdSelfEntertain;
	}

	public Double getExpdSelfFestiv() {
		return this.expdSelfFestiv;
	}

	public void setExpdSelfFestiv(Double expdSelfFestiv) {
		this.expdSelfFestiv = expdSelfFestiv;
	}

	public Double getExpdSelfVacations() {
		return this.expdSelfVacations;
	}

	public void setExpdSelfVacations(Double expdSelfVacations) {
		this.expdSelfVacations = expdSelfVacations;
	}

	public Double getExpdSelfCharity() {
		return this.expdSelfCharity;
	}

	public void setExpdSelfCharity(Double expdSelfCharity) {
		this.expdSelfCharity = expdSelfCharity;
	}

	public Double getExpdSelfProploan() {
		return this.expdSelfProploan;
	}

	public void setExpdSelfProploan(Double expdSelfProploan) {
		this.expdSelfProploan = expdSelfProploan;
	}

	public Double getExpdSelfVehiloan() {
		return this.expdSelfVehiloan;
	}

	public void setExpdSelfVehiloan(Double expdSelfVehiloan) {
		this.expdSelfVehiloan = expdSelfVehiloan;
	}

	public Double getExpdSelfInsurance() {
		return this.expdSelfInsurance;
	}

	public void setExpdSelfInsurance(Double expdSelfInsurance) {
		this.expdSelfInsurance = expdSelfInsurance;
	}

	public Double getExpdSelfOthers() {
		return this.expdSelfOthers;
	}

	public void setExpdSelfOthers(Double expdSelfOthers) {
		this.expdSelfOthers = expdSelfOthers;
	}

	public Double getExpdSpsRent() {
		return this.expdSpsRent;
	}

	public void setExpdSpsRent(Double expdSpsRent) {
		this.expdSpsRent = expdSpsRent;
	}

	public Double getExpdSpsUtil() {
		return this.expdSpsUtil;
	}

	public void setExpdSpsUtil(Double expdSpsUtil) {
		this.expdSpsUtil = expdSpsUtil;
	}

	public Double getExpdSpsGrocery() {
		return this.expdSpsGrocery;
	}

	public void setExpdSpsGrocery(Double expdSpsGrocery) {
		this.expdSpsGrocery = expdSpsGrocery;
	}

	public Double getExpdSpsEatingout() {
		return this.expdSpsEatingout;
	}

	public void setExpdSpsEatingout(Double expdSpsEatingout) {
		this.expdSpsEatingout = expdSpsEatingout;
	}

	public Double getExpdSpsClothing() {
		return this.expdSpsClothing;
	}

	public void setExpdSpsClothing(Double expdSpsClothing) {
		this.expdSpsClothing = expdSpsClothing;
	}

	public Double getExpdSpsTransport() {
		return this.expdSpsTransport;
	}

	public void setExpdSpsTransport(Double expdSpsTransport) {
		this.expdSpsTransport = expdSpsTransport;
	}

	public Double getExpdSpsMedical() {
		return this.expdSpsMedical;
	}

	public void setExpdSpsMedical(Double expdSpsMedical) {
		this.expdSpsMedical = expdSpsMedical;
	}

	public Double getExpdSpsPersonal() {
		return this.expdSpsPersonal;
	}

	public void setExpdSpsPersonal(Double expdSpsPersonal) {
		this.expdSpsPersonal = expdSpsPersonal;
	}

	public Double getExpdSpsDepntcontr() {
		return this.expdSpsDepntcontr;
	}

	public void setExpdSpsDepntcontr(Double expdSpsDepntcontr) {
		this.expdSpsDepntcontr = expdSpsDepntcontr;
	}

	public Double getExpdSpsTaxes() {
		return this.expdSpsTaxes;
	}

	public void setExpdSpsTaxes(Double expdSpsTaxes) {
		this.expdSpsTaxes = expdSpsTaxes;
	}

	public Double getExpdSpsEntertain() {
		return this.expdSpsEntertain;
	}

	public void setExpdSpsEntertain(Double expdSpsEntertain) {
		this.expdSpsEntertain = expdSpsEntertain;
	}

	public Double getExpdSpsFestiv() {
		return this.expdSpsFestiv;
	}

	public void setExpdSpsFestiv(Double expdSpsFestiv) {
		this.expdSpsFestiv = expdSpsFestiv;
	}

	public Double getExpdSpsVacations() {
		return this.expdSpsVacations;
	}

	public void setExpdSpsVacations(Double expdSpsVacations) {
		this.expdSpsVacations = expdSpsVacations;
	}

	public Double getExpdSpsCharity() {
		return this.expdSpsCharity;
	}

	public void setExpdSpsCharity(Double expdSpsCharity) {
		this.expdSpsCharity = expdSpsCharity;
	}

	public Double getExpdSpsProploan() {
		return this.expdSpsProploan;
	}

	public void setExpdSpsProploan(Double expdSpsProploan) {
		this.expdSpsProploan = expdSpsProploan;
	}

	public Double getExpdSpsVehiloan() {
		return this.expdSpsVehiloan;
	}

	public void setExpdSpsVehiloan(Double expdSpsVehiloan) {
		this.expdSpsVehiloan = expdSpsVehiloan;
	}

	public Double getExpdSpsInsurance() {
		return this.expdSpsInsurance;
	}

	public void setExpdSpsInsurance(Double expdSpsInsurance) {
		this.expdSpsInsurance = expdSpsInsurance;
	}

	public Double getExpdSpsOthers() {
		return this.expdSpsOthers;
	}

	public void setExpdSpsOthers(Double expdSpsOthers) {
		this.expdSpsOthers = expdSpsOthers;
	}

	public Double getExpdFamilyRent() {
		return this.expdFamilyRent;
	}

	public void setExpdFamilyRent(Double expdFamilyRent) {
		this.expdFamilyRent = expdFamilyRent;
	}

	public Double getExpdFamilyUtil() {
		return this.expdFamilyUtil;
	}

	public void setExpdFamilyUtil(Double expdFamilyUtil) {
		this.expdFamilyUtil = expdFamilyUtil;
	}

	public Double getExpdFamilyGrocery() {
		return this.expdFamilyGrocery;
	}

	public void setExpdFamilyGrocery(Double expdFamilyGrocery) {
		this.expdFamilyGrocery = expdFamilyGrocery;
	}

	public Double getExpdFamilyEatingout() {
		return this.expdFamilyEatingout;
	}

	public void setExpdFamilyEatingout(Double expdFamilyEatingout) {
		this.expdFamilyEatingout = expdFamilyEatingout;
	}

	public Double getExpdFamilyClothing() {
		return this.expdFamilyClothing;
	}

	public void setExpdFamilyClothing(Double expdFamilyClothing) {
		this.expdFamilyClothing = expdFamilyClothing;
	}

	public Double getExpdFamilyTransport() {
		return this.expdFamilyTransport;
	}

	public void setExpdFamilyTransport(Double expdFamilyTransport) {
		this.expdFamilyTransport = expdFamilyTransport;
	}

	public Double getExpdFamilyMedical() {
		return this.expdFamilyMedical;
	}

	public void setExpdFamilyMedical(Double expdFamilyMedical) {
		this.expdFamilyMedical = expdFamilyMedical;
	}

	public Double getExpdFamilyPersonal() {
		return this.expdFamilyPersonal;
	}

	public void setExpdFamilyPersonal(Double expdFamilyPersonal) {
		this.expdFamilyPersonal = expdFamilyPersonal;
	}

	public Double getExpdFamilyHousehold() {
		return this.expdFamilyHousehold;
	}

	public void setExpdFamilyHousehold(Double expdFamilyHousehold) {
		this.expdFamilyHousehold = expdFamilyHousehold;
	}

	public Double getExpdFamilyDomestic() {
		return this.expdFamilyDomestic;
	}

	public void setExpdFamilyDomestic(Double expdFamilyDomestic) {
		this.expdFamilyDomestic = expdFamilyDomestic;
	}

	public Double getExpdFamilyEnhance() {
		return this.expdFamilyEnhance;
	}

	public void setExpdFamilyEnhance(Double expdFamilyEnhance) {
		this.expdFamilyEnhance = expdFamilyEnhance;
	}

	public Double getExpdFamilyTaxes() {
		return this.expdFamilyTaxes;
	}

	public void setExpdFamilyTaxes(Double expdFamilyTaxes) {
		this.expdFamilyTaxes = expdFamilyTaxes;
	}

	public Double getExpdFamilyEntertain() {
		return this.expdFamilyEntertain;
	}

	public void setExpdFamilyEntertain(Double expdFamilyEntertain) {
		this.expdFamilyEntertain = expdFamilyEntertain;
	}

	public Double getExpdFamilyFestiv() {
		return this.expdFamilyFestiv;
	}

	public void setExpdFamilyFestiv(Double expdFamilyFestiv) {
		this.expdFamilyFestiv = expdFamilyFestiv;
	}

	public Double getExpdFamilyVacations() {
		return this.expdFamilyVacations;
	}

	public void setExpdFamilyVacations(Double expdFamilyVacations) {
		this.expdFamilyVacations = expdFamilyVacations;
	}

	public Double getExpdFamilyCharity() {
		return this.expdFamilyCharity;
	}

	public void setExpdFamilyCharity(Double expdFamilyCharity) {
		this.expdFamilyCharity = expdFamilyCharity;
	}

	public Double getExpdFamilyProploan() {
		return this.expdFamilyProploan;
	}

	public void setExpdFamilyProploan(Double expdFamilyProploan) {
		this.expdFamilyProploan = expdFamilyProploan;
	}

	public Double getExpdFamilyVehiloan() {
		return this.expdFamilyVehiloan;
	}

	public void setExpdFamilyVehiloan(Double expdFamilyVehiloan) {
		this.expdFamilyVehiloan = expdFamilyVehiloan;
	}

	public Double getExpdFamilyInsurance() {
		return this.expdFamilyInsurance;
	}

	public void setExpdFamilyInsurance(Double expdFamilyInsurance) {
		this.expdFamilyInsurance = expdFamilyInsurance;
	}

	public Double getExpdFamilyOthers() {
		return this.expdFamilyOthers;
	}

	public void setExpdFamilyOthers(Double expdFamilyOthers) {
		this.expdFamilyOthers = expdFamilyOthers;
	}

	public Double getExpdSelfLoanrepay() {
		return this.expdSelfLoanrepay;
	}

	public void setExpdSelfLoanrepay(Double expdSelfLoanrepay) {
		this.expdSelfLoanrepay = expdSelfLoanrepay;
	}

	public Double getExpdSpsLoanrepay() {
		return this.expdSpsLoanrepay;
	}

	public void setExpdSpsLoanrepay(Double expdSpsLoanrepay) {
		this.expdSpsLoanrepay = expdSpsLoanrepay;
	}

	public Double getExpdFamilyLoanrepay() {
		return this.expdFamilyLoanrepay;
	}

	public void setExpdFamilyLoanrepay(Double expdFamilyLoanrepay) {
		this.expdFamilyLoanrepay = expdFamilyLoanrepay;
	}

	public Double getExpdSelfGi() {
		return this.expdSelfGi;
	}

	public void setExpdSelfGi(Double expdSelfGi) {
		this.expdSelfGi = expdSelfGi;
	}

	public Double getExpdSpsGi() {
		return this.expdSpsGi;
	}

	public void setExpdSpsGi(Double expdSpsGi) {
		this.expdSpsGi = expdSpsGi;
	}

	public Double getExpdFamilyGi() {
		return this.expdFamilyGi;
	}

	public void setExpdFamilyGi(Double expdFamilyGi) {
		this.expdFamilyGi = expdFamilyGi;
	}

	public Double getExpdSelfTotalannl() {
		return this.expdSelfTotalannl;
	}

	public void setExpdSelfTotalannl(Double expdSelfTotalannl) {
		this.expdSelfTotalannl = expdSelfTotalannl;
	}

	public Double getExpdSpsTotalannl() {
		return this.expdSpsTotalannl;
	}

	public void setExpdSpsTotalannl(Double expdSpsTotalannl) {
		this.expdSpsTotalannl = expdSpsTotalannl;
	}

	public Double getExpdFamilyTotalannl() {
		return this.expdFamilyTotalannl;
	}

	public void setExpdFamilyTotalannl(Double expdFamilyTotalannl) {
		this.expdFamilyTotalannl = expdFamilyTotalannl;
	}

	public String getExpdRemarks() {
		return this.expdRemarks;
	}

	public void setExpdRemarks(String expdRemarks) {
		this.expdRemarks = expdRemarks;
	}

	public String getExpdCreatedBy() {
		return this.expdCreatedBy;
	}

	public void setExpdCreatedBy(String expdCreatedBy) {
		this.expdCreatedBy = expdCreatedBy;
	}

	public Date getExpdCreatedDate() {
		return this.expdCreatedDate;
	}

	public void setExpdCreatedDate(Date expdCreatedDate) {
		this.expdCreatedDate = expdCreatedDate;
	}

	public String getExpdModifiedBy() {
		return this.expdModifiedBy;
	}

	public void setExpdModifiedBy(String expdModifiedBy) {
		this.expdModifiedBy = expdModifiedBy;
	}

	public Date getExpdModifiedDate() {
		return this.expdModifiedDate;
	}

	public void setExpdModifiedDate(Date expdModifiedDate) {
		this.expdModifiedDate = expdModifiedDate;
	}

}
