package com.fipa.dto;

// Generated May 17, 2018 11:20:36 AM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * FnaEstatePlan generated by hbm2java
 */
public class FnaEstatePlan implements java.io.Serializable {

	private String estId;
	private FnaSelfspouseDets fnaSelfspouseDets;
	private String estPlanDesc;
	private String estSelfPlanFlg;
	private String estSpsPlanFlg;
	private String estPlanRemarks;
	private String estCrtdBy;
	private Date estCrtdDate;
	private String estModBy;
	private Date estModDate;

	public FnaEstatePlan() {
	}

	public FnaEstatePlan(String estId, String estPlanDesc, String estCrtdBy,
			Date estCrtdDate) {
		this.estId = estId;
		this.estPlanDesc = estPlanDesc;
		this.estCrtdBy = estCrtdBy;
		this.estCrtdDate = estCrtdDate;
	}

	public FnaEstatePlan(String estId, FnaSelfspouseDets fnaSelfspouseDets,
			String estPlanDesc, String estSelfPlanFlg, String estSpsPlanFlg,
			String estPlanRemarks, String estCrtdBy, Date estCrtdDate,
			String estModBy, Date estModDate) {
		this.estId = estId;
		this.fnaSelfspouseDets = fnaSelfspouseDets;
		this.estPlanDesc = estPlanDesc;
		this.estSelfPlanFlg = estSelfPlanFlg;
		this.estSpsPlanFlg = estSpsPlanFlg;
		this.estPlanRemarks = estPlanRemarks;
		this.estCrtdBy = estCrtdBy;
		this.estCrtdDate = estCrtdDate;
		this.estModBy = estModBy;
		this.estModDate = estModDate;
	}

	public String getEstId() {
		return this.estId;
	}

	public void setEstId(String estId) {
		this.estId = estId;
	}

	public FnaSelfspouseDets getFnaSelfspouseDets() {
		return this.fnaSelfspouseDets;
	}

	public void setFnaSelfspouseDets(FnaSelfspouseDets fnaSelfspouseDets) {
		this.fnaSelfspouseDets = fnaSelfspouseDets;
	}

	public String getEstPlanDesc() {
		return this.estPlanDesc;
	}

	public void setEstPlanDesc(String estPlanDesc) {
		this.estPlanDesc = estPlanDesc;
	}

	public String getEstSelfPlanFlg() {
		return this.estSelfPlanFlg;
	}

	public void setEstSelfPlanFlg(String estSelfPlanFlg) {
		this.estSelfPlanFlg = estSelfPlanFlg;
	}

	public String getEstSpsPlanFlg() {
		return this.estSpsPlanFlg;
	}

	public void setEstSpsPlanFlg(String estSpsPlanFlg) {
		this.estSpsPlanFlg = estSpsPlanFlg;
	}

	public String getEstPlanRemarks() {
		return this.estPlanRemarks;
	}

	public void setEstPlanRemarks(String estPlanRemarks) {
		this.estPlanRemarks = estPlanRemarks;
	}

	public String getEstCrtdBy() {
		return this.estCrtdBy;
	}

	public void setEstCrtdBy(String estCrtdBy) {
		this.estCrtdBy = estCrtdBy;
	}

	public Date getEstCrtdDate() {
		return this.estCrtdDate;
	}

	public void setEstCrtdDate(Date estCrtdDate) {
		this.estCrtdDate = estCrtdDate;
	}

	public String getEstModBy() {
		return this.estModBy;
	}

	public void setEstModBy(String estModBy) {
		this.estModBy = estModBy;
	}

	public Date getEstModDate() {
		return this.estModDate;
	}

	public void setEstModDate(Date estModDate) {
		this.estModDate = estModDate;
	}

}
