package com.fipa.dto;

// Generated May 17, 2018 11:20:36 AM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * FnaFingoalsconcern generated by hbm2java
 */
public class FnaFingoalsconcern implements java.io.Serializable {

	private String fnaGoalId;
	private FnaSelfspouseDets fnaSelfspouseDets;
	private String fgType;
	private String finGoal;
	private String fgPriority;
	private String fgCreatedBy;
	private Date fgCreatedDate;
	private String fgModifiedBy;
	private Date fgModifiedDate;

	public FnaFingoalsconcern() {
	}

	public FnaFingoalsconcern(String fnaGoalId, String finGoal) {
		this.fnaGoalId = fnaGoalId;
		this.finGoal = finGoal;
	}

	public FnaFingoalsconcern(String fnaGoalId,
			FnaSelfspouseDets fnaSelfspouseDets, String fgType, String finGoal,
			String fgPriority, String fgCreatedBy, Date fgCreatedDate,
			String fgModifiedBy, Date fgModifiedDate) {
		this.fnaGoalId = fnaGoalId;
		this.fnaSelfspouseDets = fnaSelfspouseDets;
		this.fgType = fgType;
		this.finGoal = finGoal;
		this.fgPriority = fgPriority;
		this.fgCreatedBy = fgCreatedBy;
		this.fgCreatedDate = fgCreatedDate;
		this.fgModifiedBy = fgModifiedBy;
		this.fgModifiedDate = fgModifiedDate;
	}

	public String getFnaGoalId() {
		return this.fnaGoalId;
	}

	public void setFnaGoalId(String fnaGoalId) {
		this.fnaGoalId = fnaGoalId;
	}

	public FnaSelfspouseDets getFnaSelfspouseDets() {
		return this.fnaSelfspouseDets;
	}

	public void setFnaSelfspouseDets(FnaSelfspouseDets fnaSelfspouseDets) {
		this.fnaSelfspouseDets = fnaSelfspouseDets;
	}

	public String getFgType() {
		return this.fgType;
	}

	public void setFgType(String fgType) {
		this.fgType = fgType;
	}

	public String getFinGoal() {
		return this.finGoal;
	}

	public void setFinGoal(String finGoal) {
		this.finGoal = finGoal;
	}

	public String getFgPriority() {
		return this.fgPriority;
	}

	public void setFgPriority(String fgPriority) {
		this.fgPriority = fgPriority;
	}

	public String getFgCreatedBy() {
		return this.fgCreatedBy;
	}

	public void setFgCreatedBy(String fgCreatedBy) {
		this.fgCreatedBy = fgCreatedBy;
	}

	public Date getFgCreatedDate() {
		return this.fgCreatedDate;
	}

	public void setFgCreatedDate(Date fgCreatedDate) {
		this.fgCreatedDate = fgCreatedDate;
	}

	public String getFgModifiedBy() {
		return this.fgModifiedBy;
	}

	public void setFgModifiedBy(String fgModifiedBy) {
		this.fgModifiedBy = fgModifiedBy;
	}

	public Date getFgModifiedDate() {
		return this.fgModifiedDate;
	}

	public void setFgModifiedDate(Date fgModifiedDate) {
		this.fgModifiedDate = fgModifiedDate;
	}

}
