package com.fipa.dto;

// Generated May 17, 2018 11:20:36 AM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * FnaHealthinsInfo generated by hbm2java
 */
public class FnaHealthinsInfo implements java.io.Serializable {

	private String hiId;
	private FnaSelfspouseDets fnaSelfspouseDets;
	private String hiPolicytype;
	private String hiInsured;
	private String hiBenftype;
	private Double hiAmount;
	private Date hiExpiry;
	private Double hiAnnprem;
	private String hiRemarks;
	private String hiCreatedBy;
	private Date hiCreatedDate;
	private String hiModifiedBy;
	private Date hiModifiedDate;

	public FnaHealthinsInfo() {
	}

	public FnaHealthinsInfo(String hiId) {
		this.hiId = hiId;
	}

	public FnaHealthinsInfo(String hiId, FnaSelfspouseDets fnaSelfspouseDets,
			String hiPolicytype, String hiInsured, String hiBenftype,
			Double hiAmount, Date hiExpiry, Double hiAnnprem, String hiRemarks,
			String hiCreatedBy, Date hiCreatedDate, String hiModifiedBy,
			Date hiModifiedDate) {
		this.hiId = hiId;
		this.fnaSelfspouseDets = fnaSelfspouseDets;
		this.hiPolicytype = hiPolicytype;
		this.hiInsured = hiInsured;
		this.hiBenftype = hiBenftype;
		this.hiAmount = hiAmount;
		this.hiExpiry = hiExpiry;
		this.hiAnnprem = hiAnnprem;
		this.hiRemarks = hiRemarks;
		this.hiCreatedBy = hiCreatedBy;
		this.hiCreatedDate = hiCreatedDate;
		this.hiModifiedBy = hiModifiedBy;
		this.hiModifiedDate = hiModifiedDate;
	}

	public String getHiId() {
		return this.hiId;
	}

	public void setHiId(String hiId) {
		this.hiId = hiId;
	}

	public FnaSelfspouseDets getFnaSelfspouseDets() {
		return this.fnaSelfspouseDets;
	}

	public void setFnaSelfspouseDets(FnaSelfspouseDets fnaSelfspouseDets) {
		this.fnaSelfspouseDets = fnaSelfspouseDets;
	}

	public String getHiPolicytype() {
		return this.hiPolicytype;
	}

	public void setHiPolicytype(String hiPolicytype) {
		this.hiPolicytype = hiPolicytype;
	}

	public String getHiInsured() {
		return this.hiInsured;
	}

	public void setHiInsured(String hiInsured) {
		this.hiInsured = hiInsured;
	}

	public String getHiBenftype() {
		return this.hiBenftype;
	}

	public void setHiBenftype(String hiBenftype) {
		this.hiBenftype = hiBenftype;
	}

	public Double getHiAmount() {
		return this.hiAmount;
	}

	public void setHiAmount(Double hiAmount) {
		this.hiAmount = hiAmount;
	}

	public Date getHiExpiry() {
		return this.hiExpiry;
	}

	public void setHiExpiry(Date hiExpiry) {
		this.hiExpiry = hiExpiry;
	}

	public Double getHiAnnprem() {
		return this.hiAnnprem;
	}

	public void setHiAnnprem(Double hiAnnprem) {
		this.hiAnnprem = hiAnnprem;
	}

	public String getHiRemarks() {
		return this.hiRemarks;
	}

	public void setHiRemarks(String hiRemarks) {
		this.hiRemarks = hiRemarks;
	}

	public String getHiCreatedBy() {
		return this.hiCreatedBy;
	}

	public void setHiCreatedBy(String hiCreatedBy) {
		this.hiCreatedBy = hiCreatedBy;
	}

	public Date getHiCreatedDate() {
		return this.hiCreatedDate;
	}

	public void setHiCreatedDate(Date hiCreatedDate) {
		this.hiCreatedDate = hiCreatedDate;
	}

	public String getHiModifiedBy() {
		return this.hiModifiedBy;
	}

	public void setHiModifiedBy(String hiModifiedBy) {
		this.hiModifiedBy = hiModifiedBy;
	}

	public Date getHiModifiedDate() {
		return this.hiModifiedDate;
	}

	public void setHiModifiedDate(Date hiModifiedDate) {
		this.hiModifiedDate = hiModifiedDate;
	}

}
