package com.fipa.dto;

// Generated May 17, 2018 11:20:36 AM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * FnaInvsetmentSummary generated by hbm2java
 */
public class FnaInvsetmentSummary implements java.io.Serializable {

	private String invstId;//
	private FnaSelfspouseDets fnaSelfspouseDets;
	private Double invSelfBondCurr;//
	private Double invSelfBondReg;//
	private Double invSpsBondCurr;//
	private Double invSpsBondReg;//
	private Double invFamBondCurr;//
	private Double invFamBondReg;//
	private Double invSelfIlputCurr;//
	private Double invSelfIlputReg;//
	private Double invSpsIlputCurr;//
	private Double invSpsIlputReg;//
	private Double invFamIlputCurr;//
	private Double invFamIlputReg;//
	private Double invSelfShareCurr;//
	private Double invSelfShareReg;//
	private Double invSpsShareCurr;//
	private Double invSpsShareReg;//
	private Double invFamShareCurr;//
	private Double invFamShareReg;//
	private Double invSelfDivdCurr;
	private Double invSelfDivdReg; 
	private Double invSpsDivdCurr;
	private Double invSpsDivdReg;
	private Double invFamDivdCurr; 
	private Double invFamDivdReg;
	private Double invSelfOthinvCurr;//
	private Double invSelfOthinvReg;//
	private Double invSpsOthinvCurr;//
	private Double invSpsOthinvReg;//
	private Double invFamOthinvCurr;//
	private Double invFamOthinvReg;
	private String invCreatedBy;
	private Date invCreatedDate;
	private String invModifiedBy;
	private Date invModifiedDate;
	
	
	
	public FnaInvsetmentSummary() {
	}

	public FnaInvsetmentSummary(String invstId) {
		this.invstId = invstId;
	}

	public FnaInvsetmentSummary(String invstId, FnaSelfspouseDets fnaSelfspouseDets, Double invSelfBondCurr,
			Double invSelfBondReg, Double invSpsBondCurr, Double invSpsBondReg, Double invFamBondCurr,
			Double invFamBondReg, Double invSelfIlputCurr, Double invSelfIlputReg, Double invSpsIlputCurr,
			Double invSpsIlputReg, Double invFamIlputCurr, Double invFamIlputReg, Double invSelfShareCurr,
			Double invSelfShareReg, Double invSpsShareCurr, Double invSpsShareReg, Double invFamShareCurr,
			Double invFamShareReg, Double invSelfDivdCurr, Double invSelfDivdReg, Double invSpsDivdCurr,
			Double invSpsDivdReg, Double invFamDivdCurr, Double invFamDivdReg, Double invSelfOthinvCurr,
			Double invSelfOthinvReg, Double invSpsOthinvCurr, Double invSpsOthinvReg, Double invFamOthinvCurr,
			Double invFamOthinvReg, String invCreatedBy, Date invCreatedDate, String invModifiedBy,
			Date invModifiedDate) {
		 
		this.invstId = invstId;
		this.fnaSelfspouseDets = fnaSelfspouseDets;
		this.invSelfBondCurr = invSelfBondCurr;
		this.invSelfBondReg = invSelfBondReg;
		this.invSpsBondCurr = invSpsBondCurr;
		this.invSpsBondReg = invSpsBondReg;
		this.invFamBondCurr = invFamBondCurr;
		this.invFamBondReg = invFamBondReg;
		this.invSelfIlputCurr = invSelfIlputCurr;
		this.invSelfIlputReg = invSelfIlputReg;
		this.invSpsIlputCurr = invSpsIlputCurr;
		this.invSpsIlputReg = invSpsIlputReg;
		this.invFamIlputCurr = invFamIlputCurr;
		this.invFamIlputReg = invFamIlputReg;
		this.invSelfShareCurr = invSelfShareCurr;
		this.invSelfShareReg = invSelfShareReg;
		this.invSpsShareCurr = invSpsShareCurr;
		this.invSpsShareReg = invSpsShareReg;
		this.invFamShareCurr = invFamShareCurr;
		this.invFamShareReg = invFamShareReg;
		this.invSelfDivdCurr = invSelfDivdCurr;
		this.invSelfDivdReg = invSelfDivdReg;
		this.invSpsDivdCurr = invSpsDivdCurr;
		this.invSpsDivdReg = invSpsDivdReg;
		this.invFamDivdCurr = invFamDivdCurr;
		this.invFamDivdReg = invFamDivdReg;
		this.invSelfOthinvCurr = invSelfOthinvCurr;
		this.invSelfOthinvReg = invSelfOthinvReg;
		this.invSpsOthinvCurr = invSpsOthinvCurr;
		this.invSpsOthinvReg = invSpsOthinvReg;
		this.invFamOthinvCurr = invFamOthinvCurr;
		this.invFamOthinvReg = invFamOthinvReg;
		this.invCreatedBy = invCreatedBy;
		this.invCreatedDate = invCreatedDate;
		this.invModifiedBy = invModifiedBy;
		this.invModifiedDate = invModifiedDate;
	}

	public String getInvstId() {
		return this.invstId;
	}

	public void setInvstId(String invstId) {
		this.invstId = invstId;
	}

	public FnaSelfspouseDets getFnaSelfspouseDets() {
		return this.fnaSelfspouseDets;
	}

	public void setFnaSelfspouseDets(FnaSelfspouseDets fnaSelfspouseDets) {
		this.fnaSelfspouseDets = fnaSelfspouseDets;
	}

	
	public Double getInvSelfDivdCurr() {
		return this.invSelfDivdCurr;
	}

	public void setInvSelfDivdCurr(Double invSelfDivdCurr) {
		this.invSelfDivdCurr = invSelfDivdCurr;
	}

	public Double getInvSelfDivdReg() {
		return this.invSelfDivdReg;
	}

	public void setInvSelfDivdReg(Double invSelfDivdReg) {
		this.invSelfDivdReg = invSelfDivdReg;
	}

	public Double getInvSpsDivdCurr() {
		return this.invSpsDivdCurr;
	}

	public void setInvSpsDivdCurr(Double invSpsDivdCurr) {
		this.invSpsDivdCurr = invSpsDivdCurr;
	}

	public Double getInvSpsDivdReg() {
		return this.invSpsDivdReg;
	}

	public void setInvSpsDivdReg(Double invSpsDivdReg) {
		this.invSpsDivdReg = invSpsDivdReg;
	}

	public Double getInvFamDivdCurr() {
		return this.invFamDivdCurr;
	}

	public void setInvFamDivdCurr(Double invFamDivdCurr) {
		this.invFamDivdCurr = invFamDivdCurr;
	}

	public Double getInvFamDivdReg() {
		return this.invFamDivdReg;
	}

	public void setInvFamDivdReg(Double invFamDivdReg) {
		this.invFamDivdReg = invFamDivdReg;
	}

	public Double getInvSelfBondCurr() {
		return this.invSelfBondCurr;
	}

	public void setInvSelfBondCurr(Double invSelfBondCurr) {
		this.invSelfBondCurr = invSelfBondCurr;
	}

	public Double getInvSelfBondReg() {
		return this.invSelfBondReg;
	}

	public void setInvSelfBondReg(Double invSelfBondReg) {
		this.invSelfBondReg = invSelfBondReg;
	}

	public Double getInvSpsBondCurr() {
		return this.invSpsBondCurr;
	}

	public void setInvSpsBondCurr(Double invSpsBondCurr) {
		this.invSpsBondCurr = invSpsBondCurr;
	}

	public Double getInvSpsBondReg() {
		return this.invSpsBondReg;
	}

	public void setInvSpsBondReg(Double invSpsBondReg) {
		this.invSpsBondReg = invSpsBondReg;
	}

	public Double getInvFamBondCurr() {
		return this.invFamBondCurr;
	}

	public void setInvFamBondCurr(Double invFamBondCurr) {
		this.invFamBondCurr = invFamBondCurr;
	}

	public Double getInvFamBondReg() {
		return this.invFamBondReg;
	}

	public void setInvFamBondReg(Double invFamBondReg) {
		this.invFamBondReg = invFamBondReg;
	}

	public Double getInvSelfIlputCurr() {
		return this.invSelfIlputCurr;
	}

	public void setInvSelfIlputCurr(Double invSelfIlputCurr) {
		this.invSelfIlputCurr = invSelfIlputCurr;
	}

	public Double getInvSelfIlputReg() {
		return this.invSelfIlputReg;
	}

	public void setInvSelfIlputReg(Double invSelfIlputReg) {
		this.invSelfIlputReg = invSelfIlputReg;
	}

	public Double getInvSpsIlputCurr() {
		return this.invSpsIlputCurr;
	}

	public void setInvSpsIlputCurr(Double invSpsIlputCurr) {
		this.invSpsIlputCurr = invSpsIlputCurr;
	}

	public Double getInvSpsIlputReg() {
		return this.invSpsIlputReg;
	}

	public void setInvSpsIlputReg(Double invSpsIlputReg) {
		this.invSpsIlputReg = invSpsIlputReg;
	}

	public Double getInvFamIlputCurr() {
		return this.invFamIlputCurr;
	}

	public void setInvFamIlputCurr(Double invFamIlputCurr) {
		this.invFamIlputCurr = invFamIlputCurr;
	}

	public Double getInvFamIlputReg() {
		return this.invFamIlputReg;
	}

	public void setInvFamIlputReg(Double invFamIlputReg) {
		this.invFamIlputReg = invFamIlputReg;
	}

	public Double getInvSelfShareCurr() {
		return this.invSelfShareCurr;
	}

	public void setInvSelfShareCurr(Double invSelfShareCurr) {
		this.invSelfShareCurr = invSelfShareCurr;
	}

	public Double getInvSelfShareReg() {
		return this.invSelfShareReg;
	}

	public void setInvSelfShareReg(Double invSelfShareReg) {
		this.invSelfShareReg = invSelfShareReg;
	}

	public Double getInvSpsShareCurr() {
		return this.invSpsShareCurr;
	}

	public void setInvSpsShareCurr(Double invSpsShareCurr) {
		this.invSpsShareCurr = invSpsShareCurr;
	}

	public Double getInvSpsShareReg() {
		return this.invSpsShareReg;
	}

	public void setInvSpsShareReg(Double invSpsShareReg) {
		this.invSpsShareReg = invSpsShareReg;
	}

	public Double getInvFamShareCurr() {
		return this.invFamShareCurr;
	}

	public void setInvFamShareCurr(Double invFamShareCurr) {
		this.invFamShareCurr = invFamShareCurr;
	}

	public Double getInvFamShareReg() {
		return this.invFamShareReg;
	}

	public void setInvFamShareReg(Double invFamShareReg) {
		this.invFamShareReg = invFamShareReg;
	}

	public Double getInvSelfOthinvCurr() {
		return this.invSelfOthinvCurr;
	}

	public void setInvSelfOthinvCurr(Double invSelfOthinvCurr) {
		this.invSelfOthinvCurr = invSelfOthinvCurr;
	}

	public Double getInvSelfOthinvReg() {
		return this.invSelfOthinvReg;
	}

	public void setInvSelfOthinvReg(Double invSelfOthinvReg) {
		this.invSelfOthinvReg = invSelfOthinvReg;
	}

	public Double getInvSpsOthinvCurr() {
		return this.invSpsOthinvCurr;
	}

	public void setInvSpsOthinvCurr(Double invSpsOthinvCurr) {
		this.invSpsOthinvCurr = invSpsOthinvCurr;
	}

	public Double getInvSpsOthinvReg() {
		return this.invSpsOthinvReg;
	}

	public void setInvSpsOthinvReg(Double invSpsOthinvReg) {
		this.invSpsOthinvReg = invSpsOthinvReg;
	}

	public Double getInvFamOthinvCurr() {
		return this.invFamOthinvCurr;
	}

	public void setInvFamOthinvCurr(Double invFamOthinvCurr) {
		this.invFamOthinvCurr = invFamOthinvCurr;
	}

	public Double getInvFamOthinvReg() {
		return this.invFamOthinvReg;
	}

	public void setInvFamOthinvReg(Double invFamOthinvReg) {
		this.invFamOthinvReg = invFamOthinvReg;
	}

	public String getInvCreatedBy() {
		return this.invCreatedBy;
	}

	public void setInvCreatedBy(String invCreatedBy) {
		this.invCreatedBy = invCreatedBy;
	}

	public Date getInvCreatedDate() {
		return this.invCreatedDate;
	}

	public void setInvCreatedDate(Date invCreatedDate) {
		this.invCreatedDate = invCreatedDate;
	}

	public String getInvModifiedBy() {
		return this.invModifiedBy;
	}

	public void setInvModifiedBy(String invModifiedBy) {
		this.invModifiedBy = invModifiedBy;
	}

	public Date getInvModifiedDate() {
		return this.invModifiedDate;
	}

	public void setInvModifiedDate(Date invModifiedDate) {
		this.invModifiedDate = invModifiedDate;
	}

}
