package com.fipa.dto;

// Generated May 17, 2018 11:20:36 AM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * FnaLifeinsuranceNominees generated by hbm2java
 */
public class FnaLifeinsuranceNominees implements java.io.Serializable {

	private String nomineeId;
	private FnaLifeinsuranceDets fnaLifeinsuranceDets;
	private FnaSelfspouseDets fnaSelfspouseDets;
	private String nomineeName;
	private String nomineeCrtdBy;
	private Date nomineeCrtdDate;
	private String nomineeModBy;
	private Date nomineeModDate;
	private Double nomineePrcnt;

	public FnaLifeinsuranceNominees() {
	}

	public FnaLifeinsuranceNominees(String nomineeId) {
		this.nomineeId = nomineeId;
	}

	public FnaLifeinsuranceNominees(String nomineeId,
			FnaLifeinsuranceDets fnaLifeinsuranceDets,
			FnaSelfspouseDets fnaSelfspouseDets, String nomineeName,
			String nomineeCrtdBy, Date nomineeCrtdDate, String nomineeModBy,
			Date nomineeModDate, Double nomineePrcnt) {
		this.nomineeId = nomineeId;
		this.fnaLifeinsuranceDets = fnaLifeinsuranceDets;
		this.fnaSelfspouseDets = fnaSelfspouseDets;
		this.nomineeName = nomineeName;
		this.nomineeCrtdBy = nomineeCrtdBy;
		this.nomineeCrtdDate = nomineeCrtdDate;
		this.nomineeModBy = nomineeModBy;
		this.nomineeModDate = nomineeModDate;
		this.nomineePrcnt = nomineePrcnt;
	}

	public String getNomineeId() {
		return this.nomineeId;
	}

	public void setNomineeId(String nomineeId) {
		this.nomineeId = nomineeId;
	}

	public FnaLifeinsuranceDets getFnaLifeinsuranceDets() {
		return this.fnaLifeinsuranceDets;
	}

	public void setFnaLifeinsuranceDets(
			FnaLifeinsuranceDets fnaLifeinsuranceDets) {
		this.fnaLifeinsuranceDets = fnaLifeinsuranceDets;
	}

	public FnaSelfspouseDets getFnaSelfspouseDets() {
		return this.fnaSelfspouseDets;
	}

	public void setFnaSelfspouseDets(FnaSelfspouseDets fnaSelfspouseDets) {
		this.fnaSelfspouseDets = fnaSelfspouseDets;
	}

	public String getNomineeName() {
		return this.nomineeName;
	}

	public void setNomineeName(String nomineeName) {
		this.nomineeName = nomineeName;
	}

	public String getNomineeCrtdBy() {
		return this.nomineeCrtdBy;
	}

	public void setNomineeCrtdBy(String nomineeCrtdBy) {
		this.nomineeCrtdBy = nomineeCrtdBy;
	}

	public Date getNomineeCrtdDate() {
		return this.nomineeCrtdDate;
	}

	public void setNomineeCrtdDate(Date nomineeCrtdDate) {
		this.nomineeCrtdDate = nomineeCrtdDate;
	}

	public String getNomineeModBy() {
		return this.nomineeModBy;
	}

	public void setNomineeModBy(String nomineeModBy) {
		this.nomineeModBy = nomineeModBy;
	}

	public Date getNomineeModDate() {
		return this.nomineeModDate;
	}

	public void setNomineeModDate(Date nomineeModDate) {
		this.nomineeModDate = nomineeModDate;
	}

	public Double getNomineePrcnt() {
		return this.nomineePrcnt;
	}

	public void setNomineePrcnt(Double nomineePrcnt) {
		this.nomineePrcnt = nomineePrcnt;
	}

}
