package com.fipa.dto;

// Generated May 17, 2018 11:20:36 AM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;

/**
 * FnaLifeinsuranceBasicriders generated by hbm2java
 */
public class FnaLifeinsuranceBasicriders implements java.io.Serializable {

	private String riderId;
	private FnaLifeinsuranceDets fnaLifeinsuranceDets;
	private FnaSelfspouseDets fnaSelfspouseDets;
	private String planName;
	private String basorrid;
	private String premTerm;
	private Double sumAssured;
	private Double premAmount;
	private String paymentMode;
	private String paymentMethod;
	private String coverageTypes;
	private String planRemarks;
	private String planCrtdBy;
	private Date planCrtdDate;
	private String planModBy;
	private Date planModDate;
	private Date planExpDate;
	private Date planIncepDate;
	private String planReferenceId;
	private String benfRaidRefId; 
	private Integer plnlfretYrstoret;
	private Integer plnretSelfretage;
	private Integer plnretSpouseretage;
	private String plnretMultionret;
	private Double plnretCashvalonret;
	private Double plnretIntrateused;
	private Double plnretPrcnttoused;
	private Integer plncashvalRetAge;
	private String cashValRefId;
	private Date planPremTrDate;
	private Double insurCashval;
	private Double lifeInsLoans;
	private String paymentMethodBy;


	public String getPaymentMethodBy() {
		return paymentMethodBy;
	}

	public void setPaymentMethodBy(String paymentMethodBy) {
		this.paymentMethodBy = paymentMethodBy;
	}

	public FnaLifeinsuranceBasicriders() {
		
	} 
	
	public FnaLifeinsuranceBasicriders(String riderId, String planCrtdBy,
			Date planCrtdDate) {
		this.riderId = riderId;
		this.planCrtdBy = planCrtdBy;
		this.planCrtdDate = planCrtdDate;
	}

	

	public FnaLifeinsuranceBasicriders(String riderId,
			FnaLifeinsuranceDets fnaLifeinsuranceDets,
			FnaSelfspouseDets fnaSelfspouseDets, String planName,
			String basorrid, String premTerm, Double sumAssured,
			Double premAmount, String paymentMode, String paymentMethod,
			String coverageTypes, String planRemarks, String planCrtdBy,
			Date planCrtdDate, String planModBy, Date planModDate,
			Date planExpDate, Date planIncepDate, String planReferenceId,
			String benfRaidRefId, Integer plnlfretYrstoret,
			Integer plnretSelfretage, Integer plnretSpouseretage,
			String plnretMultionret, Double plnretCashvalonret,
			Double plnretIntrateused, Double plnretPrcnttoused,
			Integer plncashvalRetAge, String cashValRefId, Date planPremTrDate,Double insurCashval,
			Double lifeInsLoans,String paymentMethodBy) {
		 
		this.riderId = riderId;
		this.fnaLifeinsuranceDets = fnaLifeinsuranceDets;
		this.fnaSelfspouseDets = fnaSelfspouseDets;
		this.planName = planName;
		this.basorrid = basorrid;
		this.premTerm = premTerm;
		this.sumAssured = sumAssured;
		this.premAmount = premAmount;
		this.paymentMode = paymentMode;
		this.paymentMethod = paymentMethod;
		this.coverageTypes = coverageTypes;
		this.planRemarks = planRemarks;
		this.planCrtdBy = planCrtdBy;
		this.planCrtdDate = planCrtdDate;
		this.planModBy = planModBy;
		this.planModDate = planModDate;
		this.planExpDate = planExpDate;
		this.planIncepDate = planIncepDate;
		this.planReferenceId = planReferenceId;
		this.benfRaidRefId = benfRaidRefId;
		this.plnlfretYrstoret = plnlfretYrstoret;
		this.plnretSelfretage = plnretSelfretage;
		this.plnretSpouseretage = plnretSpouseretage;
		this.plnretMultionret = plnretMultionret;
		this.plnretCashvalonret = plnretCashvalonret;
		this.plnretIntrateused = plnretIntrateused;
		this.plnretPrcnttoused = plnretPrcnttoused;
		this.plncashvalRetAge = plncashvalRetAge;
		this.cashValRefId = cashValRefId;
		this.planPremTrDate = planPremTrDate;
				this.insurCashval = insurCashval;
		this.lifeInsLoans = lifeInsLoans;
		this.paymentMethodBy=paymentMethodBy;
		
	}
	
		public Double getInsurCashval() {
		return this.insurCashval;
	}

	public void setInsurCashval(Double insurCashval) {
		this.insurCashval = insurCashval;
	}

	public Double getLifeInsLoans() {
		return this.lifeInsLoans;
	}

	public void setLifeInsLoans(Double lifeInsLoans) {
		this.lifeInsLoans = lifeInsLoans;
	}

	public Date getPlanPremTrDate() {
		return this.planPremTrDate;
	}

	public void setPlanPremTrDate(Date planPremTrDate) {
		this.planPremTrDate = planPremTrDate;
	}

	public String getCashValRefId() {
		return this.cashValRefId;
	}

	public void setCashValRefId(String cashValRefId) {
		this.cashValRefId = cashValRefId;
	}

	public Integer getPlnlfretYrstoret() {
		return this.plnlfretYrstoret;
	}

	public void setPlnlfretYrstoret(Integer plnlfretYrstoret) {
		this.plnlfretYrstoret = plnlfretYrstoret;
	}

	public Integer getPlnretSelfretage() {
		return this.plnretSelfretage;
	}

	public void setPlnretSelfretage(Integer plnretSelfretage) {
		this.plnretSelfretage = plnretSelfretage;
	}

	public Integer getPlnretSpouseretage() {
		return this.plnretSpouseretage;
	}

	public void setPlnretSpouseretage(Integer plnretSpouseretage) {
		this.plnretSpouseretage = plnretSpouseretage;
	}

	public String getPlnretMultionret() {
		return this.plnretMultionret;
	}

	public void setPlnretMultionret(String plnretMultionret) {
		this.plnretMultionret = plnretMultionret;
	}

	public Double getPlnretCashvalonret() {
		return this.plnretCashvalonret;
	}

	public void setPlnretCashvalonret(Double plnretCashvalonret) {
		this.plnretCashvalonret = plnretCashvalonret;
	}

	public Double getPlnretIntrateused() {
		return this.plnretIntrateused;
	}

	public void setPlnretIntrateused(Double plnretIntrateused) {
		this.plnretIntrateused = plnretIntrateused;
	}

	public Double getPlnretPrcnttoused() {
		return this.plnretPrcnttoused;
	}

	public void setPlnretPrcnttoused(Double plnretPrcnttoused) {
		this.plnretPrcnttoused = plnretPrcnttoused;
	}

	public Integer getPlncashvalRetAge() {
		return this.plncashvalRetAge;
	}

	public void setPlncashvalRetAge(Integer plncashvalRetAge) {
		this.plncashvalRetAge = plncashvalRetAge;
	}

	public String getBenfRaidRefId() {
		return this.benfRaidRefId;
	}

	public void setBenfRaidRefId(String benfRaidRefId) {
		this.benfRaidRefId = benfRaidRefId;
	}

	public String getPlanReferenceId() {
		return this.planReferenceId;
	}

	public void setPlanReferenceId(String planReferenceId) {
		this.planReferenceId = planReferenceId;
	}

	public Date getPlanExpDate() {
		return planExpDate;
	}

	public void setPlanExpDate(Date planExpDate) {
		this.planExpDate = planExpDate;
	}

	public Date getPlanIncepDate() {
		return planIncepDate;
	}

	public void setPlanIncepDate(Date planIncepDate) {
		this.planIncepDate = planIncepDate;
	}

	public String getRiderId() {
		return this.riderId;
	}

	public void setRiderId(String riderId) {
		this.riderId = riderId;
	}

	public FnaLifeinsuranceDets getFnaLifeinsuranceDets() {
		return this.fnaLifeinsuranceDets;
	}

	public void setFnaLifeinsuranceDets(
			FnaLifeinsuranceDets fnaLifeinsuranceDets) {
		this.fnaLifeinsuranceDets = fnaLifeinsuranceDets;
	}

	public FnaSelfspouseDets getFnaSelfspouseDets() {
		return this.fnaSelfspouseDets;
	}

	public void setFnaSelfspouseDets(FnaSelfspouseDets fnaSelfspouseDets) {
		this.fnaSelfspouseDets = fnaSelfspouseDets;
	}

	public String getPlanName() {
		return this.planName;
	}

	public void setPlanName(String planName) {
		this.planName = planName;
	}

	public String getBasorrid() {
		return this.basorrid;
	}

	public void setBasorrid(String basorrid) {
		this.basorrid = basorrid;
	}

	public String getPremTerm() {
		return this.premTerm;
	}

	public void setPremTerm(String premTerm) {
		this.premTerm = premTerm;
	}

	public Double getSumAssured() {
		return this.sumAssured;
	}

	public void setSumAssured(Double sumAssured) {
		this.sumAssured = sumAssured;
	}

	public Double getPremAmount() {
		return this.premAmount;
	}

	public void setPremAmount(Double premAmount) {
		this.premAmount = premAmount;
	}

	public String getPaymentMode() {
		return this.paymentMode;
	}

	public void setPaymentMode(String paymentMode) {
		this.paymentMode = paymentMode;
	}

	public String getPaymentMethod() {
		return this.paymentMethod;
	}

	public void setPaymentMethod(String paymentMethod) {
		this.paymentMethod = paymentMethod;
	}

	public String getCoverageTypes() {
		return this.coverageTypes;
	}

	public void setCoverageTypes(String coverageTypes) {
		this.coverageTypes = coverageTypes;
	}

	public String getPlanRemarks() {
		return this.planRemarks;
	}

	public void setPlanRemarks(String planRemarks) {
		this.planRemarks = planRemarks;
	}

	public String getPlanCrtdBy() {
		return this.planCrtdBy;
	}

	public void setPlanCrtdBy(String planCrtdBy) {
		this.planCrtdBy = planCrtdBy;
	}

	public Date getPlanCrtdDate() {
		return this.planCrtdDate;
	}

	public void setPlanCrtdDate(Date planCrtdDate) {
		this.planCrtdDate = planCrtdDate;
	}

	public String getPlanModBy() {
		return this.planModBy;
	}

	public void setPlanModBy(String planModBy) {
		this.planModBy = planModBy;
	}

	public Date getPlanModDate() {
		return this.planModDate;
	}

	public void setPlanModDate(Date planModDate) {
		this.planModDate = planModDate;
	}

}
