package com.fipa.dto;

// Generated May 17, 2018 11:20:36 AM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * FnaLifeinsuranceDisablebenfs generated by hbm2java
 */
public class FnaLifeinsuranceDisablebenfs implements java.io.Serializable {

	private String benfId;
	private FnaLifeinsuranceDets fnaLifeinsuranceDets;
	private FnaSelfspouseDets fnaSelfspouseDets;
	private String befType;
	private String startYr;
	private String endYr;
	private Double benfSa;
	private Double benfValue;
	private Double bnefIncr;
	private String benfCrtdBy;
	private Date benfCrtdDate;
	private String benfModBy;
	private Date benfModDate;
	private String benfPlanName;
	private Date benfIncepDate;
	private Date benfExpDate;
	

	public FnaLifeinsuranceDisablebenfs() {
	}

	public FnaLifeinsuranceDisablebenfs(String benfId) {
		this.benfId = benfId;
	}

	public FnaLifeinsuranceDisablebenfs(String benfId,
			FnaLifeinsuranceDets fnaLifeinsuranceDets,
			FnaSelfspouseDets fnaSelfspouseDets, String befType,
			String startYr, String endYr, Double benfSa, Double benfValue,
			Double bnefIncr, String benfCrtdBy, Date benfCrtdDate,
			String benfModBy, Date benfModDate,String benfPlanName,Date benfIncepDate,Date benfExpDate) {
		this.benfId = benfId;
		this.fnaLifeinsuranceDets = fnaLifeinsuranceDets;
		this.fnaSelfspouseDets = fnaSelfspouseDets;
		this.befType = befType;
		this.startYr = startYr;
		this.endYr = endYr;
		this.benfSa = benfSa;
		this.benfValue = benfValue;
		this.bnefIncr = bnefIncr;
		this.benfCrtdBy = benfCrtdBy;
		this.benfCrtdDate = benfCrtdDate;
		this.benfModBy = benfModBy;
		this.benfModDate = benfModDate;
		this.benfPlanName = benfPlanName;
		this.benfIncepDate =  benfIncepDate;
		this.benfExpDate = benfExpDate;
	}

	public String getBenfPlanName() {
		return this.benfPlanName;
	}

	public void setBenfPlanName(String benfPlanName) {
		this.benfPlanName = benfPlanName;
	}

	public Date getBenfIncepDate() {
		return this.benfIncepDate;
	}

	public void setBenfIncepDate(Date benfIncepDate) {
		this.benfIncepDate = benfIncepDate;
	}

	public Date getBenfExpDate() {
		return this.benfExpDate;
	}

	public void setBenfExpDate(Date benfExpDate) {
		this.benfExpDate = benfExpDate;
	}

	public String getBenfId() {
		return this.benfId;
	}

	public void setBenfId(String benfId) {
		this.benfId = benfId;
	}

	public FnaLifeinsuranceDets getFnaLifeinsuranceDets() {
		return this.fnaLifeinsuranceDets;
	}

	public void setFnaLifeinsuranceDets(
			FnaLifeinsuranceDets fnaLifeinsuranceDets) {
		this.fnaLifeinsuranceDets = fnaLifeinsuranceDets;
	}

	public FnaSelfspouseDets getFnaSelfspouseDets() {
		return this.fnaSelfspouseDets;
	}

	public void setFnaSelfspouseDets(FnaSelfspouseDets fnaSelfspouseDets) {
		this.fnaSelfspouseDets = fnaSelfspouseDets;
	}

	public String getBefType() {
		return this.befType;
	}

	public void setBefType(String befType) {
		this.befType = befType;
	}

	public String getStartYr() {
		return this.startYr;
	}

	public void setStartYr(String startYr) {
		this.startYr = startYr;
	}

	public String getEndYr() {
		return this.endYr;
	}

	public void setEndYr(String endYr) {
		this.endYr = endYr;
	}

	public Double getBenfSa() {
		return this.benfSa;
	}

	public void setBenfSa(Double benfSa) {
		this.benfSa = benfSa;
	}

	public Double getBenfValue() {
		return this.benfValue;
	}

	public void setBenfValue(Double benfValue) {
		this.benfValue = benfValue;
	}

	public Double getBnefIncr() {
		return this.bnefIncr;
	}

	public void setBnefIncr(Double bnefIncr) {
		this.bnefIncr = bnefIncr;
	}

	public String getBenfCrtdBy() {
		return this.benfCrtdBy;
	}

	public void setBenfCrtdBy(String benfCrtdBy) {
		this.benfCrtdBy = benfCrtdBy;
	}

	public Date getBenfCrtdDate() {
		return this.benfCrtdDate;
	}

	public void setBenfCrtdDate(Date benfCrtdDate) {
		this.benfCrtdDate = benfCrtdDate;
	}

	public String getBenfModBy() {
		return this.benfModBy;
	}

	public void setBenfModBy(String benfModBy) {
		this.benfModBy = benfModBy;
	}

	public Date getBenfModDate() {
		return this.benfModDate;
	}

	public void setBenfModDate(Date benfModDate) {
		this.benfModDate = benfModDate;
	}

}
