package com.fipa.dto;

// Generated May 17, 2018 11:20:36 AM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * FnaLifeinsuranceMvRet generated by hbm2java
 */
public class FnaLifeinsuranceMvRet implements java.io.Serializable {

	private String mvretId;
	private FnaLifeinsuranceDets fnaLifeinsuranceDets;
	private FnaSelfspouseDets fnaSelfspouseDets;
	private String commenceAge;
	private String endAge;
	private Double esclationRate;
	private Double gtdIncome;
	private Double nongtdIncome;
	private Double incomeStream;
	private Double pvfvOnRet;
	private Double assumedBankInt;
	private Double mvrettotinc;
	private String mvretRemarks;
	private String mvretCrtdBy;
	private Date mvretCrtdDate;
	private String mvretModBy;
	private Date mvretModDate;
	private String mvrefId;
	private String mvretPlanName;
	private Date mvretIncDate;
	private Date mvretExpDate;
	 

	public FnaLifeinsuranceMvRet() {
	}

	public FnaLifeinsuranceMvRet(String mvretId, String mvretCrtdBy,
			Date mvretCrtdDate) {
		this.mvretId = mvretId;
		this.mvretCrtdBy = mvretCrtdBy;
		this.mvretCrtdDate = mvretCrtdDate;
	}
 

	public FnaLifeinsuranceMvRet(String mvretId,
			FnaLifeinsuranceDets fnaLifeinsuranceDets,
			FnaSelfspouseDets fnaSelfspouseDets, String commenceAge,
			String endAge, Double esclationRate, Double gtdIncome,
			Double nongtdIncome, Double incomeStream, Double pvfvOnRet,
			Double assumedBankInt, Double mvrettotinc, String mvretRemarks,
			String mvretCrtdBy, Date mvretCrtdDate, String mvretModBy,
			Date mvretModDate, String mvrefId,String mvretPlanName,
			Date mvretIncDate,Date mvretExpDate) {
		 
		this.mvretId = mvretId;
		this.fnaLifeinsuranceDets = fnaLifeinsuranceDets;
		this.fnaSelfspouseDets = fnaSelfspouseDets;
		this.commenceAge = commenceAge;
		this.endAge = endAge;
		this.esclationRate = esclationRate;
		this.gtdIncome = gtdIncome;
		this.nongtdIncome = nongtdIncome;
		this.incomeStream = incomeStream;
		this.pvfvOnRet = pvfvOnRet;
		this.assumedBankInt = assumedBankInt;
		this.mvrettotinc = mvrettotinc;
		this.mvretRemarks = mvretRemarks;
		this.mvretCrtdBy = mvretCrtdBy;
		this.mvretCrtdDate = mvretCrtdDate;
		this.mvretModBy = mvretModBy;
		this.mvretModDate = mvretModDate;
		this.mvrefId = mvrefId;
		this.mvretPlanName=mvretPlanName;
		this.mvretIncDate=mvretIncDate;
		this.mvretExpDate=mvretExpDate;
	}
 

	public String getMvretPlanName() {
		return this.mvretPlanName;
	}

	public void setMvretPlanName(String mvretPlanName) {
		this.mvretPlanName = mvretPlanName;
	}

	public Date getMvretIncDate() {
		return this.mvretIncDate;
	}

	public void setMvretIncDate(Date mvretIncDate) {
		this.mvretIncDate = mvretIncDate;
	}

	public Date getMvretExpDate() {
		return this.mvretExpDate;
	}

	public void setMvretExpDate(Date mvretExpDate) {
		this.mvretExpDate = mvretExpDate;
	}

	public String getMvrefId() {
		return this.mvrefId;
	}

	public void setMvrefId(String mvrefId) {
		this.mvrefId = mvrefId;
	}

	public Double getMvrettotinc() {
		return this.mvrettotinc;
	}

	public void setMvrettotinc(Double mvrettotinc) {
		this.mvrettotinc = mvrettotinc;
	}

	public String getMvretId() {
		return this.mvretId;
	}

	public void setMvretId(String mvretId) {
		this.mvretId = mvretId;
	}

	public FnaLifeinsuranceDets getFnaLifeinsuranceDets() {
		return this.fnaLifeinsuranceDets;
	}

	public void setFnaLifeinsuranceDets(
			FnaLifeinsuranceDets fnaLifeinsuranceDets) {
		this.fnaLifeinsuranceDets = fnaLifeinsuranceDets;
	}

	public FnaSelfspouseDets getFnaSelfspouseDets() {
		return this.fnaSelfspouseDets;
	}

	public void setFnaSelfspouseDets(FnaSelfspouseDets fnaSelfspouseDets) {
		this.fnaSelfspouseDets = fnaSelfspouseDets;
	}

	public String getCommenceAge() {
		return this.commenceAge;
	}

	public void setCommenceAge(String commenceAge) {
		this.commenceAge = commenceAge;
	}

	public String getEndAge() {
		return this.endAge;
	}

	public void setEndAge(String endAge) {
		this.endAge = endAge;
	}

	public Double getEsclationRate() {
		return this.esclationRate;
	}

	public void setEsclationRate(Double esclationRate) {
		this.esclationRate = esclationRate;
	}

	public Double getGtdIncome() {
		return this.gtdIncome;
	}

	public void setGtdIncome(Double gtdIncome) {
		this.gtdIncome = gtdIncome;
	}

	public Double getNongtdIncome() {
		return this.nongtdIncome;
	}

	public void setNongtdIncome(Double nongtdIncome) {
		this.nongtdIncome = nongtdIncome;
	}

	public Double getIncomeStream() {
		return this.incomeStream;
	}

	public void setIncomeStream(Double incomeStream) {
		this.incomeStream = incomeStream;
	}

	public Double getPvfvOnRet() {
		return this.pvfvOnRet;
	}

	public void setPvfvOnRet(Double pvfvOnRet) {
		this.pvfvOnRet = pvfvOnRet;
	}

	public Double getAssumedBankInt() {
		return this.assumedBankInt;
	}

	public void setAssumedBankInt(Double assumedBankInt) {
		this.assumedBankInt = assumedBankInt;
	}

	public String getMvretRemarks() {
		return this.mvretRemarks;
	}

	public void setMvretRemarks(String mvretRemarks) {
		this.mvretRemarks = mvretRemarks;
	}

	public String getMvretCrtdBy() {
		return this.mvretCrtdBy;
	}

	public void setMvretCrtdBy(String mvretCrtdBy) {
		this.mvretCrtdBy = mvretCrtdBy;
	}

	public Date getMvretCrtdDate() {
		return this.mvretCrtdDate;
	}

	public void setMvretCrtdDate(Date mvretCrtdDate) {
		this.mvretCrtdDate = mvretCrtdDate;
	}

	public String getMvretModBy() {
		return this.mvretModBy;
	}

	public void setMvretModBy(String mvretModBy) {
		this.mvretModBy = mvretModBy;
	}

	public Date getMvretModDate() {
		return this.mvretModDate;
	}

	public void setMvretModDate(Date mvretModDate) {
		this.mvretModDate = mvretModDate;
	}

}
