package com.fipa.dto;

// Generated May 17, 2018 11:20:36 AM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * FnaLifeinsuranceCoverages generated by hbm2java
 */
public class FnaLifeinsuranceCoverages implements java.io.Serializable {

	private String coverId;
	private FnaLifeinsuranceDets fnaLifeinsuranceDets;
	private FnaSelfspouseDets fnaSelfspouseDets;
	private String coverName;
	private String coverLevelortype;
	private String coverPlanname;
	private String coverBasorrid;
	private Date effDate;
	private Date expiryDate;
	private String coverageTerm;
	private String premPaymentTerm;
	private Double coverSumAssured;
	private Double coverPremium;
	private Double coverDeductable;
	private Double coInsurance;
	private String coverRemarks;
	private String coverCreatedBy;
	private Date coverCreatedDate;
	private String coverModifiedBy;
	private Date coverModifiedDate;
	private Double multiBoost;
	private Double maaAmtAssured;
	private String maaExPeriod;
	private String payNoofyear;
	private Double benefAmount;
	private String payYears;
	private String maxPayoutAge;
	private String typeOfHS; 
	private String descriptions;
	
	public FnaLifeinsuranceCoverages() {
	}

	public FnaLifeinsuranceCoverages(String coverId, String coverCreatedBy,
			Date coverCreatedDate) {
		this.coverId = coverId;
		this.coverCreatedBy = coverCreatedBy;
		this.coverCreatedDate = coverCreatedDate;
	}

	public FnaLifeinsuranceCoverages(String coverId,
			FnaLifeinsuranceDets fnaLifeinsuranceDets,
			FnaSelfspouseDets fnaSelfspouseDets, String coverName,
			String coverLevelortype, String coverPlanname,
			String coverBasorrid, Date effDate, Date expiryDate,
			String coverageTerm, String premPaymentTerm,
			Double coverSumAssured, Double coverPremium,
			Double coverDeductable, Double coInsurance, String coverRemarks,
			String coverCreatedBy, Date coverCreatedDate,
			String coverModifiedBy, Date coverModifiedDate, Double multiBoost,
			Double maaAmtAssured, String maaExPeriod, String payNoofyear,
			Double benefAmount, String payYears, String maxPayoutAge,
			String typeOfHS, String descriptions) {
		 
		this.coverId = coverId;
		this.fnaLifeinsuranceDets = fnaLifeinsuranceDets;
		this.fnaSelfspouseDets = fnaSelfspouseDets;
		this.coverName = coverName;
		this.coverLevelortype = coverLevelortype;
		this.coverPlanname = coverPlanname;
		this.coverBasorrid = coverBasorrid;
		this.effDate = effDate;
		this.expiryDate = expiryDate;
		this.coverageTerm = coverageTerm;
		this.premPaymentTerm = premPaymentTerm;
		this.coverSumAssured = coverSumAssured;
		this.coverPremium = coverPremium;
		this.coverDeductable = coverDeductable;
		this.coInsurance = coInsurance;
		this.coverRemarks = coverRemarks;
		this.coverCreatedBy = coverCreatedBy;
		this.coverCreatedDate = coverCreatedDate;
		this.coverModifiedBy = coverModifiedBy;
		this.coverModifiedDate = coverModifiedDate;
		this.multiBoost = multiBoost;
		this.maaAmtAssured = maaAmtAssured;
		this.maaExPeriod = maaExPeriod;
		this.payNoofyear = payNoofyear;
		this.benefAmount = benefAmount;
		this.payYears = payYears;
		this.maxPayoutAge = maxPayoutAge;
		this.typeOfHS = typeOfHS;
		this.descriptions = descriptions;
	}
	
	
	public FnaLifeinsuranceCoverages(String coverId,
			FnaLifeinsuranceDets fnaLifeinsuranceDets,
			FnaSelfspouseDets fnaSelfspouseDets,String coverPlanname,
			 Date effDate, Date expiryDate,String coverBasorrid,String coverName, 
			Double multiBoost,Double maaAmtAssured, String maaExPeriod, String payNoofyear,
			Double benefAmount, String payYears, String maxPayoutAge,
			String typeOfHS, Double coverDeductable, Double coInsurance, String descriptions,
			String coverRemarks,String coverCreatedBy, Date coverCreatedDate,
			String coverModifiedBy, Date coverModifiedDate) {
		  
		this.coverId=coverId;
		this.fnaLifeinsuranceDets=fnaLifeinsuranceDets;
		this.fnaSelfspouseDets=fnaSelfspouseDets;
		this.coverPlanname=coverPlanname;
		this.effDate=effDate;
		this.expiryDate=expiryDate;
		this.coverBasorrid=coverBasorrid;
		this.coverName=coverName;
		this.multiBoost=multiBoost;
		this.maaAmtAssured=maaAmtAssured;
		this.maaExPeriod=maaExPeriod;
		this.payNoofyear=payNoofyear;
		this.benefAmount=benefAmount;
		this.payYears=payYears;
		this.maxPayoutAge=maxPayoutAge;
		this.typeOfHS=typeOfHS;
		this.coverDeductable=coverDeductable;
		this.coInsurance=coInsurance;
		this.descriptions=descriptions;
		this.coverRemarks=coverRemarks;
		this.coverCreatedBy=coverCreatedBy;
		this.coverCreatedDate=coverCreatedDate;
		this.coverModifiedBy=coverModifiedBy;
		this.coverModifiedDate=coverModifiedDate;
		
	}

	public Double getMultiBoost() {
		return this.multiBoost;
	}

	public void setMultiBoost(Double multiBoost) {
		this.multiBoost = multiBoost;
	}

	public Double getMaaAmtAssured() {
		return this.maaAmtAssured;
	}

	public void setMaaAmtAssured(Double maaAmtAssured) {
		this.maaAmtAssured = maaAmtAssured;
	}

	public String getMaaExPeriod() {
		return this.maaExPeriod;
	}

	public void setMaaExPeriod(String maaExPeriod) {
		this.maaExPeriod = maaExPeriod;
	}

	public String getPayNoofyear() {
		return this.payNoofyear;
	}

	public void setPayNoofyear(String payNoofyear) {
		this.payNoofyear = payNoofyear;
	}

	public Double getBenefAmount() {
		return this.benefAmount;
	}

	public void setBenefAmount(Double benefAmount) {
		this.benefAmount = benefAmount;
	}

	public String getPayYears() {
		return this.payYears;
	}

	public void setPayYears(String payYears) {
		this.payYears = payYears;
	}

	public String getMaxPayoutAge() {
		return this.maxPayoutAge;
	}

	public void setMaxPayoutAge(String maxPayoutAge) {
		this.maxPayoutAge = maxPayoutAge;
	}

	public String getTypeOfHS() {
		return this.typeOfHS;
	}

	public void setTypeOfHS(String typeOfHS) {
		this.typeOfHS = typeOfHS;
	}

	public String getDescriptions() {
		return this.descriptions;
	}

	public void setDescriptions(String descriptions) {
		this.descriptions = descriptions;
	}

	public String getCoverId() {
		return this.coverId;
	}

	public void setCoverId(String coverId) {
		this.coverId = coverId;
	}

	public FnaLifeinsuranceDets getFnaLifeinsuranceDets() {
		return this.fnaLifeinsuranceDets;
	}

	public void setFnaLifeinsuranceDets(
			FnaLifeinsuranceDets fnaLifeinsuranceDets) {
		this.fnaLifeinsuranceDets = fnaLifeinsuranceDets;
	}

	public FnaSelfspouseDets getFnaSelfspouseDets() {
		return this.fnaSelfspouseDets;
	}

	public void setFnaSelfspouseDets(FnaSelfspouseDets fnaSelfspouseDets) {
		this.fnaSelfspouseDets = fnaSelfspouseDets;
	}

	public String getCoverName() {
		return this.coverName;
	}

	public void setCoverName(String coverName) {
		this.coverName = coverName;
	}

	public String getCoverLevelortype() {
		return this.coverLevelortype;
	}

	public void setCoverLevelortype(String coverLevelortype) {
		this.coverLevelortype = coverLevelortype;
	}

	public String getCoverPlanname() {
		return this.coverPlanname;
	}

	public void setCoverPlanname(String coverPlanname) {
		this.coverPlanname = coverPlanname;
	}

	public String getCoverBasorrid() {
		return this.coverBasorrid;
	}

	public void setCoverBasorrid(String coverBasorrid) {
		this.coverBasorrid = coverBasorrid;
	}

	public Date getEffDate() {
		return this.effDate;
	}

	public void setEffDate(Date effDate) {
		this.effDate = effDate;
	}

	public Date getExpiryDate() {
		return this.expiryDate;
	}

	public void setExpiryDate(Date expiryDate) {
		this.expiryDate = expiryDate;
	}

	public String getCoverageTerm() {
		return this.coverageTerm;
	}

	public void setCoverageTerm(String coverageTerm) {
		this.coverageTerm = coverageTerm;
	}

	public String getPremPaymentTerm() {
		return this.premPaymentTerm;
	}

	public void setPremPaymentTerm(String premPaymentTerm) {
		this.premPaymentTerm = premPaymentTerm;
	}

	public Double getCoverSumAssured() {
		return this.coverSumAssured;
	}

	public void setCoverSumAssured(Double coverSumAssured) {
		this.coverSumAssured = coverSumAssured;
	}

	public Double getCoverPremium() {
		return this.coverPremium;
	}

	public void setCoverPremium(Double coverPremium) {
		this.coverPremium = coverPremium;
	}

	public Double getCoverDeductable() {
		return this.coverDeductable;
	}

	public void setCoverDeductable(Double coverDeductable) {
		this.coverDeductable = coverDeductable;
	}

	public Double getCoInsurance() {
		return this.coInsurance;
	}

	public void setCoInsurance(Double coInsurance) {
		this.coInsurance = coInsurance;
	}

	public String getCoverRemarks() {
		return this.coverRemarks;
	}

	public void setCoverRemarks(String coverRemarks) {
		this.coverRemarks = coverRemarks;
	}

	public String getCoverCreatedBy() {
		return this.coverCreatedBy;
	}

	public void setCoverCreatedBy(String coverCreatedBy) {
		this.coverCreatedBy = coverCreatedBy;
	}

	public Date getCoverCreatedDate() {
		return this.coverCreatedDate;
	}

	public void setCoverCreatedDate(Date coverCreatedDate) {
		this.coverCreatedDate = coverCreatedDate;
	}

	public String getCoverModifiedBy() {
		return this.coverModifiedBy;
	}

	public void setCoverModifiedBy(String coverModifiedBy) {
		this.coverModifiedBy = coverModifiedBy;
	}

	public Date getCoverModifiedDate() {
		return this.coverModifiedDate;
	}

	public void setCoverModifiedDate(Date coverModifiedDate) {
		this.coverModifiedDate = coverModifiedDate;
	}

}
