package com.fipa.dto;

// Generated May 17, 2018 11:20:36 AM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * FnaLifeinsuranceChildedc generated by hbm2java
 */
public class FnaLifeinsuranceChildedc implements java.io.Serializable {

	private String chliId;
	private FnaLifeinsuranceDets fnaLifeinsuranceDets;
	private FnaSelfspouseDets fnaSelfspouseDets;
	private String childName;
	private String childAge;
	private String terEdcAge;
	private Double bankIntRate;
	private Double loanIntRate;
	private Double inflationRate;
	private String startAge;
	private Double paidByPolicy;
	private Double convertVal;
	private String chliRemarks;
	private String chliCrtdBy;
	private Date chliCrtdDate;
	private String chliModBy;
	private Date chliModDate;
	private String chliRefId;
	private String chliPlanName;
	private Date chliIncDate;
	private Date chliExpDate;
	
	
	public FnaLifeinsuranceChildedc() {
	}

	public FnaLifeinsuranceChildedc(String chliId, String childName,
			String chliCrtdBy, Date chliCrtdDate) {
		this.chliId = chliId;
		this.childName = childName;
		this.chliCrtdBy = chliCrtdBy;
		this.chliCrtdDate = chliCrtdDate;
	}

	 

	public FnaLifeinsuranceChildedc(String chliId,
			FnaLifeinsuranceDets fnaLifeinsuranceDets,
			FnaSelfspouseDets fnaSelfspouseDets, String childName,
			String childAge, String terEdcAge, Double bankIntRate,
			Double loanIntRate, Double inflationRate, String startAge,
			Double paidByPolicy, Double convertVal, String chliRemarks,
			String chliCrtdBy, Date chliCrtdDate, String chliModBy,
			Date chliModDate, String chliRefId, String chliPlanName,
			Date chliIncDate, Date chliExpDate) {
	 
		this.chliId = chliId;
		this.fnaLifeinsuranceDets = fnaLifeinsuranceDets;
		this.fnaSelfspouseDets = fnaSelfspouseDets;
		this.childName = childName;
		this.childAge = childAge;
		this.terEdcAge = terEdcAge;
		this.bankIntRate = bankIntRate;
		this.loanIntRate = loanIntRate;
		this.inflationRate = inflationRate;
		this.startAge = startAge;
		this.paidByPolicy = paidByPolicy;
		this.convertVal = convertVal;
		this.chliRemarks = chliRemarks;
		this.chliCrtdBy = chliCrtdBy;
		this.chliCrtdDate = chliCrtdDate;
		this.chliModBy = chliModBy;
		this.chliModDate = chliModDate;
		this.chliRefId = chliRefId;
		this.chliPlanName = chliPlanName;
		this.chliIncDate = chliIncDate;
		this.chliExpDate = chliExpDate;
	}

	public String getChildAge() {
		return this.childAge;
	}

	public void setChildAge(String childAge) {
		this.childAge = childAge;
	}

	public Double getLoanIntRate() {
		return this.loanIntRate;
	}

	public void setLoanIntRate(Double loanIntRate) {
		this.loanIntRate = loanIntRate;
	}

	public String getChliPlanName() {
		return this.chliPlanName;
	}

	public void setChliPlanName(String chliPlanName) {
		this.chliPlanName = chliPlanName;
	}

	public Date getChliIncDate() {
		return this.chliIncDate;
	}

	public void setChliIncDate(Date chliIncDate) {
		this.chliIncDate = chliIncDate;
	}

	public Date getChliExpDate() {
		return this.chliExpDate;
	}

	public void setChliExpDate(Date chliExpDate) {
		this.chliExpDate = chliExpDate;
	}

	public String getChliRefId() {
		return this.chliRefId;
	}

	public void setChliRefId(String chliRefId) {
		this.chliRefId = chliRefId;
	}

	public String getChliId() {
		return this.chliId;
	}

	public void setChliId(String chliId) {
		this.chliId = chliId;
	}

	public FnaLifeinsuranceDets getFnaLifeinsuranceDets() {
		return this.fnaLifeinsuranceDets;
	}

	public void setFnaLifeinsuranceDets(
			FnaLifeinsuranceDets fnaLifeinsuranceDets) {
		this.fnaLifeinsuranceDets = fnaLifeinsuranceDets;
	}

	public FnaSelfspouseDets getFnaSelfspouseDets() {
		return this.fnaSelfspouseDets;
	}

	public void setFnaSelfspouseDets(FnaSelfspouseDets fnaSelfspouseDets) {
		this.fnaSelfspouseDets = fnaSelfspouseDets;
	}

	public String getChildName() {
		return this.childName;
	}

	public void setChildName(String childName) {
		this.childName = childName;
	}

	public String getTerEdcAge() {
		return this.terEdcAge;
	}

	public void setTerEdcAge(String terEdcAge) {
		this.terEdcAge = terEdcAge;
	}

	public Double getBankIntRate() {
		return this.bankIntRate;
	}

	public void setBankIntRate(Double bankIntRate) {
		this.bankIntRate = bankIntRate;
	}

	public Double getInflationRate() {
		return this.inflationRate;
	}

	public void setInflationRate(Double inflationRate) {
		this.inflationRate = inflationRate;
	}

	public String getStartAge() {
		return this.startAge;
	}

	public void setStartAge(String startAge) {
		this.startAge = startAge;
	}

	public Double getPaidByPolicy() {
		return this.paidByPolicy;
	}

	public void setPaidByPolicy(Double paidByPolicy) {
		this.paidByPolicy = paidByPolicy;
	}

	public Double getConvertVal() {
		return this.convertVal;
	}

	public void setConvertVal(Double convertVal) {
		this.convertVal = convertVal;
	}

	public String getChliRemarks() {
		return this.chliRemarks;
	}

	public void setChliRemarks(String chliRemarks) {
		this.chliRemarks = chliRemarks;
	}

	public String getChliCrtdBy() {
		return this.chliCrtdBy;
	}

	public void setChliCrtdBy(String chliCrtdBy) {
		this.chliCrtdBy = chliCrtdBy;
	}

	public Date getChliCrtdDate() {
		return this.chliCrtdDate;
	}

	public void setChliCrtdDate(Date chliCrtdDate) {
		this.chliCrtdDate = chliCrtdDate;
	}

	public String getChliModBy() {
		return this.chliModBy;
	}

	public void setChliModBy(String chliModBy) {
		this.chliModBy = chliModBy;
	}

	public Date getChliModDate() {
		return this.chliModDate;
	}

	public void setChliModDate(Date chliModDate) {
		this.chliModDate = chliModDate;
	}

}
