package com.fipa.dto;

// Generated May 17, 2018 11:20:36 AM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * FnaOthareaconcern generated by hbm2java
 */
public class FnaOthareaconcern implements java.io.Serializable {

	private String fnaOacId;
	private FnaSelfspouseDets fnaSelfspouseDets;
	private String othAreaConcern;
	private String fgCreatedBy;
	private Date fgCreatedDate;
	private String fgModifiedBy;
	private Date fgModifiedDate;

	public FnaOthareaconcern() {
	}

	public FnaOthareaconcern(String fnaOacId, String othAreaConcern) {
		this.fnaOacId = fnaOacId;
		this.othAreaConcern = othAreaConcern;
	}

	public FnaOthareaconcern(String fnaOacId,
			FnaSelfspouseDets fnaSelfspouseDets, String othAreaConcern,
			String fgCreatedBy, Date fgCreatedDate, String fgModifiedBy,
			Date fgModifiedDate) {
		this.fnaOacId = fnaOacId;
		this.fnaSelfspouseDets = fnaSelfspouseDets;
		this.othAreaConcern = othAreaConcern;
		this.fgCreatedBy = fgCreatedBy;
		this.fgCreatedDate = fgCreatedDate;
		this.fgModifiedBy = fgModifiedBy;
		this.fgModifiedDate = fgModifiedDate;
	}

	public String getFnaOacId() {
		return this.fnaOacId;
	}

	public void setFnaOacId(String fnaOacId) {
		this.fnaOacId = fnaOacId;
	}

	public FnaSelfspouseDets getFnaSelfspouseDets() {
		return this.fnaSelfspouseDets;
	}

	public void setFnaSelfspouseDets(FnaSelfspouseDets fnaSelfspouseDets) {
		this.fnaSelfspouseDets = fnaSelfspouseDets;
	}

	public String getOthAreaConcern() {
		return this.othAreaConcern;
	}

	public void setOthAreaConcern(String othAreaConcern) {
		this.othAreaConcern = othAreaConcern;
	}

	public String getFgCreatedBy() {
		return this.fgCreatedBy;
	}

	public void setFgCreatedBy(String fgCreatedBy) {
		this.fgCreatedBy = fgCreatedBy;
	}

	public Date getFgCreatedDate() {
		return this.fgCreatedDate;
	}

	public void setFgCreatedDate(Date fgCreatedDate) {
		this.fgCreatedDate = fgCreatedDate;
	}

	public String getFgModifiedBy() {
		return this.fgModifiedBy;
	}

	public void setFgModifiedBy(String fgModifiedBy) {
		this.fgModifiedBy = fgModifiedBy;
	}

	public Date getFgModifiedDate() {
		return this.fgModifiedDate;
	}

	public void setFgModifiedDate(Date fgModifiedDate) {
		this.fgModifiedDate = fgModifiedDate;
	}

}
