package com.fipa.dto;

// Generated May 17, 2018 11:20:36 AM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * FnaPropownDets generated by hbm2java
 */
public class FnaPropownDets implements java.io.Serializable {

	private String propownId;
	private FnaSelfspouseDets fnaSelfspouseDets;
	private String propCateg;
	private String propDescription;
	private String propOwnership;
	private Double propMktvalue;
	private Double propMortageos;
	private String propObj;
	private Double propApprecrate;
	private Double propOsloanperd;
	private Double propLoanBySelfcash;
	private Double propLoanBySpscash;
	private Double propLoanBySelfcpf;
	private Double propLoanBySpscpf;
	private Double propMonthRentincome;
	private Double propYrstopay;
	private String propSold;
	private String propRentOnret;
	private Double propLoancash;
	private Double propLoancpf;
	private Double propCurRetInc; 
	private Double propAnlRetInc;
	private Double propYrsToRent;
	private String propCreatedBy;
	private Date propCreatedDate;
	private String propModifiedBy;
	private Date propModifiedDate;
	private String propRefId;
	private Double propFvOnrent;
	private Double propRentPerd;

	public FnaPropownDets() {
	}

	public FnaPropownDets(String propownId) {
		this.propownId = propownId;
	}

	
 
	
	public FnaPropownDets(String propownId, FnaSelfspouseDets fnaSelfspouseDets, String propCateg,
			String propDescription, String propOwnership, Double propMktvalue, Double propMortageos, String propObj,
			Double propApprecrate, Double propOsloanperd, Double propLoanBySelfcash, Double propLoanBySpscash,
			Double propLoanBySelfcpf, Double propLoanBySpscpf, Double propMonthRentincome, Double propYrstopay,
			String propSold, String propRentOnret, Double propLoancash, Double propLoancpf, Double propCurRetInc,
			Double propAnlRetInc, Double propYrsToRent, String propCreatedBy, Date propCreatedDate,
			String propModifiedBy, Date propModifiedDate, String propRefId, Double propFvOnrent,Double propRentPerd) {
		
		this.propownId = propownId;
		this.fnaSelfspouseDets = fnaSelfspouseDets;
		this.propCateg = propCateg;
		this.propDescription = propDescription;
		this.propOwnership = propOwnership;
		this.propMktvalue = propMktvalue;
		this.propMortageos = propMortageos;
		this.propObj = propObj;
		this.propApprecrate = propApprecrate;
		this.propOsloanperd = propOsloanperd;
		this.propLoanBySelfcash = propLoanBySelfcash;
		this.propLoanBySpscash = propLoanBySpscash;
		this.propLoanBySelfcpf = propLoanBySelfcpf;
		this.propLoanBySpscpf = propLoanBySpscpf;
		this.propMonthRentincome = propMonthRentincome;
		this.propYrstopay = propYrstopay;
		this.propSold = propSold;
		this.propRentOnret = propRentOnret;
		this.propLoancash = propLoancash;
		this.propLoancpf = propLoancpf;
		this.propCurRetInc = propCurRetInc;
		this.propAnlRetInc = propAnlRetInc;
		this.propYrsToRent = propYrsToRent;
		this.propCreatedBy = propCreatedBy;
		this.propCreatedDate = propCreatedDate;
		this.propModifiedBy = propModifiedBy;
		this.propModifiedDate = propModifiedDate;
		this.propRefId = propRefId;
		this.propFvOnrent = propFvOnrent;
		this.propRentPerd = propRentPerd;
	}

	public Double getPropRentPerd() {
		return this.propRentPerd;
	}

	public void setPropRentPerd(Double propRentPerd) {
		this.propRentPerd = propRentPerd;
	}

	public Double getPropFvOnrent() {
		return this.propFvOnrent;
	}

	public void setPropFvOnrent(Double propFvOnrent) {
		this.propFvOnrent = propFvOnrent;
	}

	public String getPropRefId() {
		return this.propRefId;
	}

	public void setPropRefId(String propRefId) {
		this.propRefId = propRefId;
	}

	public Double getPropYrsToRent() {
		return propYrsToRent;
	}

	public void setPropYrsToRent(Double propYrsToRent) {
		this.propYrsToRent = propYrsToRent;
	}

	public Double getPropAnlRetInc() {
		return this.propAnlRetInc;
	}

	public void setPropAnlRetInc(Double propAnlRetInc) {
		this.propAnlRetInc = propAnlRetInc;
	}

	public String getPropownId() {
		return this.propownId;
	}

	public void setPropownId(String propownId) {
		this.propownId = propownId;
	}

	public FnaSelfspouseDets getFnaSelfspouseDets() {
		return this.fnaSelfspouseDets;
	}

	public void setFnaSelfspouseDets(FnaSelfspouseDets fnaSelfspouseDets) {
		this.fnaSelfspouseDets = fnaSelfspouseDets;
	}

	public String getPropCateg() {
		return this.propCateg;
	}

	public void setPropCateg(String propCateg) {
		this.propCateg = propCateg;
	}

	public String getPropDescription() {
		return this.propDescription;
	}

	public void setPropDescription(String propDescription) {
		this.propDescription = propDescription;
	}

	public String getPropOwnership() {
		return this.propOwnership;
	}

	public void setPropOwnership(String propOwnership) {
		this.propOwnership = propOwnership;
	}

	public Double getPropMktvalue() {
		return this.propMktvalue;
	}

	public void setPropMktvalue(Double propMktvalue) {
		this.propMktvalue = propMktvalue;
	}

	public Double getPropMortageos() {
		return this.propMortageos;
	}

	public void setPropMortageos(Double propMortageos) {
		this.propMortageos = propMortageos;
	}

	public String getPropObj() {
		return this.propObj;
	}

	public void setPropObj(String propObj) {
		this.propObj = propObj;
	}

	public Double getPropApprecrate() {
		return this.propApprecrate;
	}

	public void setPropApprecrate(Double propApprecrate) {
		this.propApprecrate = propApprecrate;
	}

	public Double getPropOsloanperd() {
		return this.propOsloanperd;
	}

	public void setPropOsloanperd(Double propOsloanperd) {
		this.propOsloanperd = propOsloanperd;
	}

	public Double getPropLoanBySelfcash() {
		return this.propLoanBySelfcash;
	}

	public void setPropLoanBySelfcash(Double propLoanBySelfcash) {
		this.propLoanBySelfcash = propLoanBySelfcash;
	}

	public Double getPropLoanBySpscash() {
		return this.propLoanBySpscash;
	}

	public void setPropLoanBySpscash(Double propLoanBySpscash) {
		this.propLoanBySpscash = propLoanBySpscash;
	}

	public Double getPropLoanBySelfcpf() {
		return this.propLoanBySelfcpf;
	}

	public void setPropLoanBySelfcpf(Double propLoanBySelfcpf) {
		this.propLoanBySelfcpf = propLoanBySelfcpf;
	}

	public Double getPropLoanBySpscpf() {
		return this.propLoanBySpscpf;
	}

	public void setPropLoanBySpscpf(Double propLoanBySpscpf) {
		this.propLoanBySpscpf = propLoanBySpscpf;
	}

	public Double getPropMonthRentincome() {
		return this.propMonthRentincome;
	}

	public void setPropMonthRentincome(Double propMonthRentincome) {
		this.propMonthRentincome = propMonthRentincome;
	}

	public Double getPropYrstopay() {
		return this.propYrstopay;
	}

	public void setPropYrstopay(Double propYrstopay) {
		this.propYrstopay = propYrstopay;
	}

	public String getPropSold() {
		return this.propSold;
	}

	public void setPropSold(String propSold) {
		this.propSold = propSold;
	}

	public String getPropRentOnret() {
		return this.propRentOnret;
	}

	public void setPropRentOnret(String propRentOnret) {
		this.propRentOnret = propRentOnret;
	}

	public Double getPropLoancash() {
		return this.propLoancash;
	}

	public void setPropLoancash(Double propLoancash) {
		this.propLoancash = propLoancash;
	}

	public Double getPropLoancpf() {
		return this.propLoancpf;
	}

	public void setPropLoancpf(Double propLoancpf) {
		this.propLoancpf = propLoancpf;
	}

	public Double getPropCurRetInc() {
		return this.propCurRetInc;
	}

	public void setPropCurRetInc(Double propCurRetInc) {
		this.propCurRetInc = propCurRetInc;
	}

	public String getPropCreatedBy() {
		return this.propCreatedBy;
	}

	public void setPropCreatedBy(String propCreatedBy) {
		this.propCreatedBy = propCreatedBy;
	}

	public Date getPropCreatedDate() {
		return this.propCreatedDate;
	}

	public void setPropCreatedDate(Date propCreatedDate) {
		this.propCreatedDate = propCreatedDate;
	}

	public String getPropModifiedBy() {
		return this.propModifiedBy;
	}

	public void setPropModifiedBy(String propModifiedBy) {
		this.propModifiedBy = propModifiedBy;
	}

	public Date getPropModifiedDate() {
		return this.propModifiedDate;
	}

	public void setPropModifiedDate(Date propModifiedDate) {
		this.propModifiedDate = propModifiedDate;
	}

}
