package com.fipa.dto;

// Generated May 17, 2018 11:20:36 AM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * FnaRiskprefDets generated by hbm2java
 */
public class FnaRiskprefDets implements java.io.Serializable {

	private String riskId;//
	private FnaSelfspouseDets fnaSelfspouseDets;
	private String crInvstobj;//
	private Double crInvstamt;//
	private String crInvsttimehorizon;///
	private String crRiskpref;//
	private String crRiskclass;
	private Double crRoi;
	private String crAdeqfund;
	private String crOthconcern;
	private String crCreatedBy;
	private Date crCreatedDate;
	private String crModifiedBy;
	private Date crModifiedDate;

	public FnaRiskprefDets() {
	}

	public FnaRiskprefDets(String riskId) {
		this.riskId = riskId;
	}

	public FnaRiskprefDets(String riskId, FnaSelfspouseDets fnaSelfspouseDets,
			String crInvstobj, Double crInvstamt, String crInvsttimehorizon,
			String crRiskpref, String crRiskclass, Double crRoi,
			String crAdeqfund, String crOthconcern, String crCreatedBy,
			Date crCreatedDate, String crModifiedBy, Date crModifiedDate) {
		this.riskId = riskId;
		this.fnaSelfspouseDets = fnaSelfspouseDets;
		this.crInvstobj = crInvstobj;
		this.crInvstamt = crInvstamt;
		this.crInvsttimehorizon = crInvsttimehorizon;
		this.crRiskpref = crRiskpref;
		this.crRiskclass = crRiskclass;
		this.crRoi = crRoi;
		this.crAdeqfund = crAdeqfund;
		this.crOthconcern = crOthconcern;
		this.crCreatedBy = crCreatedBy;
		this.crCreatedDate = crCreatedDate;
		this.crModifiedBy = crModifiedBy;
		this.crModifiedDate = crModifiedDate;
	}

	public String getRiskId() {
		return this.riskId;
	}

	public void setRiskId(String riskId) {
		this.riskId = riskId;
	}

	public FnaSelfspouseDets getFnaSelfspouseDets() {
		return this.fnaSelfspouseDets;
	}

	public void setFnaSelfspouseDets(FnaSelfspouseDets fnaSelfspouseDets) {
		this.fnaSelfspouseDets = fnaSelfspouseDets;
	}

	public String getCrInvstobj() {
		return this.crInvstobj;
	}

	public void setCrInvstobj(String crInvstobj) {
		this.crInvstobj = crInvstobj;
	}

	public Double getCrInvstamt() {
		return this.crInvstamt;
	}

	public void setCrInvstamt(Double crInvstamt) {
		this.crInvstamt = crInvstamt;
	}

	public String getCrInvsttimehorizon() {
		return this.crInvsttimehorizon;
	}

	public void setCrInvsttimehorizon(String crInvsttimehorizon) {
		this.crInvsttimehorizon = crInvsttimehorizon;
	}

	public String getCrRiskpref() {
		return this.crRiskpref;
	}

	public void setCrRiskpref(String crRiskpref) {
		this.crRiskpref = crRiskpref;
	}

	public String getCrRiskclass() {
		return this.crRiskclass;
	}

	public void setCrRiskclass(String crRiskclass) {
		this.crRiskclass = crRiskclass;
	}

	public Double getCrRoi() {
		return this.crRoi;
	}

	public void setCrRoi(Double crRoi) {
		this.crRoi = crRoi;
	}

	public String getCrAdeqfund() {
		return this.crAdeqfund;
	}

	public void setCrAdeqfund(String crAdeqfund) {
		this.crAdeqfund = crAdeqfund;
	}

	public String getCrOthconcern() {
		return this.crOthconcern;
	}

	public void setCrOthconcern(String crOthconcern) {
		this.crOthconcern = crOthconcern;
	}

	public String getCrCreatedBy() {
		return this.crCreatedBy;
	}

	public void setCrCreatedBy(String crCreatedBy) {
		this.crCreatedBy = crCreatedBy;
	}

	public Date getCrCreatedDate() {
		return this.crCreatedDate;
	}

	public void setCrCreatedDate(Date crCreatedDate) {
		this.crCreatedDate = crCreatedDate;
	}

	public String getCrModifiedBy() {
		return this.crModifiedBy;
	}

	public void setCrModifiedBy(String crModifiedBy) {
		this.crModifiedBy = crModifiedBy;
	}

	public Date getCrModifiedDate() {
		return this.crModifiedDate;
	}

	public void setCrModifiedDate(Date crModifiedDate) {
		this.crModifiedDate = crModifiedDate;
	}

}
