package com.fipa.dto;

// Generated Mar 5, 2019 9:27:03 AM by Hibernate Tools 3.4.0.CR1

/**
 * FnaRetireplanCpflife generated by hbm2java
 */
public class FnaRetireplanCpflife implements java.io.Serializable {

	private String rpClId;
	private FnaSelfspouseDets fnaSelfspouseDets;
	private String age;
	private String cpflifeType;
	private Double cpflifePrem;
	private Double cpflifePayoutincome;
	private Double cpflifeFromRa;

	public FnaRetireplanCpflife() {
	}

	
	public FnaRetireplanCpflife(String rpClId) {
		this.rpClId = rpClId;
	}
	

	public FnaRetireplanCpflife(String rpClId,
			FnaSelfspouseDets fnaSelfspouseDets, String age,
			String cpflifeType, Double cpflifePrem, Double cpflifePayoutincome,
			Double cpflifeFromRa) {
		 
		this.rpClId = rpClId;
		this.fnaSelfspouseDets = fnaSelfspouseDets;
		this.age = age;
		this.cpflifeType = cpflifeType;
		this.cpflifePrem = cpflifePrem;
		this.cpflifePayoutincome = cpflifePayoutincome;
		this.cpflifeFromRa = cpflifeFromRa;
	}


	public String getRpClId() {
		return this.rpClId;
	}

	public void setRpClId(String rpClId) {
		this.rpClId = rpClId;
	}

	public FnaSelfspouseDets getFnaSelfspouseDets() {
		return this.fnaSelfspouseDets;
	}

	public void setFnaSelfspouseDets(FnaSelfspouseDets fnaSelfspouseDets) {
		this.fnaSelfspouseDets = fnaSelfspouseDets;
	}

	public String getAge() {
		return this.age;
	}

	public void setAge(String age) {
		this.age = age;
	}

	public String getCpflifeType() {
		return this.cpflifeType;
	}

	public void setCpflifeType(String cpflifeType) {
		this.cpflifeType = cpflifeType;
	}

	public Double getCpflifePrem() {
		return this.cpflifePrem;
	}

	public void setCpflifePrem(Double cpflifePrem) {
		this.cpflifePrem = cpflifePrem;
	}

	public Double getCpflifePayoutincome() {
		return this.cpflifePayoutincome;
	}

	public void setCpflifePayoutincome(Double cpflifePayoutincome) {
		this.cpflifePayoutincome = cpflifePayoutincome;
	}

	public Double getCpflifeFromRa() {
		return this.cpflifeFromRa;
	}

	public void setCpflifeFromRa(Double cpflifeFromRa) {
		this.cpflifeFromRa = cpflifeFromRa;
	}
 
}
