package com.fipa.dto;

// Generated Jun 21, 2018 6:09:59 PM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * FnaRetireplanDets generated by hbm2java
 */
public class FnaRetireplanDets implements java.io.Serializable {

	private String retId;
	private FnaSelfspouseDets fnaSelfspouseDets;
	private String retSelfAge;
	private String retSpsAge;
	private String retAgeBasedon;
	private String retYrstoret;
	private String retSelfCoordinateage;
	private String retSpsCoordinateage;
	private String retSelfProjage;
	private String retSpsProjage;
	private String retSelfLivyrs;
	private String retSpsLivyrs;
	private String retFamLivyrs;
	private Double retSelfProjroi;
	private Double retSpsProjroi;
	private Double retFamProjroi;
	private Double retSelfAnnlexpdamt;
	private String retSelfAnnlexpdyrs;
	private Double retSpsAnnlexpdamt;
	private String retSpsAnnlexpdyrs;
	private Double retFamAnnlexpdamt;
	private String retFamAnnlexpdyrs;
	private Double retSelfFv1amt;
	private String retSelfFv1yrs;
	private Double retSpsFv1amt;
	private String retSpsFv1yrs;
	private Double retFamFv1amt;
	private String retFamFv1yrs;
	private String retSelfFv1agefrom;
	private String retSelfFv1ageto;
	private String retSpsFv1agefrom;
	private String retSpsFv1ageto;
	private String retFamFv1agefrom;
	private String retFamFv1ageto;
	private Double retSelfFv2amt;
	private String retSelfFv2yrs;
	private Double retSpsFv2amt;
	private String retSpsFv2yrs;
	private Double retFamFv2amt;
	private String retFamFv2yrs;
	private String retSelfFv2agefrom;
	private String retSelfFv2ageto;
	private String retSpsFv2agefrom;
	private String retSpsFv2ageto;
	private String retFamFv2agefrom;
	private String retFamFv2ageto;
	private Double retSelfAssetval;
	private Double retSpsAssetval;
	private String retCreatedBy;
	private Date retCreatedDate;
	private String retModifiedBy;
	private Date retModifiedDate;
	private String retSelfCoordretage;
	private String retSpsCoordretage;
	private String retFamCoordretage;
	private Double retSelfSDRSAmt;
	private Double retSpsSDRSAmt;
	private Double retFamSDRSAmt; 
	private String retPropToCPF;
	private String retMedGround;
	private String retTopUpRAERS;
	private String retExistAnnuity;
	private String retFromSrsAge;
	private Double retFromSrsAmount;
	
	public FnaRetireplanDets() {
	}

	public FnaRetireplanDets(String retId) {
		this.retId = retId;
	}

	 

	public FnaRetireplanDets(String retId, FnaSelfspouseDets fnaSelfspouseDets,
			String retSelfAge, String retSpsAge, String retAgeBasedon,
			String retYrstoret, String retSelfCoordinateage,
			String retSpsCoordinateage, String retSelfProjage,
			String retSpsProjage, String retSelfLivyrs, String retSpsLivyrs,
			String retFamLivyrs, Double retSelfProjroi, Double retSpsProjroi,
			Double retFamProjroi, Double retSelfAnnlexpdamt,
			String retSelfAnnlexpdyrs, Double retSpsAnnlexpdamt,
			String retSpsAnnlexpdyrs, Double retFamAnnlexpdamt,
			String retFamAnnlexpdyrs, Double retSelfFv1amt,
			String retSelfFv1yrs, Double retSpsFv1amt, String retSpsFv1yrs,
			Double retFamFv1amt, String retFamFv1yrs, String retSelfFv1agefrom,
			String retSelfFv1ageto, String retSpsFv1agefrom,
			String retSpsFv1ageto, String retFamFv1agefrom,
			String retFamFv1ageto, Double retSelfFv2amt, String retSelfFv2yrs,
			Double retSpsFv2amt, String retSpsFv2yrs, Double retFamFv2amt,
			String retFamFv2yrs, String retSelfFv2agefrom,
			String retSelfFv2ageto, String retSpsFv2agefrom,
			String retSpsFv2ageto, String retFamFv2agefrom,
			String retFamFv2ageto, Double retSelfAssetval,
			Double retSpsAssetval, String retCreatedBy, Date retCreatedDate,
			String retModifiedBy, Date retModifiedDate,
			String retSelfCoordretage, String retSpsCoordretage,
			String retFamCoordretage, Double retSelfSDRSAmt,
			Double retSpsSDRSAmt, Double retFamSDRSAmt,String retPropToCPF,
			String retMedGround,String retTopUpRAERS,String retExistAnnuity) {
				this.retId = retId;
				this.fnaSelfspouseDets = fnaSelfspouseDets;
				this.retSelfAge = retSelfAge;
				this.retSpsAge = retSpsAge;
				this.retAgeBasedon = retAgeBasedon;
				this.retYrstoret = retYrstoret;
				this.retSelfCoordinateage = retSelfCoordinateage;
				this.retSpsCoordinateage = retSpsCoordinateage;
				this.retSelfProjage = retSelfProjage;
				this.retSpsProjage = retSpsProjage;
				this.retSelfLivyrs = retSelfLivyrs;
				this.retSpsLivyrs = retSpsLivyrs;
				this.retFamLivyrs = retFamLivyrs;
				this.retSelfProjroi = retSelfProjroi;
				this.retSpsProjroi = retSpsProjroi;
				this.retFamProjroi = retFamProjroi;
				this.retSelfAnnlexpdamt = retSelfAnnlexpdamt;
				this.retSelfAnnlexpdyrs = retSelfAnnlexpdyrs;
				this.retSpsAnnlexpdamt = retSpsAnnlexpdamt;
				this.retSpsAnnlexpdyrs = retSpsAnnlexpdyrs;
				this.retFamAnnlexpdamt = retFamAnnlexpdamt;
				this.retFamAnnlexpdyrs = retFamAnnlexpdyrs;
				this.retSelfFv1amt = retSelfFv1amt;
				this.retSelfFv1yrs = retSelfFv1yrs;
				this.retSpsFv1amt = retSpsFv1amt;
				this.retSpsFv1yrs = retSpsFv1yrs;
				this.retFamFv1amt = retFamFv1amt;
				this.retFamFv1yrs = retFamFv1yrs;
				this.retSelfFv1agefrom = retSelfFv1agefrom;
				this.retSelfFv1ageto = retSelfFv1ageto;
				this.retSpsFv1agefrom = retSpsFv1agefrom;
				this.retSpsFv1ageto = retSpsFv1ageto;
				this.retFamFv1agefrom = retFamFv1agefrom;
				this.retFamFv1ageto = retFamFv1ageto;
				this.retSelfFv2amt = retSelfFv2amt;
				this.retSelfFv2yrs = retSelfFv2yrs;
				this.retSpsFv2amt = retSpsFv2amt;
				this.retSpsFv2yrs = retSpsFv2yrs;
				this.retFamFv2amt = retFamFv2amt;
				this.retFamFv2yrs = retFamFv2yrs;
				this.retSelfFv2agefrom = retSelfFv2agefrom;
				this.retSelfFv2ageto = retSelfFv2ageto;
				this.retSpsFv2agefrom = retSpsFv2agefrom;
				this.retSpsFv2ageto = retSpsFv2ageto;
				this.retFamFv2agefrom = retFamFv2agefrom;
				this.retFamFv2ageto = retFamFv2ageto;
				this.retSelfAssetval = retSelfAssetval;
				this.retSpsAssetval = retSpsAssetval;
				this.retCreatedBy = retCreatedBy;
				this.retCreatedDate = retCreatedDate;
				this.retModifiedBy = retModifiedBy;
				this.retModifiedDate = retModifiedDate;
				this.retSelfCoordretage = retSelfCoordretage;
				this.retSpsCoordretage = retSpsCoordretage;
				this.retFamCoordretage = retFamCoordretage;
				this.retSelfSDRSAmt = retSelfSDRSAmt;
				this.retSpsSDRSAmt = retSpsSDRSAmt;
				this.retFamSDRSAmt = retFamSDRSAmt;
	}

	
	
	public String getRetPropToCPF() {
		return this.retPropToCPF;
	}

	public void setRetPropToCPF(String retPropToCPF) {
		this.retPropToCPF = retPropToCPF;
	}

	public String getRetMedGround() {
		return this.retMedGround;
	}

	public void setRetMedGround(String retMedGround) {
		this.retMedGround = retMedGround;
	}

	public String getRetTopUpRAERS() {
		return this.retTopUpRAERS;
	}

	public void setRetTopUpRAERS(String retTopUpRAERS) {
		this.retTopUpRAERS = retTopUpRAERS;
	}

	public String getRetExistAnnuity() {
		return this.retExistAnnuity;
	}

	public void setRetExistAnnuity(String retExistAnnuity) {
		this.retExistAnnuity = retExistAnnuity;
	}

	public Double getRetSelfSDRSAmt() {
		return this.retSelfSDRSAmt;
	}

	public void setRetSelfSDRSAmt(Double retSelfSDRSAmt) {
		this.retSelfSDRSAmt = retSelfSDRSAmt;
	}

	public Double getRetSpsSDRSAmt() {
		return this.retSpsSDRSAmt;
	}

	public void setRetSpsSDRSAmt(Double retSpsSDRSAmt) {
		this.retSpsSDRSAmt = retSpsSDRSAmt;
	}

	public Double getRetFamSDRSAmt() {
		return this.retFamSDRSAmt;
	}

	public void setRetFamSDRSAmt(Double retFamSDRSAmt) {
		this.retFamSDRSAmt = retFamSDRSAmt;
	}

	public String getRetId() {
		return this.retId;
	}

	public void setRetId(String retId) {
		this.retId = retId;
	}

	public FnaSelfspouseDets getFnaSelfspouseDets() {
		return this.fnaSelfspouseDets;
	}

	public void setFnaSelfspouseDets(FnaSelfspouseDets fnaSelfspouseDets) {
		this.fnaSelfspouseDets = fnaSelfspouseDets;
	}

	public String getRetSelfAge() {
		return this.retSelfAge;
	}

	public void setRetSelfAge(String retSelfAge) {
		this.retSelfAge = retSelfAge;
	}

	public String getRetSpsAge() {
		return this.retSpsAge;
	}

	public void setRetSpsAge(String retSpsAge) {
		this.retSpsAge = retSpsAge;
	}

	public String getRetAgeBasedon() {
		return this.retAgeBasedon;
	}

	public void setRetAgeBasedon(String retAgeBasedon) {
		this.retAgeBasedon = retAgeBasedon;
	}

	public String getRetYrstoret() {
		return this.retYrstoret;
	}

	public void setRetYrstoret(String retYrstoret) {
		this.retYrstoret = retYrstoret;
	}

	public String getRetSelfCoordinateage() {
		return this.retSelfCoordinateage;
	}

	public void setRetSelfCoordinateage(String retSelfCoordinateage) {
		this.retSelfCoordinateage = retSelfCoordinateage;
	}

	public String getRetSpsCoordinateage() {
		return this.retSpsCoordinateage;
	}

	public void setRetSpsCoordinateage(String retSpsCoordinateage) {
		this.retSpsCoordinateage = retSpsCoordinateage;
	}

	public String getRetSelfProjage() {
		return this.retSelfProjage;
	}

	public void setRetSelfProjage(String retSelfProjage) {
		this.retSelfProjage = retSelfProjage;
	}

	public String getRetSpsProjage() {
		return this.retSpsProjage;
	}

	public void setRetSpsProjage(String retSpsProjage) {
		this.retSpsProjage = retSpsProjage;
	}

	public String getRetSelfLivyrs() {
		return this.retSelfLivyrs;
	}

	public void setRetSelfLivyrs(String retSelfLivyrs) {
		this.retSelfLivyrs = retSelfLivyrs;
	}

	public String getRetSpsLivyrs() {
		return this.retSpsLivyrs;
	}

	public void setRetSpsLivyrs(String retSpsLivyrs) {
		this.retSpsLivyrs = retSpsLivyrs;
	}

	public String getRetFamLivyrs() {
		return this.retFamLivyrs;
	}

	public void setRetFamLivyrs(String retFamLivyrs) {
		this.retFamLivyrs = retFamLivyrs;
	}

	public Double getRetSelfProjroi() {
		return this.retSelfProjroi;
	}

	public void setRetSelfProjroi(Double retSelfProjroi) {
		this.retSelfProjroi = retSelfProjroi;
	}

	public Double getRetSpsProjroi() {
		return this.retSpsProjroi;
	}

	public void setRetSpsProjroi(Double retSpsProjroi) {
		this.retSpsProjroi = retSpsProjroi;
	}

	public Double getRetFamProjroi() {
		return this.retFamProjroi;
	}

	public void setRetFamProjroi(Double retFamProjroi) {
		this.retFamProjroi = retFamProjroi;
	}

	public Double getRetSelfAnnlexpdamt() {
		return this.retSelfAnnlexpdamt;
	}

	public void setRetSelfAnnlexpdamt(Double retSelfAnnlexpdamt) {
		this.retSelfAnnlexpdamt = retSelfAnnlexpdamt;
	}

	public String getRetSelfAnnlexpdyrs() {
		return this.retSelfAnnlexpdyrs;
	}

	public void setRetSelfAnnlexpdyrs(String retSelfAnnlexpdyrs) {
		this.retSelfAnnlexpdyrs = retSelfAnnlexpdyrs;
	}

	public Double getRetSpsAnnlexpdamt() {
		return this.retSpsAnnlexpdamt;
	}

	public void setRetSpsAnnlexpdamt(Double retSpsAnnlexpdamt) {
		this.retSpsAnnlexpdamt = retSpsAnnlexpdamt;
	}

	public String getRetSpsAnnlexpdyrs() {
		return this.retSpsAnnlexpdyrs;
	}

	public void setRetSpsAnnlexpdyrs(String retSpsAnnlexpdyrs) {
		this.retSpsAnnlexpdyrs = retSpsAnnlexpdyrs;
	}

	public Double getRetFamAnnlexpdamt() {
		return this.retFamAnnlexpdamt;
	}

	public void setRetFamAnnlexpdamt(Double retFamAnnlexpdamt) {
		this.retFamAnnlexpdamt = retFamAnnlexpdamt;
	}

	public String getRetFamAnnlexpdyrs() {
		return this.retFamAnnlexpdyrs;
	}

	public void setRetFamAnnlexpdyrs(String retFamAnnlexpdyrs) {
		this.retFamAnnlexpdyrs = retFamAnnlexpdyrs;
	}

	public Double getRetSelfFv1amt() {
		return this.retSelfFv1amt;
	}

	public void setRetSelfFv1amt(Double retSelfFv1amt) {
		this.retSelfFv1amt = retSelfFv1amt;
	}

	public String getRetSelfFv1yrs() {
		return this.retSelfFv1yrs;
	}

	public void setRetSelfFv1yrs(String retSelfFv1yrs) {
		this.retSelfFv1yrs = retSelfFv1yrs;
	}

	public Double getRetSpsFv1amt() {
		return this.retSpsFv1amt;
	}

	public void setRetSpsFv1amt(Double retSpsFv1amt) {
		this.retSpsFv1amt = retSpsFv1amt;
	}

	public String getRetSpsFv1yrs() {
		return this.retSpsFv1yrs;
	}

	public void setRetSpsFv1yrs(String retSpsFv1yrs) {
		this.retSpsFv1yrs = retSpsFv1yrs;
	}

	public Double getRetFamFv1amt() {
		return this.retFamFv1amt;
	}

	public void setRetFamFv1amt(Double retFamFv1amt) {
		this.retFamFv1amt = retFamFv1amt;
	}

	public String getRetFamFv1yrs() {
		return this.retFamFv1yrs;
	}

	public void setRetFamFv1yrs(String retFamFv1yrs) {
		this.retFamFv1yrs = retFamFv1yrs;
	}

	public String getRetSelfFv1agefrom() {
		return this.retSelfFv1agefrom;
	}

	public void setRetSelfFv1agefrom(String retSelfFv1agefrom) {
		this.retSelfFv1agefrom = retSelfFv1agefrom;
	}

	public String getRetSelfFv1ageto() {
		return this.retSelfFv1ageto;
	}

	public void setRetSelfFv1ageto(String retSelfFv1ageto) {
		this.retSelfFv1ageto = retSelfFv1ageto;
	}

	public String getRetSpsFv1agefrom() {
		return this.retSpsFv1agefrom;
	}

	public void setRetSpsFv1agefrom(String retSpsFv1agefrom) {
		this.retSpsFv1agefrom = retSpsFv1agefrom;
	}

	public String getRetSpsFv1ageto() {
		return this.retSpsFv1ageto;
	}

	public void setRetSpsFv1ageto(String retSpsFv1ageto) {
		this.retSpsFv1ageto = retSpsFv1ageto;
	}

	public String getRetFamFv1agefrom() {
		return this.retFamFv1agefrom;
	}

	public void setRetFamFv1agefrom(String retFamFv1agefrom) {
		this.retFamFv1agefrom = retFamFv1agefrom;
	}

	public String getRetFamFv1ageto() {
		return this.retFamFv1ageto;
	}

	public void setRetFamFv1ageto(String retFamFv1ageto) {
		this.retFamFv1ageto = retFamFv1ageto;
	}

	public Double getRetSelfFv2amt() {
		return this.retSelfFv2amt;
	}

	public void setRetSelfFv2amt(Double retSelfFv2amt) {
		this.retSelfFv2amt = retSelfFv2amt;
	}

	public String getRetSelfFv2yrs() {
		return this.retSelfFv2yrs;
	}

	public void setRetSelfFv2yrs(String retSelfFv2yrs) {
		this.retSelfFv2yrs = retSelfFv2yrs;
	}

	public Double getRetSpsFv2amt() {
		return this.retSpsFv2amt;
	}

	public void setRetSpsFv2amt(Double retSpsFv2amt) {
		this.retSpsFv2amt = retSpsFv2amt;
	}

	public String getRetSpsFv2yrs() {
		return this.retSpsFv2yrs;
	}

	public void setRetSpsFv2yrs(String retSpsFv2yrs) {
		this.retSpsFv2yrs = retSpsFv2yrs;
	}

	public Double getRetFamFv2amt() {
		return this.retFamFv2amt;
	}

	public void setRetFamFv2amt(Double retFamFv2amt) {
		this.retFamFv2amt = retFamFv2amt;
	}

	public String getRetFamFv2yrs() {
		return this.retFamFv2yrs;
	}

	public void setRetFamFv2yrs(String retFamFv2yrs) {
		this.retFamFv2yrs = retFamFv2yrs;
	}

	public String getRetSelfFv2agefrom() {
		return this.retSelfFv2agefrom;
	}

	public void setRetSelfFv2agefrom(String retSelfFv2agefrom) {
		this.retSelfFv2agefrom = retSelfFv2agefrom;
	}

	public String getRetSelfFv2ageto() {
		return this.retSelfFv2ageto;
	}

	public void setRetSelfFv2ageto(String retSelfFv2ageto) {
		this.retSelfFv2ageto = retSelfFv2ageto;
	}

	public String getRetSpsFv2agefrom() {
		return this.retSpsFv2agefrom;
	}

	public void setRetSpsFv2agefrom(String retSpsFv2agefrom) {
		this.retSpsFv2agefrom = retSpsFv2agefrom;
	}

	public String getRetSpsFv2ageto() {
		return this.retSpsFv2ageto;
	}

	public void setRetSpsFv2ageto(String retSpsFv2ageto) {
		this.retSpsFv2ageto = retSpsFv2ageto;
	}

	public String getRetFamFv2agefrom() {
		return this.retFamFv2agefrom;
	}

	public void setRetFamFv2agefrom(String retFamFv2agefrom) {
		this.retFamFv2agefrom = retFamFv2agefrom;
	}

	public String getRetFamFv2ageto() {
		return this.retFamFv2ageto;
	}

	public void setRetFamFv2ageto(String retFamFv2ageto) {
		this.retFamFv2ageto = retFamFv2ageto;
	}

	public Double getRetSelfAssetval() {
		return this.retSelfAssetval;
	}

	public void setRetSelfAssetval(Double retSelfAssetval) {
		this.retSelfAssetval = retSelfAssetval;
	}

	public Double getRetSpsAssetval() {
		return this.retSpsAssetval;
	}

	public void setRetSpsAssetval(Double retSpsAssetval) {
		this.retSpsAssetval = retSpsAssetval;
	}

	public String getRetCreatedBy() {
		return this.retCreatedBy;
	}

	public void setRetCreatedBy(String retCreatedBy) {
		this.retCreatedBy = retCreatedBy;
	}

	public Date getRetCreatedDate() {
		return this.retCreatedDate;
	}

	public void setRetCreatedDate(Date retCreatedDate) {
		this.retCreatedDate = retCreatedDate;
	}

	public String getRetModifiedBy() {
		return this.retModifiedBy;
	}

	public void setRetModifiedBy(String retModifiedBy) {
		this.retModifiedBy = retModifiedBy;
	}

	public Date getRetModifiedDate() {
		return this.retModifiedDate;
	}

	public void setRetModifiedDate(Date retModifiedDate) {
		this.retModifiedDate = retModifiedDate;
	}

	public String getRetSelfCoordretage() {
		return this.retSelfCoordretage;
	}

	public void setRetSelfCoordretage(String retSelfCoordretage) {
		this.retSelfCoordretage = retSelfCoordretage;
	}

	public String getRetSpsCoordretage() {
		return this.retSpsCoordretage;
	}

	public void setRetSpsCoordretage(String retSpsCoordretage) {
		this.retSpsCoordretage = retSpsCoordretage;
	}

	public String getRetFamCoordretage() {
		return this.retFamCoordretage;
	}

	public void setRetFamCoordretage(String retFamCoordretage) {
		this.retFamCoordretage = retFamCoordretage;
	}
	public String getRetFromSrsAge() {
		return retFromSrsAge;
	}

	public void setRetFromSrsAge(String retFromSrsAge) {
		this.retFromSrsAge = retFromSrsAge;
	}

	public Double getRetFromSrsAmount() {
		return retFromSrsAmount;
	}

	public void setRetFromSrsAmount(Double retFromSrsAmount) {
		this.retFromSrsAmount = retFromSrsAmount;
	}

	
}
