package com.fipa.dto;

// Generated Jun 21, 2018 6:09:59 PM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * FnaRetireplanOthpayment generated by hbm2java
 */
public class FnaRetireplanOthpayment implements java.io.Serializable {

	private String opId;
	private FnaSelfspouseDets fnaSelfspouseDets;
	private String retPaytype;
	private String retFrequency;
	private Double retAnnualexp;
	private Double retEscarate;
	private String retAgebasedon;
	private String retAgestart;
	private String retAgeend;
	private String retOthRemarks;
	private String retCrtdBy;
	private Date retCrtdDate;
	private String retModBy;
	private Date retModDate;

	public FnaRetireplanOthpayment() {
	}

	public FnaRetireplanOthpayment(String opId) {
		this.opId = opId;
	}

	public FnaRetireplanOthpayment(String opId,
			FnaSelfspouseDets fnaSelfspouseDets, String retPaytype,
			String retFrequency, Double retAnnualexp, Double retEscarate,
			String retAgebasedon, String retAgestart, String retAgeend,
			String retOthRemarks, String retCrtdBy, Date retCrtdDate,
			String retModBy, Date retModDate) {
		this.opId = opId;
		this.fnaSelfspouseDets = fnaSelfspouseDets;
		this.retPaytype = retPaytype;
		this.retFrequency = retFrequency;
		this.retAnnualexp = retAnnualexp;
		this.retEscarate = retEscarate;
		this.retAgebasedon = retAgebasedon;
		this.retAgestart = retAgestart;
		this.retAgeend = retAgeend;
		this.retOthRemarks = retOthRemarks;
		this.retCrtdBy = retCrtdBy;
		this.retCrtdDate = retCrtdDate;
		this.retModBy = retModBy;
		this.retModDate = retModDate;
	}

	public String getOpId() {
		return this.opId;
	}

	public void setOpId(String opId) {
		this.opId = opId;
	}

	public FnaSelfspouseDets getFnaSelfspouseDets() {
		return this.fnaSelfspouseDets;
	}

	public void setFnaSelfspouseDets(FnaSelfspouseDets fnaSelfspouseDets) {
		this.fnaSelfspouseDets = fnaSelfspouseDets;
	}

	public String getRetPaytype() {
		return this.retPaytype;
	}

	public void setRetPaytype(String retPaytype) {
		this.retPaytype = retPaytype;
	}

	public String getRetFrequency() {
		return this.retFrequency;
	}

	public void setRetFrequency(String retFrequency) {
		this.retFrequency = retFrequency;
	}

	public Double getRetAnnualexp() {
		return this.retAnnualexp;
	}

	public void setRetAnnualexp(Double retAnnualexp) {
		this.retAnnualexp = retAnnualexp;
	}

	public Double getRetEscarate() {
		return this.retEscarate;
	}

	public void setRetEscarate(Double retEscarate) {
		this.retEscarate = retEscarate;
	}

	public String getRetAgebasedon() {
		return this.retAgebasedon;
	}

	public void setRetAgebasedon(String retAgebasedon) {
		this.retAgebasedon = retAgebasedon;
	}

	public String getRetAgestart() {
		return this.retAgestart;
	}

	public void setRetAgestart(String retAgestart) {
		this.retAgestart = retAgestart;
	}

	public String getRetAgeend() {
		return this.retAgeend;
	}

	public void setRetAgeend(String retAgeend) {
		this.retAgeend = retAgeend;
	}

	public String getRetOthRemarks() {
		return this.retOthRemarks;
	}

	public void setRetOthRemarks(String retOthRemarks) {
		this.retOthRemarks = retOthRemarks;
	}

	public String getRetCrtdBy() {
		return this.retCrtdBy;
	}

	public void setRetCrtdBy(String retCrtdBy) {
		this.retCrtdBy = retCrtdBy;
	}

	public Date getRetCrtdDate() {
		return this.retCrtdDate;
	}

	public void setRetCrtdDate(Date retCrtdDate) {
		this.retCrtdDate = retCrtdDate;
	}

	public String getRetModBy() {
		return this.retModBy;
	}

	public void setRetModBy(String retModBy) {
		this.retModBy = retModBy;
	}

	public Date getRetModDate() {
		return this.retModDate;
	}

	public void setRetModDate(Date retModDate) {
		this.retModDate = retModDate;
	}

}
