package com.fipa.dto;

// Generated May 17, 2018 11:20:36 AM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * FnaRecomReasons generated by hbm2java
 */
public class FnaRecomReasons implements java.io.Serializable {

	private String fnaReasId;
	private FnaSelfspouseDets fnaSelfspouseDets;
	private String reasons;
	private String recCreatedBy;
	private Date recCreatedDate;
	private String recModifiedBy;
	private Date recModifiedDate;

	public FnaRecomReasons() {
	}

	public FnaRecomReasons(String fnaReasId) {
		this.fnaReasId = fnaReasId;
	}

	public FnaRecomReasons(String fnaReasId,
			FnaSelfspouseDets fnaSelfspouseDets, String reasons,
			String recCreatedBy, Date recCreatedDate, String recModifiedBy,
			Date recModifiedDate) {
		this.fnaReasId = fnaReasId;
		this.fnaSelfspouseDets = fnaSelfspouseDets;
		this.reasons = reasons;
		this.recCreatedBy = recCreatedBy;
		this.recCreatedDate = recCreatedDate;
		this.recModifiedBy = recModifiedBy;
		this.recModifiedDate = recModifiedDate;
	}

	public String getFnaReasId() {
		return this.fnaReasId;
	}

	public void setFnaReasId(String fnaReasId) {
		this.fnaReasId = fnaReasId;
	}

	public FnaSelfspouseDets getFnaSelfspouseDets() {
		return this.fnaSelfspouseDets;
	}

	public void setFnaSelfspouseDets(FnaSelfspouseDets fnaSelfspouseDets) {
		this.fnaSelfspouseDets = fnaSelfspouseDets;
	}

	public String getReasons() {
		return this.reasons;
	}

	public void setReasons(String reasons) {
		this.reasons = reasons;
	}

	public String getRecCreatedBy() {
		return this.recCreatedBy;
	}

	public void setRecCreatedBy(String recCreatedBy) {
		this.recCreatedBy = recCreatedBy;
	}

	public Date getRecCreatedDate() {
		return this.recCreatedDate;
	}

	public void setRecCreatedDate(Date recCreatedDate) {
		this.recCreatedDate = recCreatedDate;
	}

	public String getRecModifiedBy() {
		return this.recModifiedBy;
	}

	public void setRecModifiedBy(String recModifiedBy) {
		this.recModifiedBy = recModifiedBy;
	}

	public Date getRecModifiedDate() {
		return this.recModifiedDate;
	}

	public void setRecModifiedDate(Date recModifiedDate) {
		this.recModifiedDate = recModifiedDate;
	}

}
