package com.fipa.dto;

// Generated May 17, 2018 11:20:36 AM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * FnaRecomPrdtplanDet generated by hbm2java
 */
public class FnaRecomPrdtplanDet implements java.io.Serializable {

	private String recomPpId;
	private FnaSelfspouseDets fnaSelfspouseDets;
	private String recomPpProdtype;
	private String recomPpProdname;
	private Double recomPpSumassr;
	private String recomPpPaymentmode;
	private String recomPpPlanterm;
	private String recomPpPayterm;
	private Double recomPpPremium;
	private String recomPpPerson;
	private String recomPpPersonname;
	private String recomPpCateg;
	private String createdBy;
	private Date createdDate;
	private String recomPpPrin;
	private String recomPpPlan;
	private String recomPpBasrid;
	private String recomPpOpt;

	public FnaRecomPrdtplanDet() {
	}

	public FnaRecomPrdtplanDet(String recomPpId) {
		this.recomPpId = recomPpId;
	}

	public FnaRecomPrdtplanDet(String recomPpId,
			FnaSelfspouseDets fnaSelfspouseDets, String recomPpProdtype,
			String recomPpProdname, Double recomPpSumassr,
			String recomPpPaymentmode, String recomPpPlanterm,
			String recomPpPayterm, Double recomPpPremium, String recomPpPerson,
			String recomPpPersonname, String recomPpCateg, String createdBy,
			Date createdDate, String recomPpPrin, String recomPpPlan,
			String recomPpBasrid, String recomPpOpt) {
		this.recomPpId = recomPpId;
		this.fnaSelfspouseDets = fnaSelfspouseDets;
		this.recomPpProdtype = recomPpProdtype;
		this.recomPpProdname = recomPpProdname;
		this.recomPpSumassr = recomPpSumassr;
		this.recomPpPaymentmode = recomPpPaymentmode;
		this.recomPpPlanterm = recomPpPlanterm;
		this.recomPpPayterm = recomPpPayterm;
		this.recomPpPremium = recomPpPremium;
		this.recomPpPerson = recomPpPerson;
		this.recomPpPersonname = recomPpPersonname;
		this.recomPpCateg = recomPpCateg;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.recomPpPrin = recomPpPrin;
		this.recomPpPlan = recomPpPlan;
		this.recomPpBasrid = recomPpBasrid;
		this.recomPpOpt = recomPpOpt;
	}

	public String getRecomPpId() {
		return this.recomPpId;
	}

	public void setRecomPpId(String recomPpId) {
		this.recomPpId = recomPpId;
	}

	public FnaSelfspouseDets getFnaSelfspouseDets() {
		return this.fnaSelfspouseDets;
	}

	public void setFnaSelfspouseDets(FnaSelfspouseDets fnaSelfspouseDets) {
		this.fnaSelfspouseDets = fnaSelfspouseDets;
	}

	public String getRecomPpProdtype() {
		return this.recomPpProdtype;
	}

	public void setRecomPpProdtype(String recomPpProdtype) {
		this.recomPpProdtype = recomPpProdtype;
	}

	public String getRecomPpProdname() {
		return this.recomPpProdname;
	}

	public void setRecomPpProdname(String recomPpProdname) {
		this.recomPpProdname = recomPpProdname;
	}

	public Double getRecomPpSumassr() {
		return this.recomPpSumassr;
	}

	public void setRecomPpSumassr(Double recomPpSumassr) {
		this.recomPpSumassr = recomPpSumassr;
	}

	public String getRecomPpPaymentmode() {
		return this.recomPpPaymentmode;
	}

	public void setRecomPpPaymentmode(String recomPpPaymentmode) {
		this.recomPpPaymentmode = recomPpPaymentmode;
	}

	public String getRecomPpPlanterm() {
		return this.recomPpPlanterm;
	}

	public void setRecomPpPlanterm(String recomPpPlanterm) {
		this.recomPpPlanterm = recomPpPlanterm;
	}

	public String getRecomPpPayterm() {
		return this.recomPpPayterm;
	}

	public void setRecomPpPayterm(String recomPpPayterm) {
		this.recomPpPayterm = recomPpPayterm;
	}

	public Double getRecomPpPremium() {
		return this.recomPpPremium;
	}

	public void setRecomPpPremium(Double recomPpPremium) {
		this.recomPpPremium = recomPpPremium;
	}

	public String getRecomPpPerson() {
		return this.recomPpPerson;
	}

	public void setRecomPpPerson(String recomPpPerson) {
		this.recomPpPerson = recomPpPerson;
	}

	public String getRecomPpPersonname() {
		return this.recomPpPersonname;
	}

	public void setRecomPpPersonname(String recomPpPersonname) {
		this.recomPpPersonname = recomPpPersonname;
	}

	public String getRecomPpCateg() {
		return this.recomPpCateg;
	}

	public void setRecomPpCateg(String recomPpCateg) {
		this.recomPpCateg = recomPpCateg;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public String getRecomPpPrin() {
		return this.recomPpPrin;
	}

	public void setRecomPpPrin(String recomPpPrin) {
		this.recomPpPrin = recomPpPrin;
	}

	public String getRecomPpPlan() {
		return this.recomPpPlan;
	}

	public void setRecomPpPlan(String recomPpPlan) {
		this.recomPpPlan = recomPpPlan;
	}

	public String getRecomPpBasrid() {
		return this.recomPpBasrid;
	}

	public void setRecomPpBasrid(String recomPpBasrid) {
		this.recomPpBasrid = recomPpBasrid;
	}

	public String getRecomPpOpt() {
		return this.recomPpOpt;
	}

	public void setRecomPpOpt(String recomPpOpt) {
		this.recomPpOpt = recomPpOpt;
	}

}
