package com.fipa.dto;

// Generated May 17, 2018 11:20:36 AM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * FnaRecomFundDet generated by hbm2java
 */
public class FnaRecomFundDet implements java.io.Serializable {

	private String recomFfId;
	private FnaSelfspouseDets fnaSelfspouseDets;
	private String recomFfProdtype;
	private String recomFfProname;
	private Double recomFfFundriskrate;
	private String recomFfPaymentmode;
	private Double recomFfSaleschrg;
	private Double recomFfPuramount;
	private Double recomFfPurprcnt;
	private String recomFfIaffee;
	private String createdBy;
	private Date createdDate;
	private String recomFfPrin;
	private String recomFfPlan;
	private String recomFfBasrid;
	private String recomFfOpt;

	public FnaRecomFundDet() {
	}

	public FnaRecomFundDet(String recomFfId) {
		this.recomFfId = recomFfId;
	}

	public FnaRecomFundDet(String recomFfId,
			FnaSelfspouseDets fnaSelfspouseDets, String recomFfProdtype,
			String recomFfProname, Double recomFfFundriskrate,
			String recomFfPaymentmode, Double recomFfSaleschrg,
			Double recomFfPuramount, Double recomFfPurprcnt,
			String recomFfIaffee, String createdBy, Date createdDate,
			String recomFfPrin, String recomFfPlan, String recomFfBasrid,
			String recomFfOpt) {
		this.recomFfId = recomFfId;
		this.fnaSelfspouseDets = fnaSelfspouseDets;
		this.recomFfProdtype = recomFfProdtype;
		this.recomFfProname = recomFfProname;
		this.recomFfFundriskrate = recomFfFundriskrate;
		this.recomFfPaymentmode = recomFfPaymentmode;
		this.recomFfSaleschrg = recomFfSaleschrg;
		this.recomFfPuramount = recomFfPuramount;
		this.recomFfPurprcnt = recomFfPurprcnt;
		this.recomFfIaffee = recomFfIaffee;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.recomFfPrin = recomFfPrin;
		this.recomFfPlan = recomFfPlan;
		this.recomFfBasrid = recomFfBasrid;
		this.recomFfOpt = recomFfOpt;
	}

	public String getRecomFfId() {
		return this.recomFfId;
	}

	public void setRecomFfId(String recomFfId) {
		this.recomFfId = recomFfId;
	}

	public FnaSelfspouseDets getFnaSelfspouseDets() {
		return this.fnaSelfspouseDets;
	}

	public void setFnaSelfspouseDets(FnaSelfspouseDets fnaSelfspouseDets) {
		this.fnaSelfspouseDets = fnaSelfspouseDets;
	}

	public String getRecomFfProdtype() {
		return this.recomFfProdtype;
	}

	public void setRecomFfProdtype(String recomFfProdtype) {
		this.recomFfProdtype = recomFfProdtype;
	}

	public String getRecomFfProname() {
		return this.recomFfProname;
	}

	public void setRecomFfProname(String recomFfProname) {
		this.recomFfProname = recomFfProname;
	}

	public Double getRecomFfFundriskrate() {
		return this.recomFfFundriskrate;
	}

	public void setRecomFfFundriskrate(Double recomFfFundriskrate) {
		this.recomFfFundriskrate = recomFfFundriskrate;
	}

	public String getRecomFfPaymentmode() {
		return this.recomFfPaymentmode;
	}

	public void setRecomFfPaymentmode(String recomFfPaymentmode) {
		this.recomFfPaymentmode = recomFfPaymentmode;
	}

	public Double getRecomFfSaleschrg() {
		return this.recomFfSaleschrg;
	}

	public void setRecomFfSaleschrg(Double recomFfSaleschrg) {
		this.recomFfSaleschrg = recomFfSaleschrg;
	}

	public Double getRecomFfPuramount() {
		return this.recomFfPuramount;
	}

	public void setRecomFfPuramount(Double recomFfPuramount) {
		this.recomFfPuramount = recomFfPuramount;
	}

	public Double getRecomFfPurprcnt() {
		return this.recomFfPurprcnt;
	}

	public void setRecomFfPurprcnt(Double recomFfPurprcnt) {
		this.recomFfPurprcnt = recomFfPurprcnt;
	}

	public String getRecomFfIaffee() {
		return this.recomFfIaffee;
	}

	public void setRecomFfIaffee(String recomFfIaffee) {
		this.recomFfIaffee = recomFfIaffee;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public String getRecomFfPrin() {
		return this.recomFfPrin;
	}

	public void setRecomFfPrin(String recomFfPrin) {
		this.recomFfPrin = recomFfPrin;
	}

	public String getRecomFfPlan() {
		return this.recomFfPlan;
	}

	public void setRecomFfPlan(String recomFfPlan) {
		this.recomFfPlan = recomFfPlan;
	}

	public String getRecomFfBasrid() {
		return this.recomFfBasrid;
	}

	public void setRecomFfBasrid(String recomFfBasrid) {
		this.recomFfBasrid = recomFfBasrid;
	}

	public String getRecomFfOpt() {
		return this.recomFfOpt;
	}

	public void setRecomFfOpt(String recomFfOpt) {
		this.recomFfOpt = recomFfOpt;
	}

}
