package com.fipa.dto;

// Generated May 17, 2018 11:20:36 AM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * FnaRetireplanIncome generated by hbm2java
 */
public class FnaRetireplanIncome implements java.io.Serializable {

	private String riId;
	private FnaSelfspouseDets fnaSelfspouseDets;
	private String retIncDesc;
	private Double retIncAmountSelf;
	private String retIncYrstoretSelf;
	private String retIncYrsSelf;
	private Double retIncAmountSps;
	private String retIncYrstoretSps;
	private String retIncYrsSps;
	private String retIncCrtdBy;
	private Date retIncCrtdDate;
	private String retIncModBy;
	private Date retIncModDate;

	public FnaRetireplanIncome() {
	}

	public FnaRetireplanIncome(String riId) {
		this.riId = riId;
	}

	public FnaRetireplanIncome(String riId,
			FnaSelfspouseDets fnaSelfspouseDets, String retIncDesc,
			Double retIncAmountSelf, String retIncYrstoretSelf,
			String retIncYrsSelf, Double retIncAmountSps,
			String retIncYrstoretSps, String retIncYrsSps, String retIncCrtdBy,
			Date retIncCrtdDate, String retIncModBy, Date retIncModDate) {
		this.riId = riId;
		this.fnaSelfspouseDets = fnaSelfspouseDets;
		this.retIncDesc = retIncDesc;
		this.retIncAmountSelf = retIncAmountSelf;
		this.retIncYrstoretSelf = retIncYrstoretSelf;
		this.retIncYrsSelf = retIncYrsSelf;
		this.retIncAmountSps = retIncAmountSps;
		this.retIncYrstoretSps = retIncYrstoretSps;
		this.retIncYrsSps = retIncYrsSps;
		this.retIncCrtdBy = retIncCrtdBy;
		this.retIncCrtdDate = retIncCrtdDate;
		this.retIncModBy = retIncModBy;
		this.retIncModDate = retIncModDate;
	}

	public String getRiId() {
		return this.riId;
	}

	public void setRiId(String riId) {
		this.riId = riId;
	}

	public FnaSelfspouseDets getFnaSelfspouseDets() {
		return this.fnaSelfspouseDets;
	}

	public void setFnaSelfspouseDets(FnaSelfspouseDets fnaSelfspouseDets) {
		this.fnaSelfspouseDets = fnaSelfspouseDets;
	}

	public String getRetIncDesc() {
		return this.retIncDesc;
	}

	public void setRetIncDesc(String retIncDesc) {
		this.retIncDesc = retIncDesc;
	}

	public Double getRetIncAmountSelf() {
		return this.retIncAmountSelf;
	}

	public void setRetIncAmountSelf(Double retIncAmountSelf) {
		this.retIncAmountSelf = retIncAmountSelf;
	}

	public String getRetIncYrstoretSelf() {
		return this.retIncYrstoretSelf;
	}

	public void setRetIncYrstoretSelf(String retIncYrstoretSelf) {
		this.retIncYrstoretSelf = retIncYrstoretSelf;
	}

	public String getRetIncYrsSelf() {
		return this.retIncYrsSelf;
	}

	public void setRetIncYrsSelf(String retIncYrsSelf) {
		this.retIncYrsSelf = retIncYrsSelf;
	}

	public Double getRetIncAmountSps() {
		return this.retIncAmountSps;
	}

	public void setRetIncAmountSps(Double retIncAmountSps) {
		this.retIncAmountSps = retIncAmountSps;
	}

	public String getRetIncYrstoretSps() {
		return this.retIncYrstoretSps;
	}

	public void setRetIncYrstoretSps(String retIncYrstoretSps) {
		this.retIncYrstoretSps = retIncYrstoretSps;
	}

	public String getRetIncYrsSps() {
		return this.retIncYrsSps;
	}

	public void setRetIncYrsSps(String retIncYrsSps) {
		this.retIncYrsSps = retIncYrsSps;
	}

	public String getRetIncCrtdBy() {
		return this.retIncCrtdBy;
	}

	public void setRetIncCrtdBy(String retIncCrtdBy) {
		this.retIncCrtdBy = retIncCrtdBy;
	}

	public Date getRetIncCrtdDate() {
		return this.retIncCrtdDate;
	}

	public void setRetIncCrtdDate(Date retIncCrtdDate) {
		this.retIncCrtdDate = retIncCrtdDate;
	}

	public String getRetIncModBy() {
		return this.retIncModBy;
	}

	public void setRetIncModBy(String retIncModBy) {
		this.retIncModBy = retIncModBy;
	}

	public Date getRetIncModDate() {
		return this.retIncModDate;
	}

	public void setRetIncModDate(Date retIncModDate) {
		this.retIncModDate = retIncModDate;
	}

}
