package com.fipa.dto;

// Generated Jun 20, 2019 6:21:59 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * FnaSrs generated by hbm2java
 */
public class FnaSrs implements java.io.Serializable {

	private String srsId;
	private FnaSelfspouseDets fnaSelfspouseDets;
	private String srsRefId;
	private String srsClassfy;
	private String srsDesc;
	private String srsFreq;
	private Double srsAmount;
	private Date srsPerdFrom;
	private Date srsPerdTo;
	private String srsAgestart;
	private String srsPayoutPerd;
	private String srsCrtdBy;
	private Date srsCrtdDate;
	private String srsModBy;
	private Date srsModDate;

	public FnaSrs() {
	}

	public FnaSrs(String srsId) {
		this.srsId = srsId;
	}

	public FnaSrs(String srsId, FnaSelfspouseDets fnaSelfspouseDets,
			String srsRefId, String srsClassfy, String srsDesc, String srsFreq,
			Double srsAmount, Date srsPerdFrom, Date srsPerdTo,
			String srsAgestart, String srsPayoutPerd, String srsCrtdBy,
			Date srsCrtdDate, String srsModBy, Date srsModDate) {
		this.srsId = srsId;
		this.fnaSelfspouseDets = fnaSelfspouseDets;
		this.srsRefId = srsRefId;
		this.srsClassfy = srsClassfy;
		this.srsDesc = srsDesc;
		this.srsFreq = srsFreq;
		this.srsAmount = srsAmount;
		this.srsPerdFrom = srsPerdFrom;
		this.srsPerdTo = srsPerdTo;
		this.srsAgestart = srsAgestart;
		this.srsPayoutPerd = srsPayoutPerd;
		this.srsCrtdBy = srsCrtdBy;
		this.srsCrtdDate = srsCrtdDate;
		this.srsModBy = srsModBy;
		this.srsModDate = srsModDate;
	}

	public String getSrsId() {
		return this.srsId;
	}

	public void setSrsId(String srsId) {
		this.srsId = srsId;
	}

	public FnaSelfspouseDets getFnaSelfspouseDets() {
		return this.fnaSelfspouseDets;
	}

	public void setFnaSelfspouseDets(FnaSelfspouseDets fnaSelfspouseDets) {
		this.fnaSelfspouseDets = fnaSelfspouseDets;
	}

	public String getSrsRefId() {
		return this.srsRefId;
	}

	public void setSrsRefId(String srsRefId) {
		this.srsRefId = srsRefId;
	}

	public String getSrsClassfy() {
		return this.srsClassfy;
	}

	public void setSrsClassfy(String srsClassfy) {
		this.srsClassfy = srsClassfy;
	}

	public String getSrsDesc() {
		return this.srsDesc;
	}

	public void setSrsDesc(String srsDesc) {
		this.srsDesc = srsDesc;
	}

	public String getSrsFreq() {
		return this.srsFreq;
	}

	public void setSrsFreq(String srsFreq) {
		this.srsFreq = srsFreq;
	}

	public Double getSrsAmount() {
		return this.srsAmount;
	}

	public void setSrsAmount(Double srsAmount) {
		this.srsAmount = srsAmount;
	}

	public Date getSrsPerdFrom() {
		return this.srsPerdFrom;
	}

	public void setSrsPerdFrom(Date srsPerdFrom) {
		this.srsPerdFrom = srsPerdFrom;
	}

	public Date getSrsPerdTo() {
		return this.srsPerdTo;
	}

	public void setSrsPerdTo(Date srsPerdTo) {
		this.srsPerdTo = srsPerdTo;
	}

	public String getSrsAgestart() {
		return this.srsAgestart;
	}

	public void setSrsAgestart(String srsAgestart) {
		this.srsAgestart = srsAgestart;
	}

	public String getSrsPayoutPerd() {
		return this.srsPayoutPerd;
	}

	public void setSrsPayoutPerd(String srsPayoutPerd) {
		this.srsPayoutPerd = srsPayoutPerd;
	}

	public String getSrsCrtdBy() {
		return this.srsCrtdBy;
	}

	public void setSrsCrtdBy(String srsCrtdBy) {
		this.srsCrtdBy = srsCrtdBy;
	}

	public Date getSrsCrtdDate() {
		return this.srsCrtdDate;
	}

	public void setSrsCrtdDate(Date srsCrtdDate) {
		this.srsCrtdDate = srsCrtdDate;
	}

	public String getSrsModBy() {
		return this.srsModBy;
	}

	public void setSrsModBy(String srsModBy) {
		this.srsModBy = srsModBy;
	}

	public Date getSrsModDate() {
		return this.srsModDate;
	}

	public void setSrsModDate(Date srsModDate) {
		this.srsModDate = srsModDate;
	}

}
