package com.fipa.dto;

// Generated May 17, 2018 11:20:36 AM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * FnaSwtchrepPlanDet generated by hbm2java
 */
public class FnaSwtchrepPlanDet implements java.io.Serializable {

	private String swrepPpId;
	private FnaSelfspouseDets fnaSelfspouseDets;
	private String swrepPpProdtype;
	private String swrepPpProdname;
	private Double swrepPpSumassr;
	private String swrepPpTransind;
	private String swrepPpPaymentmode;
	private String swrepPpPlanterm;
	private String swrepPpPayterm;
	private Double swrepPpPremium;
	private String createdBy;
	private Date createdDate;
	private String swrepPpPrin;
	private String swrepPpPlan;
	private String swrepPpBasrid;
	private String swrepPpOpt;

	public FnaSwtchrepPlanDet() {
	}

	public FnaSwtchrepPlanDet(String swrepPpId) {
		this.swrepPpId = swrepPpId;
	}

	public FnaSwtchrepPlanDet(String swrepPpId,
			FnaSelfspouseDets fnaSelfspouseDets, String swrepPpProdtype,
			String swrepPpProdname, Double swrepPpSumassr,
			String swrepPpTransind, String swrepPpPaymentmode,
			String swrepPpPlanterm, String swrepPpPayterm,
			Double swrepPpPremium, String createdBy, Date createdDate,
			String swrepPpPrin, String swrepPpPlan, String swrepPpBasrid,
			String swrepPpOpt) {
		this.swrepPpId = swrepPpId;
		this.fnaSelfspouseDets = fnaSelfspouseDets;
		this.swrepPpProdtype = swrepPpProdtype;
		this.swrepPpProdname = swrepPpProdname;
		this.swrepPpSumassr = swrepPpSumassr;
		this.swrepPpTransind = swrepPpTransind;
		this.swrepPpPaymentmode = swrepPpPaymentmode;
		this.swrepPpPlanterm = swrepPpPlanterm;
		this.swrepPpPayterm = swrepPpPayterm;
		this.swrepPpPremium = swrepPpPremium;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.swrepPpPrin = swrepPpPrin;
		this.swrepPpPlan = swrepPpPlan;
		this.swrepPpBasrid = swrepPpBasrid;
		this.swrepPpOpt = swrepPpOpt;
	}

	public String getSwrepPpId() {
		return this.swrepPpId;
	}

	public void setSwrepPpId(String swrepPpId) {
		this.swrepPpId = swrepPpId;
	}

	public FnaSelfspouseDets getFnaSelfspouseDets() {
		return this.fnaSelfspouseDets;
	}

	public void setFnaSelfspouseDets(FnaSelfspouseDets fnaSelfspouseDets) {
		this.fnaSelfspouseDets = fnaSelfspouseDets;
	}

	public String getSwrepPpProdtype() {
		return this.swrepPpProdtype;
	}

	public void setSwrepPpProdtype(String swrepPpProdtype) {
		this.swrepPpProdtype = swrepPpProdtype;
	}

	public String getSwrepPpProdname() {
		return this.swrepPpProdname;
	}

	public void setSwrepPpProdname(String swrepPpProdname) {
		this.swrepPpProdname = swrepPpProdname;
	}

	public Double getSwrepPpSumassr() {
		return this.swrepPpSumassr;
	}

	public void setSwrepPpSumassr(Double swrepPpSumassr) {
		this.swrepPpSumassr = swrepPpSumassr;
	}

	public String getSwrepPpTransind() {
		return this.swrepPpTransind;
	}

	public void setSwrepPpTransind(String swrepPpTransind) {
		this.swrepPpTransind = swrepPpTransind;
	}

	public String getSwrepPpPaymentmode() {
		return this.swrepPpPaymentmode;
	}

	public void setSwrepPpPaymentmode(String swrepPpPaymentmode) {
		this.swrepPpPaymentmode = swrepPpPaymentmode;
	}

	public String getSwrepPpPlanterm() {
		return this.swrepPpPlanterm;
	}

	public void setSwrepPpPlanterm(String swrepPpPlanterm) {
		this.swrepPpPlanterm = swrepPpPlanterm;
	}

	public String getSwrepPpPayterm() {
		return this.swrepPpPayterm;
	}

	public void setSwrepPpPayterm(String swrepPpPayterm) {
		this.swrepPpPayterm = swrepPpPayterm;
	}

	public Double getSwrepPpPremium() {
		return this.swrepPpPremium;
	}

	public void setSwrepPpPremium(Double swrepPpPremium) {
		this.swrepPpPremium = swrepPpPremium;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public String getSwrepPpPrin() {
		return this.swrepPpPrin;
	}

	public void setSwrepPpPrin(String swrepPpPrin) {
		this.swrepPpPrin = swrepPpPrin;
	}

	public String getSwrepPpPlan() {
		return this.swrepPpPlan;
	}

	public void setSwrepPpPlan(String swrepPpPlan) {
		this.swrepPpPlan = swrepPpPlan;
	}

	public String getSwrepPpBasrid() {
		return this.swrepPpBasrid;
	}

	public void setSwrepPpBasrid(String swrepPpBasrid) {
		this.swrepPpBasrid = swrepPpBasrid;
	}

	public String getSwrepPpOpt() {
		return this.swrepPpOpt;
	}

	public void setSwrepPpOpt(String swrepPpOpt) {
		this.swrepPpOpt = swrepPpOpt;
	}

}
