package com.fipa.dto;

// Generated May 17, 2018 11:20:36 AM by Hibernate Tools 4.0.0

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * FnaSelfspouseDets generated by hbm2java
 */
public class FnaSelfspouseDets implements java.io.Serializable {

	private String fnaId;
	private String mgrId;//
	private String advstfId;//
	private String fpmsCustid;//
	private String fnaType;//
	private String dfSelfName;//
	private Date dfSelfDob;//
	private String dfSelfAge;//
	private String dfSelfNationality;//
	private String dfSelfIdtype;//
	private String dfSelfNric;//
	private String dfSelfMartsts;//
	private String dfSelfOccpn;//
	private String dfSelfGender;//
	private String dfSelfEmpsts;//
	private String dfSelfSmoking;//
	private String dfSelfHomeaddr;//
	private String dfSelfHomeaddr2;//
	private String dfSelfHomepostal;//
	private String dfSelfHomecntry;//
	private String dfSelfRegmailaddrSame;//
	private String dfSelfMailaddr;//
	private String dfSelfMailaddr2;//
	private String dfSelfMailpostal;//
	private String dfSelfMailcntry;//
	private String dfSelfAddrreason;//
	private String dfSelfOffaddr;
	private String dfSelfPersemail;//
	private String dfSelfOffemail;//
	private String dfSelfMobile;//
	private String dfSelfHome;//
	private String dfSelfOffice;//
	private String dfSelfFax;//
	private Double dfSelfAnnlincome;//
	private String dfSelfSrcFd;//
	private String dfSelfempcat;//
	private String dfSelfCompname;//
	private String dfSelfBusinatr;
	private String dfSelfBusinatrDets;
	private String dfSelfUsnotifyflg;
	private String dfSelfUspersonflg;
	private String dfSelfUstaxno;
	private String dfSelfRescountry;
	private String dfSpsName;//
	private Date dfSpsDob;//
	private String dfSpsAge;//
	private String dfSpsNationality;//
	private String dfSpsIdtype;//
	private String dfSpsNric;//
	private String dfSpsMartsts;//
	private String dfSpsOccpn;//
	private String dfSpsGender;//
	private String dfSpsEmpsts;//
	private String dfSpsSmoking;//
	private String dfSpsPersemail;//
	private String dfSpsHp;//
	private String dfSpsOffice;//
	private String dfSpsHome;//
	private String dfSpsFax;//
	private String dfSpsHomeaddr;//
	private String dfSpsHomeaddr2;//
	private String dfSpsHomepostalcode;//
	private String dfSpsHomecntry;//
	private String dfSpsRegmailaddrSame;//
	private String dfSpsRegaddrAsSelf;//
	private String dfSpsMailaddrAsSelf;//
	private String dfSpsMailaddr;//
	private String dfSpsMailaddr2;//
	private String dfSpsMailpostal;//
	private String dfSpsMailcntry;//
	private String dfSpsAddrreason;//
	private String dfSpsSrcfund;//
	private Double dfSpsAnnlincome;//
	private String dfSpsempcat;//
	private String dfSpsCompname;//
	private String dfSpsBusinatr;
	private String dfSpsBusinatrDets;
	private String dfSpsUsnotifyflg;
	private String dfSpsUspersonflg;
	private String dfSpsUstaxno;
	private String dfSpsRescountry;
	private Date dfCreatedDatetime;//
	private String dfCreatedBy;//
	private Date dfCreatedDate;//
	private String dfModifiedBy;//
	private Date dfModifiedDate;//
	private String dfRemarks;
	private Set<FnaLifeinsuranceNominees> fnaLifeinsuranceNomineeses = new HashSet<FnaLifeinsuranceNominees>(0);
	private Set<FnaAssetCashdets> fnaAssetCashdetses = new HashSet<FnaAssetCashdets>(0);
	private Set<FnaLifeinsuranceCoverages> fnaLifeinsuranceCoverageses = new HashSet<FnaLifeinsuranceCoverages>(0);
	private Set<FnaSummaryAnalysis> fnaSummaryAnalysises = new HashSet<FnaSummaryAnalysis>(	0);
	private Set<FnaCpfMonthcontDets> fnaCpfMonthcontDetses = new HashSet<FnaCpfMonthcontDets>(			0);
	private Set<FnaRetireplanIncome> fnaRetireplanIncomes = new HashSet<FnaRetireplanIncome>(			0);
	private Set<FnaLifeinsuranceDets> fnaLifeinsuranceDetses = new HashSet<FnaLifeinsuranceDets>(			0);
	private Set<FnaContingencyDets> fnaContingencyDetses = new HashSet<FnaContingencyDets>(			0);
	private Set<FnaAssetOtherdets> fnaAssetOtherdetses = new HashSet<FnaAssetOtherdets>(			0);
	private Set<FnaOtherAssetdets> fnaOtherAssetdetses = new HashSet<FnaOtherAssetdets>(			0);
	private Set<FnaDependantDets> fnaDependantDetses = new HashSet<FnaDependantDets>(			0);
	private Set<FnaCpfDeductions> fnaCpfDeductionses = new HashSet<FnaCpfDeductions>(			0);
	private Set<FnaFingoalsconcern> fnaFingoalsconcerns = new HashSet<FnaFingoalsconcern>(			0);
	private Set<FnaOthareaconcern> fnaOthareaconcerns = new HashSet<FnaOthareaconcern>(			0);
	private Set<FnaAssetBusiandpersdets> fnaAssetBusiandpersdetses = new HashSet<FnaAssetBusiandpersdets>(			0);
	private Set<FnaInputinvestmentsDets> fnaInputinvestmentsDetses = new HashSet<FnaInputinvestmentsDets>(			0);
	private Set<FnaSavingsinvDets> fnaSavingsinvDetses = new HashSet<FnaSavingsinvDets>(			0);
	private Set<FnaCurassDets> fnaCurassDetses = new HashSet<FnaCurassDets>(0);
	private Set<FnaLifeinsuranceMvRet> fnaLifeinsuranceMvRets = new HashSet<FnaLifeinsuranceMvRet>(			0);
	private Set<FnaLifeinsuranceDisablebenfs> fnaLifeinsuranceDisablebenfses = new HashSet<FnaLifeinsuranceDisablebenfs>(			0);
	private Set<FnaPropownDets> fnaPropownDetses = new HashSet<FnaPropownDets>(			0);
	private Set<FnaCpfBalanceDets> fnaCpfBalanceDetses = new HashSet<FnaCpfBalanceDets>(			0);
	private Set<FnaRecomReasons> fnaRecomReasonses = new HashSet<FnaRecomReasons>(			0);
	private Set<FnaLifeinsuranceBasicriders> fnaLifeinsuranceBasicriderses = new HashSet<FnaLifeinsuranceBasicriders>(			0);
	private Set<FnaVehicleownDets> fnaVehicleownDetses = new HashSet<FnaVehicleownDets>(			0);
	private Set<FnaEstatePlan> fnaEstatePlans = new HashSet<FnaEstatePlan>(0);
	private Set<FnaRiskprefDets> fnaRiskprefDetses = new HashSet<FnaRiskprefDets>(			0);
	private Set<FnaHealthinsInfo> fnaHealthinsInfos = new HashSet<FnaHealthinsInfo>(			0);
	private Set<FnaAdvDeclare> fnaAdvDeclares = new HashSet<FnaAdvDeclare>(0);
	private Set<FnaCashAtBank> fnaCashAtBanks = new HashSet<FnaCashAtBank>(0);
	private Set<FnaLifeinsuranceChildedc> fnaLifeinsuranceChildedcs = new HashSet<FnaLifeinsuranceChildedc>(			0);
	private Set<FnaExpenditureDets> fnaExpenditureDetses = new HashSet<FnaExpenditureDets>(			0);
	private Set<FnaPersprio> fnaPersprios = new HashSet<FnaPersprio>(0);
	private Set<FnaFinLiability> fnaFinLiabilities = new HashSet<FnaFinLiability>(			0);
	private Set<FnaSwtchrepPlanDet> fnaSwtchrepPlanDets = new HashSet<FnaSwtchrepPlanDet>(			0);
	private Set<FnaSrcofincome> fnaSrcofincomes = new HashSet<FnaSrcofincome>(0);
	private Set<FnaRecomPrdtplanDet> fnaRecomPrdtplanDets = new HashSet<FnaRecomPrdtplanDet>(			0);
	private Set<FnaRecomFundDet> fnaRecomFundDets = new HashSet<FnaRecomFundDet>(			0);
	private Set<FnaSwtchrepFundDet> fnaSwtchrepFundDets = new HashSet<FnaSwtchrepFundDet>(			0);
	private Set<FnaRetireplanDets> fnaRetireplanDetses = new HashSet<FnaRetireplanDets>(			0);
	private Set<FnaApptypes> fnaApptypeses = new HashSet<FnaApptypes>(0);
	private Set<FnaChilddetails> fnaChilddetailses = new HashSet<FnaChilddetails>(			0);
	private Set<FnaInvsetmentSummary> fnaInvsetmentSummaries = new HashSet<FnaInvsetmentSummary>(			0);

	public FnaSelfspouseDets() {
	}

	public FnaSelfspouseDets(String fnaId, String mgrId, String advstfId) {
		this.fnaId = fnaId;
		this.mgrId = mgrId;
		this.advstfId = advstfId;
	}

	 
	 
	public FnaSelfspouseDets(String fnaId, String mgrId, String advstfId,
			String fpmsCustid, String fnaType, String dfSelfName,
			Date dfSelfDob, String dfSelfAge, String dfSelfNationality,
			String dfSelfIdtype, String dfSelfNric, String dfSelfMartsts,
			String dfSelfOccpn, String dfSelfGender, String dfSelfEmpsts,
			String dfSelfSmoking, String dfSelfHomeaddr,
			String dfSelfHomeaddr2, String dfSelfHomepostal,
			String dfSelfHomecntry, String dfSelfRegmailaddrSame,
			String dfSelfMailaddr, String dfSelfMailaddr2,
			String dfSelfMailpostal, String dfSelfMailcntry,
			String dfSelfAddrreason, String dfSelfOffaddr,
			String dfSelfPersemail, String dfSelfOffemail, String dfSelfMobile,
			String dfSelfHome, String dfSelfOffice, String dfSelfFax,
			Double dfSelfAnnlincome, String dfSelfSrcFd, String dfSelfempcat,
			String dfSelfCompname, String dfSelfBusinatr,
			String dfSelfBusinatrDets, String dfSelfUsnotifyflg,
			String dfSelfUspersonflg, String dfSelfUstaxno,
			String dfSelfRescountry, String dfSpsName, Date dfSpsDob,
			String dfSpsAge, String dfSpsNationality, String dfSpsIdtype,
			String dfSpsNric, String dfSpsMartsts, String dfSpsOccpn,
			String dfSpsGender, String dfSpsEmpsts, String dfSpsSmoking,
			String dfSpsPersemail, String dfSpsHp, String dfSpsOffice,
			String dfSpsHome, String dfSpsFax, String dfSpsHomeaddr,
			String dfSpsHomeaddr2, String dfSpsHomepostalcode,
			String dfSpsHomecntry, String dfSpsRegmailaddrSame,
			String dfSpsRegaddrAsSelf, String dfSpsMailaddrAsSelf,
			String dfSpsMailaddr, String dfSpsMailaddr2,
			String dfSpsMailpostal, String dfSpsMailcntry,
			String dfSpsAddrreason, String dfSpsSrcfund,
			Double dfSpsAnnlincome, String dfSpsempcat, String dfSpsCompname,
			String dfSpsBusinatr, String dfSpsBusinatrDets,
			String dfSpsUsnotifyflg, String dfSpsUspersonflg,
			String dfSpsUstaxno, String dfSpsRescountry,
			Date dfCreatedDatetime, String dfCreatedBy,
			Date dfCreatedDate, String dfModifiedBy, Date dfModifiedDate,String dfRemarks,
			Set<FnaLifeinsuranceNominees> fnaLifeinsuranceNomineeses,
			Set<FnaAssetCashdets> fnaAssetCashdetses,
			Set<FnaLifeinsuranceCoverages> fnaLifeinsuranceCoverageses,
			Set<FnaSummaryAnalysis> fnaSummaryAnalysises,
			Set<FnaCpfMonthcontDets> fnaCpfMonthcontDetses,
			Set<FnaRetireplanIncome> fnaRetireplanIncomes,
			Set<FnaLifeinsuranceDets> fnaLifeinsuranceDetses,
			Set<FnaContingencyDets> fnaContingencyDetses,
			Set<FnaAssetOtherdets> fnaAssetOtherdetses,
			Set<FnaOtherAssetdets> fnaOtherAssetdetses,
			Set<FnaDependantDets> fnaDependantDetses,
			Set<FnaCpfDeductions> fnaCpfDeductionses,
			Set<FnaFingoalsconcern> fnaFingoalsconcerns,
			Set<FnaOthareaconcern> fnaOthareaconcerns,
			Set<FnaAssetBusiandpersdets> fnaAssetBusiandpersdetses,
			Set<FnaInputinvestmentsDets> fnaInputinvestmentsDetses,
			Set<FnaSavingsinvDets> fnaSavingsinvDetses,
			Set<FnaCurassDets> fnaCurassDetses,
			Set<FnaLifeinsuranceMvRet> fnaLifeinsuranceMvRets,
			Set<FnaLifeinsuranceDisablebenfs> fnaLifeinsuranceDisablebenfses,
			Set<FnaPropownDets> fnaPropownDetses,
			Set<FnaCpfBalanceDets> fnaCpfBalanceDetses,
			Set<FnaRecomReasons> fnaRecomReasonses,
			Set<FnaLifeinsuranceBasicriders> fnaLifeinsuranceBasicriderses,
			Set<FnaVehicleownDets> fnaVehicleownDetses,
			Set<FnaEstatePlan> fnaEstatePlans,
			Set<FnaRiskprefDets> fnaRiskprefDetses,
			Set<FnaHealthinsInfo> fnaHealthinsInfos,
			Set<FnaAdvDeclare> fnaAdvDeclares,
			Set<FnaCashAtBank> fnaCashAtBanks,
			Set<FnaLifeinsuranceChildedc> fnaLifeinsuranceChildedcs,
			Set<FnaExpenditureDets> fnaExpenditureDetses,
			Set<FnaPersprio> fnaPersprios,
			Set<FnaFinLiability> fnaFinLiabilities,
			Set<FnaSwtchrepPlanDet> fnaSwtchrepPlanDets,
			Set<FnaSrcofincome> fnaSrcofincomes,
			Set<FnaRecomPrdtplanDet> fnaRecomPrdtplanDets,
			Set<FnaRecomFundDet> fnaRecomFundDets,
			Set<FnaSwtchrepFundDet> fnaSwtchrepFundDets,
			Set<FnaRetireplanDets> fnaRetireplanDetses,
			Set<FnaApptypes> fnaApptypeses,
			Set<FnaChilddetails> fnaChilddetailses,
			Set<FnaInvsetmentSummary> fnaInvsetmentSummaries) {
		 
		this.fnaId = fnaId;
		this.mgrId = mgrId;
		this.advstfId = advstfId;
		this.fpmsCustid = fpmsCustid;
		this.fnaType = fnaType;
		this.dfSelfName = dfSelfName;
		this.dfSelfDob = dfSelfDob;
		this.dfSelfAge = dfSelfAge;
		this.dfSelfNationality = dfSelfNationality;
		this.dfSelfIdtype = dfSelfIdtype;
		this.dfSelfNric = dfSelfNric;
		this.dfSelfMartsts = dfSelfMartsts;
		this.dfSelfOccpn = dfSelfOccpn;
		this.dfSelfGender = dfSelfGender;
		this.dfSelfEmpsts = dfSelfEmpsts;
		this.dfSelfSmoking = dfSelfSmoking;
		this.dfSelfHomeaddr = dfSelfHomeaddr;
		this.dfSelfHomeaddr2 = dfSelfHomeaddr2;
		this.dfSelfHomepostal = dfSelfHomepostal;
		this.dfSelfHomecntry = dfSelfHomecntry;
		this.dfSelfRegmailaddrSame = dfSelfRegmailaddrSame;
		this.dfSelfMailaddr = dfSelfMailaddr;
		this.dfSelfMailaddr2 = dfSelfMailaddr2;
		this.dfSelfMailpostal = dfSelfMailpostal;
		this.dfSelfMailcntry = dfSelfMailcntry;
		this.dfSelfAddrreason = dfSelfAddrreason;
		this.dfSelfOffaddr = dfSelfOffaddr;
		this.dfSelfPersemail = dfSelfPersemail;
		this.dfSelfOffemail = dfSelfOffemail;
		this.dfSelfMobile = dfSelfMobile;
		this.dfSelfHome = dfSelfHome;
		this.dfSelfOffice = dfSelfOffice;
		this.dfSelfFax = dfSelfFax;
		this.dfSelfAnnlincome = dfSelfAnnlincome;
		this.dfSelfSrcFd = dfSelfSrcFd;
		this.dfSelfempcat = dfSelfempcat;
		this.dfSelfCompname = dfSelfCompname;
		this.dfSelfBusinatr = dfSelfBusinatr;
		this.dfSelfBusinatrDets = dfSelfBusinatrDets;
		this.dfSelfUsnotifyflg = dfSelfUsnotifyflg;
		this.dfSelfUspersonflg = dfSelfUspersonflg;
		this.dfSelfUstaxno = dfSelfUstaxno;
		this.dfSelfRescountry = dfSelfRescountry;
		this.dfSpsName = dfSpsName;
		this.dfSpsDob = dfSpsDob;
		this.dfSpsAge = dfSpsAge;
		this.dfSpsNationality = dfSpsNationality;
		this.dfSpsIdtype = dfSpsIdtype;
		this.dfSpsNric = dfSpsNric;
		this.dfSpsMartsts = dfSpsMartsts;
		this.dfSpsOccpn = dfSpsOccpn;
		this.dfSpsGender = dfSpsGender;
		this.dfSpsEmpsts = dfSpsEmpsts;
		this.dfSpsSmoking = dfSpsSmoking;
		this.dfSpsPersemail = dfSpsPersemail;
		this.dfSpsHp = dfSpsHp;
		this.dfSpsOffice = dfSpsOffice;
		this.dfSpsHome = dfSpsHome;
		this.dfSpsFax = dfSpsFax;
		this.dfSpsHomeaddr = dfSpsHomeaddr;
		this.dfSpsHomeaddr2 = dfSpsHomeaddr2;
		this.dfSpsHomepostalcode = dfSpsHomepostalcode;
		this.dfSpsHomecntry = dfSpsHomecntry;
		this.dfSpsRegmailaddrSame = dfSpsRegmailaddrSame;
		this.dfSpsRegaddrAsSelf = dfSpsRegaddrAsSelf;
		this.dfSpsMailaddrAsSelf = dfSpsMailaddrAsSelf;
		this.dfSpsMailaddr = dfSpsMailaddr;
		this.dfSpsMailaddr2 = dfSpsMailaddr2;
		this.dfSpsMailpostal = dfSpsMailpostal;
		this.dfSpsMailcntry = dfSpsMailcntry;
		this.dfSpsAddrreason = dfSpsAddrreason;
		this.dfSpsSrcfund = dfSpsSrcfund;
		this.dfSpsAnnlincome = dfSpsAnnlincome;
		this.dfSpsempcat = dfSpsempcat;
		this.dfSpsCompname = dfSpsCompname;
		this.dfSpsBusinatr = dfSpsBusinatr;
		this.dfSpsBusinatrDets = dfSpsBusinatrDets;
		this.dfSpsUsnotifyflg = dfSpsUsnotifyflg;
		this.dfSpsUspersonflg = dfSpsUspersonflg;
		this.dfSpsUstaxno = dfSpsUstaxno;
		this.dfSpsRescountry = dfSpsRescountry;
		this.dfCreatedDatetime = dfCreatedDatetime;
		this.dfCreatedBy = dfCreatedBy;
		this.dfCreatedDate = dfCreatedDate;
		this.dfModifiedBy = dfModifiedBy;
		this.dfModifiedDate = dfModifiedDate;
		this.dfRemarks = dfRemarks;
		this.fnaLifeinsuranceNomineeses = fnaLifeinsuranceNomineeses;
		this.fnaAssetCashdetses = fnaAssetCashdetses;
		this.fnaLifeinsuranceCoverageses = fnaLifeinsuranceCoverageses;
		this.fnaSummaryAnalysises = fnaSummaryAnalysises;
		this.fnaCpfMonthcontDetses = fnaCpfMonthcontDetses;
		this.fnaRetireplanIncomes = fnaRetireplanIncomes;
		this.fnaLifeinsuranceDetses = fnaLifeinsuranceDetses;
		this.fnaContingencyDetses = fnaContingencyDetses;
		this.fnaAssetOtherdetses = fnaAssetOtherdetses;
		this.fnaOtherAssetdetses = fnaOtherAssetdetses;
		this.fnaDependantDetses = fnaDependantDetses;
		this.fnaCpfDeductionses = fnaCpfDeductionses;
		this.fnaFingoalsconcerns = fnaFingoalsconcerns;
		this.fnaOthareaconcerns = fnaOthareaconcerns;
		this.fnaAssetBusiandpersdetses = fnaAssetBusiandpersdetses;
		this.fnaInputinvestmentsDetses = fnaInputinvestmentsDetses;
		this.fnaSavingsinvDetses = fnaSavingsinvDetses;
		this.fnaCurassDetses = fnaCurassDetses;
		this.fnaLifeinsuranceMvRets = fnaLifeinsuranceMvRets;
		this.fnaLifeinsuranceDisablebenfses = fnaLifeinsuranceDisablebenfses;
		this.fnaPropownDetses = fnaPropownDetses;
		this.fnaCpfBalanceDetses = fnaCpfBalanceDetses;
		this.fnaRecomReasonses = fnaRecomReasonses;
		this.fnaLifeinsuranceBasicriderses = fnaLifeinsuranceBasicriderses;
		this.fnaVehicleownDetses = fnaVehicleownDetses;
		this.fnaEstatePlans = fnaEstatePlans;
		this.fnaRiskprefDetses = fnaRiskprefDetses;
		this.fnaHealthinsInfos = fnaHealthinsInfos;
		this.fnaAdvDeclares = fnaAdvDeclares;
		this.fnaCashAtBanks = fnaCashAtBanks;
		this.fnaLifeinsuranceChildedcs = fnaLifeinsuranceChildedcs;
		this.fnaExpenditureDetses = fnaExpenditureDetses;
		this.fnaPersprios = fnaPersprios;
		this.fnaFinLiabilities = fnaFinLiabilities;
		this.fnaSwtchrepPlanDets = fnaSwtchrepPlanDets;
		this.fnaSrcofincomes = fnaSrcofincomes;
		this.fnaRecomPrdtplanDets = fnaRecomPrdtplanDets;
		this.fnaRecomFundDets = fnaRecomFundDets;
		this.fnaSwtchrepFundDets = fnaSwtchrepFundDets;
		this.fnaRetireplanDetses = fnaRetireplanDetses;
		this.fnaApptypeses = fnaApptypeses;
		this.fnaChilddetailses = fnaChilddetailses;
		this.fnaInvsetmentSummaries = fnaInvsetmentSummaries;
	}

	
	public String getDfRemarks() {
		return this.dfRemarks;
	}

	public void setDfRemarks(String dfRemarks) {
		this.dfRemarks = dfRemarks;
	}

	public String getDfSelfempcat() {
		return dfSelfempcat;
	}

	public void setDfSelfempcat(String dfSelfempcat) {
		this.dfSelfempcat = dfSelfempcat;
	}

	public String getDfSpsempcat() {
		return dfSpsempcat;
	}

	public void setDfSpsempcat(String dfSpsempcat) {
		this.dfSpsempcat = dfSpsempcat;
	}

	public String getDfSelfSrcFd() {
		return dfSelfSrcFd;
	}

	public void setDfSelfSrcFd(String dfSelfSrcFd) {
		this.dfSelfSrcFd = dfSelfSrcFd;
	}

	public String getFnaId() {
		return this.fnaId;
	}

	public void setFnaId(String fnaId) {
		this.fnaId = fnaId;
	}

	public String getMgrId() {
		return this.mgrId;
	}

	public void setMgrId(String mgrId) {
		this.mgrId = mgrId;
	}

	public String getAdvstfId() {
		return this.advstfId;
	}

	public void setAdvstfId(String advstfId) {
		this.advstfId = advstfId;
	}

	public String getFpmsCustid() {
		return this.fpmsCustid;
	}

	public void setFpmsCustid(String fpmsCustid) {
		this.fpmsCustid = fpmsCustid;
	}

	public String getFnaType() {
		return this.fnaType;
	}

	public void setFnaType(String fnaType) {
		this.fnaType = fnaType;
	}

	public String getDfSelfName() {
		return this.dfSelfName;
	}

	public void setDfSelfName(String dfSelfName) {
		this.dfSelfName = dfSelfName;
	}

	public Date getDfSelfDob() {
		return this.dfSelfDob;
	}

	public void setDfSelfDob(Date dfSelfDob) {
		this.dfSelfDob = dfSelfDob;
	}

	public String getDfSelfAge() {
		return this.dfSelfAge;
	}

	public void setDfSelfAge(String dfSelfAge) {
		this.dfSelfAge = dfSelfAge;
	}

	public String getDfSelfNationality() {
		return this.dfSelfNationality;
	}

	public void setDfSelfNationality(String dfSelfNationality) {
		this.dfSelfNationality = dfSelfNationality;
	}

	public String getDfSelfIdtype() {
		return this.dfSelfIdtype;
	}

	public void setDfSelfIdtype(String dfSelfIdtype) {
		this.dfSelfIdtype = dfSelfIdtype;
	}

	public String getDfSelfNric() {
		return this.dfSelfNric;
	}

	public void setDfSelfNric(String dfSelfNric) {
		this.dfSelfNric = dfSelfNric;
	}

	public String getDfSelfMartsts() {
		return this.dfSelfMartsts;
	}

	public void setDfSelfMartsts(String dfSelfMartsts) {
		this.dfSelfMartsts = dfSelfMartsts;
	}

	public String getDfSelfOccpn() {
		return this.dfSelfOccpn;
	}

	public void setDfSelfOccpn(String dfSelfOccpn) {
		this.dfSelfOccpn = dfSelfOccpn;
	}

	public String getDfSelfGender() {
		return this.dfSelfGender;
	}

	public void setDfSelfGender(String dfSelfGender) {
		this.dfSelfGender = dfSelfGender;
	}

	public String getDfSelfEmpsts() {
		return this.dfSelfEmpsts;
	}

	public void setDfSelfEmpsts(String dfSelfEmpsts) {
		this.dfSelfEmpsts = dfSelfEmpsts;
	}

	public String getDfSelfSmoking() {
		return this.dfSelfSmoking;
	}

	public void setDfSelfSmoking(String dfSelfSmoking) {
		this.dfSelfSmoking = dfSelfSmoking;
	}

	public String getDfSelfHomeaddr() {
		return this.dfSelfHomeaddr;
	}

	public void setDfSelfHomeaddr(String dfSelfHomeaddr) {
		this.dfSelfHomeaddr = dfSelfHomeaddr;
	}

	public String getDfSelfHomeaddr2() {
		return this.dfSelfHomeaddr2;
	}

	public void setDfSelfHomeaddr2(String dfSelfHomeaddr2) {
		this.dfSelfHomeaddr2 = dfSelfHomeaddr2;
	}

	public String getDfSelfHomepostal() {
		return this.dfSelfHomepostal;
	}

	public void setDfSelfHomepostal(String dfSelfHomepostal) {
		this.dfSelfHomepostal = dfSelfHomepostal;
	}

	public String getDfSelfHomecntry() {
		return this.dfSelfHomecntry;
	}

	public void setDfSelfHomecntry(String dfSelfHomecntry) {
		this.dfSelfHomecntry = dfSelfHomecntry;
	}

	public String getDfSelfRegmailaddrSame() {
		return this.dfSelfRegmailaddrSame;
	}

	public void setDfSelfRegmailaddrSame(String dfSelfRegmailaddrSame) {
		this.dfSelfRegmailaddrSame = dfSelfRegmailaddrSame;
	}

	public String getDfSelfMailaddr() {
		return this.dfSelfMailaddr;
	}

	public void setDfSelfMailaddr(String dfSelfMailaddr) {
		this.dfSelfMailaddr = dfSelfMailaddr;
	}

	public String getDfSelfMailaddr2() {
		return this.dfSelfMailaddr2;
	}

	public void setDfSelfMailaddr2(String dfSelfMailaddr2) {
		this.dfSelfMailaddr2 = dfSelfMailaddr2;
	}

	public String getDfSelfMailpostal() {
		return this.dfSelfMailpostal;
	}

	public void setDfSelfMailpostal(String dfSelfMailpostal) {
		this.dfSelfMailpostal = dfSelfMailpostal;
	}

	public String getDfSelfMailcntry() {
		return this.dfSelfMailcntry;
	}

	public void setDfSelfMailcntry(String dfSelfMailcntry) {
		this.dfSelfMailcntry = dfSelfMailcntry;
	}

	public String getDfSelfAddrreason() {
		return this.dfSelfAddrreason;
	}

	public void setDfSelfAddrreason(String dfSelfAddrreason) {
		this.dfSelfAddrreason = dfSelfAddrreason;
	}

	public String getDfSelfOffaddr() {
		return this.dfSelfOffaddr;
	}

	public void setDfSelfOffaddr(String dfSelfOffaddr) {
		this.dfSelfOffaddr = dfSelfOffaddr;
	}

	public String getDfSelfPersemail() {
		return this.dfSelfPersemail;
	}

	public void setDfSelfPersemail(String dfSelfPersemail) {
		this.dfSelfPersemail = dfSelfPersemail;
	}

	public String getDfSelfOffemail() {
		return this.dfSelfOffemail;
	}

	public void setDfSelfOffemail(String dfSelfOffemail) {
		this.dfSelfOffemail = dfSelfOffemail;
	}

	public String getDfSelfMobile() {
		return this.dfSelfMobile;
	}

	public void setDfSelfMobile(String dfSelfMobile) {
		this.dfSelfMobile = dfSelfMobile;
	}

	public String getDfSelfHome() {
		return this.dfSelfHome;
	}

	public void setDfSelfHome(String dfSelfHome) {
		this.dfSelfHome = dfSelfHome;
	}

	public String getDfSelfOffice() {
		return this.dfSelfOffice;
	}

	public void setDfSelfOffice(String dfSelfOffice) {
		this.dfSelfOffice = dfSelfOffice;
	}

	public String getDfSelfFax() {
		return this.dfSelfFax;
	}

	public void setDfSelfFax(String dfSelfFax) {
		this.dfSelfFax = dfSelfFax;
	}

	public Double getDfSelfAnnlincome() {
		return this.dfSelfAnnlincome;
	}

	public void setDfSelfAnnlincome(Double dfSelfAnnlincome) {
		this.dfSelfAnnlincome = dfSelfAnnlincome;
	}

	public String getDfSelfCompname() {
		return this.dfSelfCompname;
	}

	public void setDfSelfCompname(String dfSelfCompname) {
		this.dfSelfCompname = dfSelfCompname;
	}

	public String getDfSelfBusinatr() {
		return this.dfSelfBusinatr;
	}

	public void setDfSelfBusinatr(String dfSelfBusinatr) {
		this.dfSelfBusinatr = dfSelfBusinatr;
	}

	public String getDfSelfBusinatrDets() {
		return this.dfSelfBusinatrDets;
	}

	public void setDfSelfBusinatrDets(String dfSelfBusinatrDets) {
		this.dfSelfBusinatrDets = dfSelfBusinatrDets;
	}

	public String getDfSelfUsnotifyflg() {
		return this.dfSelfUsnotifyflg;
	}

	public void setDfSelfUsnotifyflg(String dfSelfUsnotifyflg) {
		this.dfSelfUsnotifyflg = dfSelfUsnotifyflg;
	}

	public String getDfSelfUspersonflg() {
		return this.dfSelfUspersonflg;
	}

	public void setDfSelfUspersonflg(String dfSelfUspersonflg) {
		this.dfSelfUspersonflg = dfSelfUspersonflg;
	}

	public String getDfSelfUstaxno() {
		return this.dfSelfUstaxno;
	}

	public void setDfSelfUstaxno(String dfSelfUstaxno) {
		this.dfSelfUstaxno = dfSelfUstaxno;
	}

	public String getDfSelfRescountry() {
		return this.dfSelfRescountry;
	}

	public void setDfSelfRescountry(String dfSelfRescountry) {
		this.dfSelfRescountry = dfSelfRescountry;
	}

	public String getDfSpsName() {
		return this.dfSpsName;
	}

	public void setDfSpsName(String dfSpsName) {
		this.dfSpsName = dfSpsName;
	}

	public Date getDfSpsDob() {
		return this.dfSpsDob;
	}

	public void setDfSpsDob(Date dfSpsDob) {
		this.dfSpsDob = dfSpsDob;
	}

	public String getDfSpsAge() {
		return this.dfSpsAge;
	}

	public void setDfSpsAge(String dfSpsAge) {
		this.dfSpsAge = dfSpsAge;
	}

	public String getDfSpsNationality() {
		return this.dfSpsNationality;
	}

	public void setDfSpsNationality(String dfSpsNationality) {
		this.dfSpsNationality = dfSpsNationality;
	}

	public String getDfSpsIdtype() {
		return this.dfSpsIdtype;
	}

	public void setDfSpsIdtype(String dfSpsIdtype) {
		this.dfSpsIdtype = dfSpsIdtype;
	}

	public String getDfSpsNric() {
		return this.dfSpsNric;
	}

	public void setDfSpsNric(String dfSpsNric) {
		this.dfSpsNric = dfSpsNric;
	}

	public String getDfSpsMartsts() {
		return this.dfSpsMartsts;
	}

	public void setDfSpsMartsts(String dfSpsMartsts) {
		this.dfSpsMartsts = dfSpsMartsts;
	}

	public String getDfSpsOccpn() {
		return this.dfSpsOccpn;
	}

	public void setDfSpsOccpn(String dfSpsOccpn) {
		this.dfSpsOccpn = dfSpsOccpn;
	}

	public String getDfSpsGender() {
		return this.dfSpsGender;
	}

	public void setDfSpsGender(String dfSpsGender) {
		this.dfSpsGender = dfSpsGender;
	}

	public String getDfSpsEmpsts() {
		return this.dfSpsEmpsts;
	}

	public void setDfSpsEmpsts(String dfSpsEmpsts) {
		this.dfSpsEmpsts = dfSpsEmpsts;
	}

	public String getDfSpsSmoking() {
		return this.dfSpsSmoking;
	}

	public void setDfSpsSmoking(String dfSpsSmoking) {
		this.dfSpsSmoking = dfSpsSmoking;
	}

	public String getDfSpsPersemail() {
		return this.dfSpsPersemail;
	}

	public void setDfSpsPersemail(String dfSpsPersemail) {
		this.dfSpsPersemail = dfSpsPersemail;
	}

	public String getDfSpsHp() {
		return this.dfSpsHp;
	}

	public void setDfSpsHp(String dfSpsHp) {
		this.dfSpsHp = dfSpsHp;
	}

	public String getDfSpsOffice() {
		return this.dfSpsOffice;
	}

	public void setDfSpsOffice(String dfSpsOffice) {
		this.dfSpsOffice = dfSpsOffice;
	}

	public String getDfSpsHome() {
		return this.dfSpsHome;
	}

	public void setDfSpsHome(String dfSpsHome) {
		this.dfSpsHome = dfSpsHome;
	}

	public String getDfSpsFax() {
		return this.dfSpsFax;
	}

	public void setDfSpsFax(String dfSpsFax) {
		this.dfSpsFax = dfSpsFax;
	}

	public String getDfSpsHomeaddr() {
		return this.dfSpsHomeaddr;
	}

	public void setDfSpsHomeaddr(String dfSpsHomeaddr) {
		this.dfSpsHomeaddr = dfSpsHomeaddr;
	}

	public String getDfSpsHomeaddr2() {
		return this.dfSpsHomeaddr2;
	}

	public void setDfSpsHomeaddr2(String dfSpsHomeaddr2) {
		this.dfSpsHomeaddr2 = dfSpsHomeaddr2;
	}

	public String getDfSpsHomepostalcode() {
		return this.dfSpsHomepostalcode;
	}

	public void setDfSpsHomepostalcode(String dfSpsHomepostalcode) {
		this.dfSpsHomepostalcode = dfSpsHomepostalcode;
	}

	public String getDfSpsHomecntry() {
		return this.dfSpsHomecntry;
	}

	public void setDfSpsHomecntry(String dfSpsHomecntry) {
		this.dfSpsHomecntry = dfSpsHomecntry;
	}

	public String getDfSpsRegmailaddrSame() {
		return this.dfSpsRegmailaddrSame;
	}

	public void setDfSpsRegmailaddrSame(String dfSpsRegmailaddrSame) {
		this.dfSpsRegmailaddrSame = dfSpsRegmailaddrSame;
	}

	public String getDfSpsRegaddrAsSelf() {
		return this.dfSpsRegaddrAsSelf;
	}

	public void setDfSpsRegaddrAsSelf(String dfSpsRegaddrAsSelf) {
		this.dfSpsRegaddrAsSelf = dfSpsRegaddrAsSelf;
	}

	public String getDfSpsMailaddrAsSelf() {
		return this.dfSpsMailaddrAsSelf;
	}

	public void setDfSpsMailaddrAsSelf(String dfSpsMailaddrAsSelf) {
		this.dfSpsMailaddrAsSelf = dfSpsMailaddrAsSelf;
	}

	public String getDfSpsMailaddr() {
		return this.dfSpsMailaddr;
	}

	public void setDfSpsMailaddr(String dfSpsMailaddr) {
		this.dfSpsMailaddr = dfSpsMailaddr;
	}

	public String getDfSpsMailaddr2() {
		return this.dfSpsMailaddr2;
	}

	public void setDfSpsMailaddr2(String dfSpsMailaddr2) {
		this.dfSpsMailaddr2 = dfSpsMailaddr2;
	}

	public String getDfSpsMailpostal() {
		return this.dfSpsMailpostal;
	}

	public void setDfSpsMailpostal(String dfSpsMailpostal) {
		this.dfSpsMailpostal = dfSpsMailpostal;
	}

	public String getDfSpsMailcntry() {
		return this.dfSpsMailcntry;
	}

	public void setDfSpsMailcntry(String dfSpsMailcntry) {
		this.dfSpsMailcntry = dfSpsMailcntry;
	}

	public String getDfSpsAddrreason() {
		return this.dfSpsAddrreason;
	}

	public void setDfSpsAddrreason(String dfSpsAddrreason) {
		this.dfSpsAddrreason = dfSpsAddrreason;
	}

	public String getDfSpsSrcfund() {
		return this.dfSpsSrcfund;
	}

	public void setDfSpsSrcfund(String dfSpsSrcfund) {
		this.dfSpsSrcfund = dfSpsSrcfund;
	}

	public Double getDfSpsAnnlincome() {
		return this.dfSpsAnnlincome;
	}

	public void setDfSpsAnnlincome(Double dfSpsAnnlincome) {
		this.dfSpsAnnlincome = dfSpsAnnlincome;
	}

	public String getDfSpsCompname() {
		return this.dfSpsCompname;
	}

	public void setDfSpsCompname(String dfSpsCompname) {
		this.dfSpsCompname = dfSpsCompname;
	}

	public String getDfSpsBusinatr() {
		return this.dfSpsBusinatr;
	}

	public void setDfSpsBusinatr(String dfSpsBusinatr) {
		this.dfSpsBusinatr = dfSpsBusinatr;
	}

	public String getDfSpsBusinatrDets() {
		return this.dfSpsBusinatrDets;
	}

	public void setDfSpsBusinatrDets(String dfSpsBusinatrDets) {
		this.dfSpsBusinatrDets = dfSpsBusinatrDets;
	}

	public String getDfSpsUsnotifyflg() {
		return this.dfSpsUsnotifyflg;
	}

	public void setDfSpsUsnotifyflg(String dfSpsUsnotifyflg) {
		this.dfSpsUsnotifyflg = dfSpsUsnotifyflg;
	}

	public String getDfSpsUspersonflg() {
		return this.dfSpsUspersonflg;
	}

	public void setDfSpsUspersonflg(String dfSpsUspersonflg) {
		this.dfSpsUspersonflg = dfSpsUspersonflg;
	}

	public String getDfSpsUstaxno() {
		return this.dfSpsUstaxno;
	}

	public void setDfSpsUstaxno(String dfSpsUstaxno) {
		this.dfSpsUstaxno = dfSpsUstaxno;
	}

	public String getDfSpsRescountry() {
		return this.dfSpsRescountry;
	}

	public void setDfSpsRescountry(String dfSpsRescountry) {
		this.dfSpsRescountry = dfSpsRescountry;
	}

	public Date getDfCreatedDatetime() {
		return this.dfCreatedDatetime;
	}

	public void setDfCreatedDatetime(Date dfCreatedDatetime) {
		this.dfCreatedDatetime = dfCreatedDatetime;
	}

	public String getDfCreatedBy() {
		return this.dfCreatedBy;
	}

	public void setDfCreatedBy(String dfCreatedBy) {
		this.dfCreatedBy = dfCreatedBy;
	}

	public Date getDfCreatedDate() {
		return this.dfCreatedDate;
	}

	public void setDfCreatedDate(Date dfCreatedDate) {
		this.dfCreatedDate = dfCreatedDate;
	}

	public String getDfModifiedBy() {
		return this.dfModifiedBy;
	}

	public void setDfModifiedBy(String dfModifiedBy) {
		this.dfModifiedBy = dfModifiedBy;
	}

	public Date getDfModifiedDate() {
		return this.dfModifiedDate;
	}

	public void setDfModifiedDate(Date dfModifiedDate) {
		this.dfModifiedDate = dfModifiedDate;
	}

	public Set<FnaLifeinsuranceNominees> getFnaLifeinsuranceNomineeses() {
		return this.fnaLifeinsuranceNomineeses;
	}

	public void setFnaLifeinsuranceNomineeses(
			Set<FnaLifeinsuranceNominees> fnaLifeinsuranceNomineeses) {
		this.fnaLifeinsuranceNomineeses = fnaLifeinsuranceNomineeses;
	}

	public Set<FnaAssetCashdets> getFnaAssetCashdetses() {
		return this.fnaAssetCashdetses;
	}

	public void setFnaAssetCashdetses(Set<FnaAssetCashdets> fnaAssetCashdetses) {
		this.fnaAssetCashdetses = fnaAssetCashdetses;
	}

	public Set<FnaLifeinsuranceCoverages> getFnaLifeinsuranceCoverageses() {
		return this.fnaLifeinsuranceCoverageses;
	}

	public void setFnaLifeinsuranceCoverageses(
			Set<FnaLifeinsuranceCoverages> fnaLifeinsuranceCoverageses) {
		this.fnaLifeinsuranceCoverageses = fnaLifeinsuranceCoverageses;
	}

	public Set<FnaSummaryAnalysis> getFnaSummaryAnalysises() {
		return this.fnaSummaryAnalysises;
	}

	public void setFnaSummaryAnalysises(
			Set<FnaSummaryAnalysis> fnaSummaryAnalysises) {
		this.fnaSummaryAnalysises = fnaSummaryAnalysises;
	}

	public Set<FnaCpfMonthcontDets> getFnaCpfMonthcontDetses() {
		return this.fnaCpfMonthcontDetses;
	}

	public void setFnaCpfMonthcontDetses(
			Set<FnaCpfMonthcontDets> fnaCpfMonthcontDetses) {
		this.fnaCpfMonthcontDetses = fnaCpfMonthcontDetses;
	}

	public Set<FnaRetireplanIncome> getFnaRetireplanIncomes() {
		return this.fnaRetireplanIncomes;
	}

	public void setFnaRetireplanIncomes(
			Set<FnaRetireplanIncome> fnaRetireplanIncomes) {
		this.fnaRetireplanIncomes = fnaRetireplanIncomes;
	}

	public Set<FnaLifeinsuranceDets> getFnaLifeinsuranceDetses() {
		return this.fnaLifeinsuranceDetses;
	}

	public void setFnaLifeinsuranceDetses(
			Set<FnaLifeinsuranceDets> fnaLifeinsuranceDetses) {
		this.fnaLifeinsuranceDetses = fnaLifeinsuranceDetses;
	}

	public Set<FnaContingencyDets> getFnaContingencyDetses() {
		return this.fnaContingencyDetses;
	}

	public void setFnaContingencyDetses(
			Set<FnaContingencyDets> fnaContingencyDetses) {
		this.fnaContingencyDetses = fnaContingencyDetses;
	}

	public Set<FnaAssetOtherdets> getFnaAssetOtherdetses() {
		return this.fnaAssetOtherdetses;
	}

	public void setFnaAssetOtherdetses(
			Set<FnaAssetOtherdets> fnaAssetOtherdetses) {
		this.fnaAssetOtherdetses = fnaAssetOtherdetses;
	}

	public Set<FnaOtherAssetdets> getFnaOtherAssetdetses() {
		return this.fnaOtherAssetdetses;
	}

	public void setFnaOtherAssetdetses(
			Set<FnaOtherAssetdets> fnaOtherAssetdetses) {
		this.fnaOtherAssetdetses = fnaOtherAssetdetses;
	}
	
	public Set<FnaDependantDets> getFnaDependantDetses() {
		return this.fnaDependantDetses;
	}

	public void setFnaDependantDetses(Set<FnaDependantDets> fnaDependantDetses) {
		this.fnaDependantDetses = fnaDependantDetses;
	}

	public Set<FnaCpfDeductions> getFnaCpfDeductionses() {
		return this.fnaCpfDeductionses;
	}

	public void setFnaCpfDeductionses(Set<FnaCpfDeductions> fnaCpfDeductionses) {
		this.fnaCpfDeductionses = fnaCpfDeductionses;
	}

	public Set<FnaFingoalsconcern> getFnaFingoalsconcerns() {
		return this.fnaFingoalsconcerns;
	}

	public void setFnaFingoalsconcerns(
			Set<FnaFingoalsconcern> fnaFingoalsconcerns) {
		this.fnaFingoalsconcerns = fnaFingoalsconcerns;
	}

	public Set<FnaOthareaconcern> getFnaOthareaconcerns() {
		return this.fnaOthareaconcerns;
	}

	public void setFnaOthareaconcerns(Set<FnaOthareaconcern> fnaOthareaconcerns) {
		this.fnaOthareaconcerns = fnaOthareaconcerns;
	}

	public Set<FnaAssetBusiandpersdets> getFnaAssetBusiandpersdetses() {
		return this.fnaAssetBusiandpersdetses;
	}

	public void setFnaAssetBusiandpersdetses(
			Set<FnaAssetBusiandpersdets> fnaAssetBusiandpersdetses) {
		this.fnaAssetBusiandpersdetses = fnaAssetBusiandpersdetses;
	}

	public Set<FnaInputinvestmentsDets> getFnaInputinvestmentsDetses() {
		return this.fnaInputinvestmentsDetses;
	}

	public void setFnaInputinvestmentsDetses(
			Set<FnaInputinvestmentsDets> fnaInputinvestmentsDetses) {
		this.fnaInputinvestmentsDetses = fnaInputinvestmentsDetses;
	}

	public Set<FnaSavingsinvDets> getFnaSavingsinvDetses() {
		return this.fnaSavingsinvDetses;
	}

	public void setFnaSavingsinvDetses(
			Set<FnaSavingsinvDets> fnaSavingsinvDetses) {
		this.fnaSavingsinvDetses = fnaSavingsinvDetses;
	}

	public Set<FnaCurassDets> getFnaCurassDetses() {
		return this.fnaCurassDetses;
	}

	public void setFnaCurassDetses(Set<FnaCurassDets> fnaCurassDetses) {
		this.fnaCurassDetses = fnaCurassDetses;
	}

	public Set<FnaLifeinsuranceMvRet> getFnaLifeinsuranceMvRets() {
		return this.fnaLifeinsuranceMvRets;
	}

	public void setFnaLifeinsuranceMvRets(
			Set<FnaLifeinsuranceMvRet> fnaLifeinsuranceMvRets) {
		this.fnaLifeinsuranceMvRets = fnaLifeinsuranceMvRets;
	}

	public Set<FnaLifeinsuranceDisablebenfs> getFnaLifeinsuranceDisablebenfses() {
		return this.fnaLifeinsuranceDisablebenfses;
	}

	public void setFnaLifeinsuranceDisablebenfses(
			Set<FnaLifeinsuranceDisablebenfs> fnaLifeinsuranceDisablebenfses) {
		this.fnaLifeinsuranceDisablebenfses = fnaLifeinsuranceDisablebenfses;
	}

	public Set<FnaPropownDets> getFnaPropownDetses() {
		return this.fnaPropownDetses;
	}

	public void setFnaPropownDetses(Set<FnaPropownDets> fnaPropownDetses) {
		this.fnaPropownDetses = fnaPropownDetses;
	}

	public Set<FnaCpfBalanceDets> getFnaCpfBalanceDetses() {
		return this.fnaCpfBalanceDetses;
	}

	public void setFnaCpfBalanceDetses(
			Set<FnaCpfBalanceDets> fnaCpfBalanceDetses) {
		this.fnaCpfBalanceDetses = fnaCpfBalanceDetses;
	}

	public Set<FnaRecomReasons> getFnaRecomReasonses() {
		return this.fnaRecomReasonses;
	}

	public void setFnaRecomReasonses(Set<FnaRecomReasons> fnaRecomReasonses) {
		this.fnaRecomReasonses = fnaRecomReasonses;
	}

	public Set<FnaLifeinsuranceBasicriders> getFnaLifeinsuranceBasicriderses() {
		return this.fnaLifeinsuranceBasicriderses;
	}

	public void setFnaLifeinsuranceBasicriderses(
			Set<FnaLifeinsuranceBasicriders> fnaLifeinsuranceBasicriderses) {
		this.fnaLifeinsuranceBasicriderses = fnaLifeinsuranceBasicriderses;
	}

	public Set<FnaVehicleownDets> getFnaVehicleownDetses() {
		return this.fnaVehicleownDetses;
	}

	public void setFnaVehicleownDetses(
			Set<FnaVehicleownDets> fnaVehicleownDetses) {
		this.fnaVehicleownDetses = fnaVehicleownDetses;
	}

	public Set<FnaEstatePlan> getFnaEstatePlans() {
		return this.fnaEstatePlans;
	}

	public void setFnaEstatePlans(Set<FnaEstatePlan> fnaEstatePlans) {
		this.fnaEstatePlans = fnaEstatePlans;
	}

	public Set<FnaRiskprefDets> getFnaRiskprefDetses() {
		return this.fnaRiskprefDetses;
	}

	public void setFnaRiskprefDetses(Set<FnaRiskprefDets> fnaRiskprefDetses) {
		this.fnaRiskprefDetses = fnaRiskprefDetses;
	}

	public Set<FnaHealthinsInfo> getFnaHealthinsInfos() {
		return this.fnaHealthinsInfos;
	}

	public void setFnaHealthinsInfos(Set<FnaHealthinsInfo> fnaHealthinsInfos) {
		this.fnaHealthinsInfos = fnaHealthinsInfos;
	}

	public Set<FnaAdvDeclare> getFnaAdvDeclares() {
		return this.fnaAdvDeclares;
	}

	public void setFnaAdvDeclares(Set<FnaAdvDeclare> fnaAdvDeclares) {
		this.fnaAdvDeclares = fnaAdvDeclares;
	}

	public Set<FnaCashAtBank> getFnaCashAtBanks() {
		return this.fnaCashAtBanks;
	}

	public void setFnaCashAtBanks(Set<FnaCashAtBank> fnaCashAtBanks) {
		this.fnaCashAtBanks = fnaCashAtBanks;
	}

	public Set<FnaLifeinsuranceChildedc> getFnaLifeinsuranceChildedcs() {
		return this.fnaLifeinsuranceChildedcs;
	}

	public void setFnaLifeinsuranceChildedcs(
			Set<FnaLifeinsuranceChildedc> fnaLifeinsuranceChildedcs) {
		this.fnaLifeinsuranceChildedcs = fnaLifeinsuranceChildedcs;
	}

	public Set<FnaExpenditureDets> getFnaExpenditureDetses() {
		return this.fnaExpenditureDetses;
	}

	public void setFnaExpenditureDetses(
			Set<FnaExpenditureDets> fnaExpenditureDetses) {
		this.fnaExpenditureDetses = fnaExpenditureDetses;
	}

	public Set<FnaPersprio> getFnaPersprios() {
		return this.fnaPersprios;
	}

	public void setFnaPersprios(Set<FnaPersprio> fnaPersprios) {
		this.fnaPersprios = fnaPersprios;
	}

	public Set<FnaFinLiability> getFnaFinLiabilities() {
		return this.fnaFinLiabilities;
	}

	public void setFnaFinLiabilities(Set<FnaFinLiability> fnaFinLiabilities) {
		this.fnaFinLiabilities = fnaFinLiabilities;
	}

	public Set<FnaSwtchrepPlanDet> getFnaSwtchrepPlanDets() {
		return this.fnaSwtchrepPlanDets;
	}

	public void setFnaSwtchrepPlanDets(
			Set<FnaSwtchrepPlanDet> fnaSwtchrepPlanDets) {
		this.fnaSwtchrepPlanDets = fnaSwtchrepPlanDets;
	}

	public Set<FnaSrcofincome> getFnaSrcofincomes() {
		return this.fnaSrcofincomes;
	}

	public void setFnaSrcofincomes(Set<FnaSrcofincome> fnaSrcofincomes) {
		this.fnaSrcofincomes = fnaSrcofincomes;
	}

	public Set<FnaRecomPrdtplanDet> getFnaRecomPrdtplanDets() {
		return this.fnaRecomPrdtplanDets;
	}

	public void setFnaRecomPrdtplanDets(
			Set<FnaRecomPrdtplanDet> fnaRecomPrdtplanDets) {
		this.fnaRecomPrdtplanDets = fnaRecomPrdtplanDets;
	}

	public Set<FnaRecomFundDet> getFnaRecomFundDets() {
		return this.fnaRecomFundDets;
	}

	public void setFnaRecomFundDets(Set<FnaRecomFundDet> fnaRecomFundDets) {
		this.fnaRecomFundDets = fnaRecomFundDets;
	}

	public Set<FnaSwtchrepFundDet> getFnaSwtchrepFundDets() {
		return this.fnaSwtchrepFundDets;
	}

	public void setFnaSwtchrepFundDets(
			Set<FnaSwtchrepFundDet> fnaSwtchrepFundDets) {
		this.fnaSwtchrepFundDets = fnaSwtchrepFundDets;
	}

	public Set<FnaRetireplanDets> getFnaRetireplanDetses() {
		return this.fnaRetireplanDetses;
	}

	public void setFnaRetireplanDetses(
			Set<FnaRetireplanDets> fnaRetireplanDetses) {
		this.fnaRetireplanDetses = fnaRetireplanDetses;
	}

	public Set<FnaApptypes> getFnaApptypeses() {
		return this.fnaApptypeses;
	}

	public void setFnaApptypeses(Set<FnaApptypes> fnaApptypeses) {
		this.fnaApptypeses = fnaApptypeses;
	}

	public Set<FnaChilddetails> getFnaChilddetailses() {
		return this.fnaChilddetailses;
	}

	public void setFnaChilddetailses(Set<FnaChilddetails> fnaChilddetailses) {
		this.fnaChilddetailses = fnaChilddetailses;
	}

	public Set<FnaInvsetmentSummary> getFnaInvsetmentSummaries() {
		return this.fnaInvsetmentSummaries;
	}

	public void setFnaInvsetmentSummaries(
			Set<FnaInvsetmentSummary> fnaInvsetmentSummaries) {
		this.fnaInvsetmentSummaries = fnaInvsetmentSummaries;
	}

}
