package com.fipa.dto;

// Generated May 17, 2018 11:20:36 AM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * FnaSrcofincome generated by hbm2java
 */
public class FnaSrcofincome implements java.io.Serializable {

	private String incsrcId;//
	private FnaSelfspouseDets fnaSelfspouseDets;
	private Double incsrcSelfEmpMonthly;//
	private Double incsrcSelfEmpIncr;//
	private Double incsrcSelfEmpPeriod;//
	private Double incsrcSpsEmpMonthly;//
	private Double incsrcSpsEmpIncr;//
	private Double incsrcSpsEmpPeriod;//
	private Double incsrcJointEmpMonthly;//
	private Double incsrcJointEmpIncr;//
	private Double incsrcJointEmpPeriod;//
	private Double incsrcSelfEmpAddlwage;//
	private Double incsrcSpsEmpAddlwage;//
	private Double incsrcSelfNempMonthly;//
	private Double incsrcSelfNempIncr;//
	private Double incsrcSelfNempPeriod;//
	private Double incsrcSpsNempMonthly;//
	private Double incsrcSpsNempIncr;//
	private Double incsrcSpsNempPeriod;//
	private Double incsrcJointNempMonthly;//
	private Double incsrcJointNempIncr;//
	private Double incsrcJointNempPeriod;//
	private Double incsrcSelfNempRentamt;//
	private Double incsrcSelfNempRentincr;//
	private Double incsrcSelfNempRentperd;//
	private Double incsrcSpsNempRentamt;//
	private Double incsrcSpsNempRentincr;//
	private Double incsrcSpsNempRentperd;//
	private Double incsrcJointNempRentamt;//
	private Double incsrcJointNempRentincr;//
	private Double incsrcJointNempRentperd;//
	private Double incsrcSelfNempDivdamt;//
	private Double incsrcSelfNempDivdincr;//
	private Double incsrcSelfNempDivdperd;//
	private Double incsrcSpsNempDivdamt;//
	private Double incsrcSpsNempDivdincr;//
	private Double incsrcSpsNempDivdperd;//
	private Double incsrcJointNempDivdamt;//
	private Double incsrcJointNempDivdincr;//
	private Double incsrcJointNempDivdperd;//
	private Double incsrcSelfNempOthamt;//
	private Double incsrcSelfNempOthincr;//
	private Double incsrcSelfNempOthperd;//
	private Double incsrcSpsNempOthamt;//
	private Double incsrcSpsNempOthincr;//
	private Double incsrcSpsNempOthperd;//
	private Double incsrcJointNempOthamt;//
	private Double incsrcJointNempOthincr;//
	private Double incsrcJointNempOthperd;//
	private Double insrcSelfTotannl;//
	private Double insrcSelfTotannlincr;//
	private Double insrcSelfTotannlperd;//
	private Double insrcSpsTotannl;//
	private Double insrcSpsTotannlincr;//
	private Double insrcSpsTotannlperd;//
	private Double insrcJointTotannl;//
	private Double insrcJointTotannlincr;//
	private Double insrcJointTotannlperd;//
	private Double incsrcSelfAbility;//
	private Double incsrcSpsAbility;//
	private Double incsrcJointAbility;//
	private Double incsrcSelfAbilityincr;//
	private Double incsrcSpsAbilityincr;//
	private Double incsrcJointAbilityincr;//
	private String incsrcRemarks;//
	private Double insrcSelfAnnlBusiincome;
	private Double insrcSpsAnnlBusiincome;
	private Double insrcSelfAnnlOthincome;
	private Double insrcSpsAnnlOthincome;
	private Double insrcSelfNempOthincome;
	private Double insrcSpsNempOthincome;
	private String incsrcCreatedBy;
	private Date incsrcCreatedDate;
	private String incsrcModifiedBy;
	private Date incsrcModifiedDate;

	public FnaSrcofincome() {
	}

	public FnaSrcofincome(String incsrcId) {
		this.incsrcId = incsrcId;
	}

	public FnaSrcofincome(String incsrcId, FnaSelfspouseDets fnaSelfspouseDets,
			Double incsrcSelfEmpMonthly, Double incsrcSelfEmpIncr,
			Double incsrcSelfEmpPeriod, Double incsrcSpsEmpMonthly,
			Double incsrcSpsEmpIncr, Double incsrcSpsEmpPeriod,
			Double incsrcJointEmpMonthly, Double incsrcJointEmpIncr,
			Double incsrcJointEmpPeriod, Double incsrcSelfEmpAddlwage,
			Double incsrcSpsEmpAddlwage, Double incsrcSelfNempMonthly,
			Double incsrcSelfNempIncr, Double incsrcSelfNempPeriod,
			Double incsrcSpsNempMonthly, Double incsrcSpsNempIncr,
			Double incsrcSpsNempPeriod, Double incsrcJointNempMonthly,
			Double incsrcJointNempIncr, Double incsrcJointNempPeriod,
			Double incsrcSelfNempRentamt, Double incsrcSelfNempRentincr,
			Double incsrcSelfNempRentperd, Double incsrcSpsNempRentamt,
			Double incsrcSpsNempRentincr, Double incsrcSpsNempRentperd,
			Double incsrcJointNempRentamt, Double incsrcJointNempRentincr,
			Double incsrcJointNempRentperd, Double incsrcSelfNempDivdamt,
			Double incsrcSelfNempDivdincr, Double incsrcSelfNempDivdperd,
			Double incsrcSpsNempDivdamt, Double incsrcSpsNempDivdincr,
			Double incsrcSpsNempDivdperd, Double incsrcJointNempDivdamt,
			Double incsrcJointNempDivdincr, Double incsrcJointNempDivdperd,
			Double incsrcSelfNempOthamt, Double incsrcSelfNempOthincr,
			Double incsrcSelfNempOthperd, Double incsrcSpsNempOthamt,
			Double incsrcSpsNempOthincr, Double incsrcSpsNempOthperd,
			Double incsrcJointNempOthamt, Double incsrcJointNempOthincr,
			Double incsrcJointNempOthperd, Double insrcSelfTotannl,
			Double insrcSelfTotannlincr, Double insrcSelfTotannlperd,
			Double insrcSpsTotannl, Double insrcSpsTotannlincr,
			Double insrcSpsTotannlperd, Double insrcJointTotannl,
			Double insrcJointTotannlincr, Double insrcJointTotannlperd,
			Double incsrcSelfAbility, Double incsrcSpsAbility,
			Double incsrcJointAbility, Double incsrcSelfAbilityincr,
			Double incsrcSpsAbilityincr, Double incsrcJointAbilityincr,
			String incsrcRemarks, Double insrcSelfAnnlBusiincome,
			Double insrcSpsAnnlBusiincome, Double insrcSelfAnnlOthincome,
			Double insrcSpsAnnlOthincome, Double insrcSelfNempOthincome,
			Double insrcSpsNempOthincome, String incsrcCreatedBy,
			Date incsrcCreatedDate, String incsrcModifiedBy,
			Date incsrcModifiedDate) {
		this.incsrcId = incsrcId;
		this.fnaSelfspouseDets = fnaSelfspouseDets;
		this.incsrcSelfEmpMonthly = incsrcSelfEmpMonthly;
		this.incsrcSelfEmpIncr = incsrcSelfEmpIncr;
		this.incsrcSelfEmpPeriod = incsrcSelfEmpPeriod;
		this.incsrcSpsEmpMonthly = incsrcSpsEmpMonthly;
		this.incsrcSpsEmpIncr = incsrcSpsEmpIncr;
		this.incsrcSpsEmpPeriod = incsrcSpsEmpPeriod;
		this.incsrcJointEmpMonthly = incsrcJointEmpMonthly;
		this.incsrcJointEmpIncr = incsrcJointEmpIncr;
		this.incsrcJointEmpPeriod = incsrcJointEmpPeriod;
		this.incsrcSelfEmpAddlwage = incsrcSelfEmpAddlwage;
		this.incsrcSpsEmpAddlwage = incsrcSpsEmpAddlwage;
		this.incsrcSelfNempMonthly = incsrcSelfNempMonthly;
		this.incsrcSelfNempIncr = incsrcSelfNempIncr;
		this.incsrcSelfNempPeriod = incsrcSelfNempPeriod;
		this.incsrcSpsNempMonthly = incsrcSpsNempMonthly;
		this.incsrcSpsNempIncr = incsrcSpsNempIncr;
		this.incsrcSpsNempPeriod = incsrcSpsNempPeriod;
		this.incsrcJointNempMonthly = incsrcJointNempMonthly;
		this.incsrcJointNempIncr = incsrcJointNempIncr;
		this.incsrcJointNempPeriod = incsrcJointNempPeriod;
		this.incsrcSelfNempRentamt = incsrcSelfNempRentamt;
		this.incsrcSelfNempRentincr = incsrcSelfNempRentincr;
		this.incsrcSelfNempRentperd = incsrcSelfNempRentperd;
		this.incsrcSpsNempRentamt = incsrcSpsNempRentamt;
		this.incsrcSpsNempRentincr = incsrcSpsNempRentincr;
		this.incsrcSpsNempRentperd = incsrcSpsNempRentperd;
		this.incsrcJointNempRentamt = incsrcJointNempRentamt;
		this.incsrcJointNempRentincr = incsrcJointNempRentincr;
		this.incsrcJointNempRentperd = incsrcJointNempRentperd;
		this.incsrcSelfNempDivdamt = incsrcSelfNempDivdamt;
		this.incsrcSelfNempDivdincr = incsrcSelfNempDivdincr;
		this.incsrcSelfNempDivdperd = incsrcSelfNempDivdperd;
		this.incsrcSpsNempDivdamt = incsrcSpsNempDivdamt;
		this.incsrcSpsNempDivdincr = incsrcSpsNempDivdincr;
		this.incsrcSpsNempDivdperd = incsrcSpsNempDivdperd;
		this.incsrcJointNempDivdamt = incsrcJointNempDivdamt;
		this.incsrcJointNempDivdincr = incsrcJointNempDivdincr;
		this.incsrcJointNempDivdperd = incsrcJointNempDivdperd;
		this.incsrcSelfNempOthamt = incsrcSelfNempOthamt;
		this.incsrcSelfNempOthincr = incsrcSelfNempOthincr;
		this.incsrcSelfNempOthperd = incsrcSelfNempOthperd;
		this.incsrcSpsNempOthamt = incsrcSpsNempOthamt;
		this.incsrcSpsNempOthincr = incsrcSpsNempOthincr;
		this.incsrcSpsNempOthperd = incsrcSpsNempOthperd;
		this.incsrcJointNempOthamt = incsrcJointNempOthamt;
		this.incsrcJointNempOthincr = incsrcJointNempOthincr;
		this.incsrcJointNempOthperd = incsrcJointNempOthperd;
		this.insrcSelfTotannl = insrcSelfTotannl;
		this.insrcSelfTotannlincr = insrcSelfTotannlincr;
		this.insrcSelfTotannlperd = insrcSelfTotannlperd;
		this.insrcSpsTotannl = insrcSpsTotannl;
		this.insrcSpsTotannlincr = insrcSpsTotannlincr;
		this.insrcSpsTotannlperd = insrcSpsTotannlperd;
		this.insrcJointTotannl = insrcJointTotannl;
		this.insrcJointTotannlincr = insrcJointTotannlincr;
		this.insrcJointTotannlperd = insrcJointTotannlperd;
		this.incsrcSelfAbility = incsrcSelfAbility;
		this.incsrcSpsAbility = incsrcSpsAbility;
		this.incsrcJointAbility = incsrcJointAbility;
		this.incsrcSelfAbilityincr = incsrcSelfAbilityincr;
		this.incsrcSpsAbilityincr = incsrcSpsAbilityincr;
		this.incsrcJointAbilityincr = incsrcJointAbilityincr;
		this.incsrcRemarks = incsrcRemarks;
		this.insrcSelfAnnlBusiincome = insrcSelfAnnlBusiincome;
		this.insrcSpsAnnlBusiincome = insrcSpsAnnlBusiincome;
		this.insrcSelfAnnlOthincome = insrcSelfAnnlOthincome;
		this.insrcSpsAnnlOthincome = insrcSpsAnnlOthincome;
		this.insrcSelfNempOthincome = insrcSelfNempOthincome;
		this.insrcSpsNempOthincome = insrcSpsNempOthincome;
		this.incsrcCreatedBy = incsrcCreatedBy;
		this.incsrcCreatedDate = incsrcCreatedDate;
		this.incsrcModifiedBy = incsrcModifiedBy;
		this.incsrcModifiedDate = incsrcModifiedDate;
	}

	public String getIncsrcId() {
		return this.incsrcId;
	}

	public void setIncsrcId(String incsrcId) {
		this.incsrcId = incsrcId;
	}

	public FnaSelfspouseDets getFnaSelfspouseDets() {
		return this.fnaSelfspouseDets;
	}

	public void setFnaSelfspouseDets(FnaSelfspouseDets fnaSelfspouseDets) {
		this.fnaSelfspouseDets = fnaSelfspouseDets;
	}

	public Double getIncsrcSelfEmpMonthly() {
		return this.incsrcSelfEmpMonthly;
	}

	public void setIncsrcSelfEmpMonthly(Double incsrcSelfEmpMonthly) {
		this.incsrcSelfEmpMonthly = incsrcSelfEmpMonthly;
	}

	public Double getIncsrcSelfEmpIncr() {
		return this.incsrcSelfEmpIncr;
	}

	public void setIncsrcSelfEmpIncr(Double incsrcSelfEmpIncr) {
		this.incsrcSelfEmpIncr = incsrcSelfEmpIncr;
	}

	public Double getIncsrcSelfEmpPeriod() {
		return this.incsrcSelfEmpPeriod;
	}

	public void setIncsrcSelfEmpPeriod(Double incsrcSelfEmpPeriod) {
		this.incsrcSelfEmpPeriod = incsrcSelfEmpPeriod;
	}

	public Double getIncsrcSpsEmpMonthly() {
		return this.incsrcSpsEmpMonthly;
	}

	public void setIncsrcSpsEmpMonthly(Double incsrcSpsEmpMonthly) {
		this.incsrcSpsEmpMonthly = incsrcSpsEmpMonthly;
	}

	public Double getIncsrcSpsEmpIncr() {
		return this.incsrcSpsEmpIncr;
	}

	public void setIncsrcSpsEmpIncr(Double incsrcSpsEmpIncr) {
		this.incsrcSpsEmpIncr = incsrcSpsEmpIncr;
	}

	public Double getIncsrcSpsEmpPeriod() {
		return this.incsrcSpsEmpPeriod;
	}

	public void setIncsrcSpsEmpPeriod(Double incsrcSpsEmpPeriod) {
		this.incsrcSpsEmpPeriod = incsrcSpsEmpPeriod;
	}

	public Double getIncsrcJointEmpMonthly() {
		return this.incsrcJointEmpMonthly;
	}

	public void setIncsrcJointEmpMonthly(Double incsrcJointEmpMonthly) {
		this.incsrcJointEmpMonthly = incsrcJointEmpMonthly;
	}

	public Double getIncsrcJointEmpIncr() {
		return this.incsrcJointEmpIncr;
	}

	public void setIncsrcJointEmpIncr(Double incsrcJointEmpIncr) {
		this.incsrcJointEmpIncr = incsrcJointEmpIncr;
	}

	public Double getIncsrcJointEmpPeriod() {
		return this.incsrcJointEmpPeriod;
	}

	public void setIncsrcJointEmpPeriod(Double incsrcJointEmpPeriod) {
		this.incsrcJointEmpPeriod = incsrcJointEmpPeriod;
	}

	public Double getIncsrcSelfEmpAddlwage() {
		return this.incsrcSelfEmpAddlwage;
	}

	public void setIncsrcSelfEmpAddlwage(Double incsrcSelfEmpAddlwage) {
		this.incsrcSelfEmpAddlwage = incsrcSelfEmpAddlwage;
	}

	public Double getIncsrcSpsEmpAddlwage() {
		return this.incsrcSpsEmpAddlwage;
	}

	public void setIncsrcSpsEmpAddlwage(Double incsrcSpsEmpAddlwage) {
		this.incsrcSpsEmpAddlwage = incsrcSpsEmpAddlwage;
	}

	public Double getIncsrcSelfNempMonthly() {
		return this.incsrcSelfNempMonthly;
	}

	public void setIncsrcSelfNempMonthly(Double incsrcSelfNempMonthly) {
		this.incsrcSelfNempMonthly = incsrcSelfNempMonthly;
	}

	public Double getIncsrcSelfNempIncr() {
		return this.incsrcSelfNempIncr;
	}

	public void setIncsrcSelfNempIncr(Double incsrcSelfNempIncr) {
		this.incsrcSelfNempIncr = incsrcSelfNempIncr;
	}

	public Double getIncsrcSelfNempPeriod() {
		return this.incsrcSelfNempPeriod;
	}

	public void setIncsrcSelfNempPeriod(Double incsrcSelfNempPeriod) {
		this.incsrcSelfNempPeriod = incsrcSelfNempPeriod;
	}

	public Double getIncsrcSpsNempMonthly() {
		return this.incsrcSpsNempMonthly;
	}

	public void setIncsrcSpsNempMonthly(Double incsrcSpsNempMonthly) {
		this.incsrcSpsNempMonthly = incsrcSpsNempMonthly;
	}

	public Double getIncsrcSpsNempIncr() {
		return this.incsrcSpsNempIncr;
	}

	public void setIncsrcSpsNempIncr(Double incsrcSpsNempIncr) {
		this.incsrcSpsNempIncr = incsrcSpsNempIncr;
	}

	public Double getIncsrcSpsNempPeriod() {
		return this.incsrcSpsNempPeriod;
	}

	public void setIncsrcSpsNempPeriod(Double incsrcSpsNempPeriod) {
		this.incsrcSpsNempPeriod = incsrcSpsNempPeriod;
	}

	public Double getIncsrcJointNempMonthly() {
		return this.incsrcJointNempMonthly;
	}

	public void setIncsrcJointNempMonthly(Double incsrcJointNempMonthly) {
		this.incsrcJointNempMonthly = incsrcJointNempMonthly;
	}

	public Double getIncsrcJointNempIncr() {
		return this.incsrcJointNempIncr;
	}

	public void setIncsrcJointNempIncr(Double incsrcJointNempIncr) {
		this.incsrcJointNempIncr = incsrcJointNempIncr;
	}

	public Double getIncsrcJointNempPeriod() {
		return this.incsrcJointNempPeriod;
	}

	public void setIncsrcJointNempPeriod(Double incsrcJointNempPeriod) {
		this.incsrcJointNempPeriod = incsrcJointNempPeriod;
	}

	public Double getIncsrcSelfNempRentamt() {
		return this.incsrcSelfNempRentamt;
	}

	public void setIncsrcSelfNempRentamt(Double incsrcSelfNempRentamt) {
		this.incsrcSelfNempRentamt = incsrcSelfNempRentamt;
	}

	public Double getIncsrcSelfNempRentincr() {
		return this.incsrcSelfNempRentincr;
	}

	public void setIncsrcSelfNempRentincr(Double incsrcSelfNempRentincr) {
		this.incsrcSelfNempRentincr = incsrcSelfNempRentincr;
	}

	public Double getIncsrcSelfNempRentperd() {
		return this.incsrcSelfNempRentperd;
	}

	public void setIncsrcSelfNempRentperd(Double incsrcSelfNempRentperd) {
		this.incsrcSelfNempRentperd = incsrcSelfNempRentperd;
	}

	public Double getIncsrcSpsNempRentamt() {
		return this.incsrcSpsNempRentamt;
	}

	public void setIncsrcSpsNempRentamt(Double incsrcSpsNempRentamt) {
		this.incsrcSpsNempRentamt = incsrcSpsNempRentamt;
	}

	public Double getIncsrcSpsNempRentincr() {
		return this.incsrcSpsNempRentincr;
	}

	public void setIncsrcSpsNempRentincr(Double incsrcSpsNempRentincr) {
		this.incsrcSpsNempRentincr = incsrcSpsNempRentincr;
	}

	public Double getIncsrcSpsNempRentperd() {
		return this.incsrcSpsNempRentperd;
	}

	public void setIncsrcSpsNempRentperd(Double incsrcSpsNempRentperd) {
		this.incsrcSpsNempRentperd = incsrcSpsNempRentperd;
	}

	public Double getIncsrcJointNempRentamt() {
		return this.incsrcJointNempRentamt;
	}

	public void setIncsrcJointNempRentamt(Double incsrcJointNempRentamt) {
		this.incsrcJointNempRentamt = incsrcJointNempRentamt;
	}

	public Double getIncsrcJointNempRentincr() {
		return this.incsrcJointNempRentincr;
	}

	public void setIncsrcJointNempRentincr(Double incsrcJointNempRentincr) {
		this.incsrcJointNempRentincr = incsrcJointNempRentincr;
	}

	public Double getIncsrcJointNempRentperd() {
		return this.incsrcJointNempRentperd;
	}

	public void setIncsrcJointNempRentperd(Double incsrcJointNempRentperd) {
		this.incsrcJointNempRentperd = incsrcJointNempRentperd;
	}

	public Double getIncsrcSelfNempDivdamt() {
		return this.incsrcSelfNempDivdamt;
	}

	public void setIncsrcSelfNempDivdamt(Double incsrcSelfNempDivdamt) {
		this.incsrcSelfNempDivdamt = incsrcSelfNempDivdamt;
	}

	public Double getIncsrcSelfNempDivdincr() {
		return this.incsrcSelfNempDivdincr;
	}

	public void setIncsrcSelfNempDivdincr(Double incsrcSelfNempDivdincr) {
		this.incsrcSelfNempDivdincr = incsrcSelfNempDivdincr;
	}

	public Double getIncsrcSelfNempDivdperd() {
		return this.incsrcSelfNempDivdperd;
	}

	public void setIncsrcSelfNempDivdperd(Double incsrcSelfNempDivdperd) {
		this.incsrcSelfNempDivdperd = incsrcSelfNempDivdperd;
	}

	public Double getIncsrcSpsNempDivdamt() {
		return this.incsrcSpsNempDivdamt;
	}

	public void setIncsrcSpsNempDivdamt(Double incsrcSpsNempDivdamt) {
		this.incsrcSpsNempDivdamt = incsrcSpsNempDivdamt;
	}

	public Double getIncsrcSpsNempDivdincr() {
		return this.incsrcSpsNempDivdincr;
	}

	public void setIncsrcSpsNempDivdincr(Double incsrcSpsNempDivdincr) {
		this.incsrcSpsNempDivdincr = incsrcSpsNempDivdincr;
	}

	public Double getIncsrcSpsNempDivdperd() {
		return this.incsrcSpsNempDivdperd;
	}

	public void setIncsrcSpsNempDivdperd(Double incsrcSpsNempDivdperd) {
		this.incsrcSpsNempDivdperd = incsrcSpsNempDivdperd;
	}

	public Double getIncsrcJointNempDivdamt() {
		return this.incsrcJointNempDivdamt;
	}

	public void setIncsrcJointNempDivdamt(Double incsrcJointNempDivdamt) {
		this.incsrcJointNempDivdamt = incsrcJointNempDivdamt;
	}

	public Double getIncsrcJointNempDivdincr() {
		return this.incsrcJointNempDivdincr;
	}

	public void setIncsrcJointNempDivdincr(Double incsrcJointNempDivdincr) {
		this.incsrcJointNempDivdincr = incsrcJointNempDivdincr;
	}

	public Double getIncsrcJointNempDivdperd() {
		return this.incsrcJointNempDivdperd;
	}

	public void setIncsrcJointNempDivdperd(Double incsrcJointNempDivdperd) {
		this.incsrcJointNempDivdperd = incsrcJointNempDivdperd;
	}

	public Double getIncsrcSelfNempOthamt() {
		return this.incsrcSelfNempOthamt;
	}

	public void setIncsrcSelfNempOthamt(Double incsrcSelfNempOthamt) {
		this.incsrcSelfNempOthamt = incsrcSelfNempOthamt;
	}

	public Double getIncsrcSelfNempOthincr() {
		return this.incsrcSelfNempOthincr;
	}

	public void setIncsrcSelfNempOthincr(Double incsrcSelfNempOthincr) {
		this.incsrcSelfNempOthincr = incsrcSelfNempOthincr;
	}

	public Double getIncsrcSelfNempOthperd() {
		return this.incsrcSelfNempOthperd;
	}

	public void setIncsrcSelfNempOthperd(Double incsrcSelfNempOthperd) {
		this.incsrcSelfNempOthperd = incsrcSelfNempOthperd;
	}

	public Double getIncsrcSpsNempOthamt() {
		return this.incsrcSpsNempOthamt;
	}

	public void setIncsrcSpsNempOthamt(Double incsrcSpsNempOthamt) {
		this.incsrcSpsNempOthamt = incsrcSpsNempOthamt;
	}

	public Double getIncsrcSpsNempOthincr() {
		return this.incsrcSpsNempOthincr;
	}

	public void setIncsrcSpsNempOthincr(Double incsrcSpsNempOthincr) {
		this.incsrcSpsNempOthincr = incsrcSpsNempOthincr;
	}

	public Double getIncsrcSpsNempOthperd() {
		return this.incsrcSpsNempOthperd;
	}

	public void setIncsrcSpsNempOthperd(Double incsrcSpsNempOthperd) {
		this.incsrcSpsNempOthperd = incsrcSpsNempOthperd;
	}

	public Double getIncsrcJointNempOthamt() {
		return this.incsrcJointNempOthamt;
	}

	public void setIncsrcJointNempOthamt(Double incsrcJointNempOthamt) {
		this.incsrcJointNempOthamt = incsrcJointNempOthamt;
	}

	public Double getIncsrcJointNempOthincr() {
		return this.incsrcJointNempOthincr;
	}

	public void setIncsrcJointNempOthincr(Double incsrcJointNempOthincr) {
		this.incsrcJointNempOthincr = incsrcJointNempOthincr;
	}

	public Double getIncsrcJointNempOthperd() {
		return this.incsrcJointNempOthperd;
	}

	public void setIncsrcJointNempOthperd(Double incsrcJointNempOthperd) {
		this.incsrcJointNempOthperd = incsrcJointNempOthperd;
	}

	public Double getInsrcSelfTotannl() {
		return this.insrcSelfTotannl;
	}

	public void setInsrcSelfTotannl(Double insrcSelfTotannl) {
		this.insrcSelfTotannl = insrcSelfTotannl;
	}

	public Double getInsrcSelfTotannlincr() {
		return this.insrcSelfTotannlincr;
	}

	public void setInsrcSelfTotannlincr(Double insrcSelfTotannlincr) {
		this.insrcSelfTotannlincr = insrcSelfTotannlincr;
	}

	public Double getInsrcSelfTotannlperd() {
		return this.insrcSelfTotannlperd;
	}

	public void setInsrcSelfTotannlperd(Double insrcSelfTotannlperd) {
		this.insrcSelfTotannlperd = insrcSelfTotannlperd;
	}

	public Double getInsrcSpsTotannl() {
		return this.insrcSpsTotannl;
	}

	public void setInsrcSpsTotannl(Double insrcSpsTotannl) {
		this.insrcSpsTotannl = insrcSpsTotannl;
	}

	public Double getInsrcSpsTotannlincr() {
		return this.insrcSpsTotannlincr;
	}

	public void setInsrcSpsTotannlincr(Double insrcSpsTotannlincr) {
		this.insrcSpsTotannlincr = insrcSpsTotannlincr;
	}

	public Double getInsrcSpsTotannlperd() {
		return this.insrcSpsTotannlperd;
	}

	public void setInsrcSpsTotannlperd(Double insrcSpsTotannlperd) {
		this.insrcSpsTotannlperd = insrcSpsTotannlperd;
	}

	public Double getInsrcJointTotannl() {
		return this.insrcJointTotannl;
	}

	public void setInsrcJointTotannl(Double insrcJointTotannl) {
		this.insrcJointTotannl = insrcJointTotannl;
	}

	public Double getInsrcJointTotannlincr() {
		return this.insrcJointTotannlincr;
	}

	public void setInsrcJointTotannlincr(Double insrcJointTotannlincr) {
		this.insrcJointTotannlincr = insrcJointTotannlincr;
	}

	public Double getInsrcJointTotannlperd() {
		return this.insrcJointTotannlperd;
	}

	public void setInsrcJointTotannlperd(Double insrcJointTotannlperd) {
		this.insrcJointTotannlperd = insrcJointTotannlperd;
	}

	public Double getIncsrcSelfAbility() {
		return this.incsrcSelfAbility;
	}

	public void setIncsrcSelfAbility(Double incsrcSelfAbility) {
		this.incsrcSelfAbility = incsrcSelfAbility;
	}

	public Double getIncsrcSpsAbility() {
		return this.incsrcSpsAbility;
	}

	public void setIncsrcSpsAbility(Double incsrcSpsAbility) {
		this.incsrcSpsAbility = incsrcSpsAbility;
	}

	public Double getIncsrcJointAbility() {
		return this.incsrcJointAbility;
	}

	public void setIncsrcJointAbility(Double incsrcJointAbility) {
		this.incsrcJointAbility = incsrcJointAbility;
	}

	public Double getIncsrcSelfAbilityincr() {
		return this.incsrcSelfAbilityincr;
	}

	public void setIncsrcSelfAbilityincr(Double incsrcSelfAbilityincr) {
		this.incsrcSelfAbilityincr = incsrcSelfAbilityincr;
	}

	public Double getIncsrcSpsAbilityincr() {
		return this.incsrcSpsAbilityincr;
	}

	public void setIncsrcSpsAbilityincr(Double incsrcSpsAbilityincr) {
		this.incsrcSpsAbilityincr = incsrcSpsAbilityincr;
	}

	public Double getIncsrcJointAbilityincr() {
		return this.incsrcJointAbilityincr;
	}

	public void setIncsrcJointAbilityincr(Double incsrcJointAbilityincr) {
		this.incsrcJointAbilityincr = incsrcJointAbilityincr;
	}

	public String getIncsrcRemarks() {
		return this.incsrcRemarks;
	}

	public void setIncsrcRemarks(String incsrcRemarks) {
		this.incsrcRemarks = incsrcRemarks;
	}

	public Double getInsrcSelfAnnlBusiincome() {
		return this.insrcSelfAnnlBusiincome;
	}

	public void setInsrcSelfAnnlBusiincome(Double insrcSelfAnnlBusiincome) {
		this.insrcSelfAnnlBusiincome = insrcSelfAnnlBusiincome;
	}

	public Double getInsrcSpsAnnlBusiincome() {
		return this.insrcSpsAnnlBusiincome;
	}

	public void setInsrcSpsAnnlBusiincome(Double insrcSpsAnnlBusiincome) {
		this.insrcSpsAnnlBusiincome = insrcSpsAnnlBusiincome;
	}

	public Double getInsrcSelfAnnlOthincome() {
		return this.insrcSelfAnnlOthincome;
	}

	public void setInsrcSelfAnnlOthincome(Double insrcSelfAnnlOthincome) {
		this.insrcSelfAnnlOthincome = insrcSelfAnnlOthincome;
	}

	public Double getInsrcSpsAnnlOthincome() {
		return this.insrcSpsAnnlOthincome;
	}

	public void setInsrcSpsAnnlOthincome(Double insrcSpsAnnlOthincome) {
		this.insrcSpsAnnlOthincome = insrcSpsAnnlOthincome;
	}

	public Double getInsrcSelfNempOthincome() {
		return this.insrcSelfNempOthincome;
	}

	public void setInsrcSelfNempOthincome(Double insrcSelfNempOthincome) {
		this.insrcSelfNempOthincome = insrcSelfNempOthincome;
	}

	public Double getInsrcSpsNempOthincome() {
		return this.insrcSpsNempOthincome;
	}

	public void setInsrcSpsNempOthincome(Double insrcSpsNempOthincome) {
		this.insrcSpsNempOthincome = insrcSpsNempOthincome;
	}

	public String getIncsrcCreatedBy() {
		return this.incsrcCreatedBy;
	}

	public void setIncsrcCreatedBy(String incsrcCreatedBy) {
		this.incsrcCreatedBy = incsrcCreatedBy;
	}

	public Date getIncsrcCreatedDate() {
		return this.incsrcCreatedDate;
	}

	public void setIncsrcCreatedDate(Date incsrcCreatedDate) {
		this.incsrcCreatedDate = incsrcCreatedDate;
	}

	public String getIncsrcModifiedBy() {
		return this.incsrcModifiedBy;
	}

	public void setIncsrcModifiedBy(String incsrcModifiedBy) {
		this.incsrcModifiedBy = incsrcModifiedBy;
	}

	public Date getIncsrcModifiedDate() {
		return this.incsrcModifiedDate;
	}

	public void setIncsrcModifiedDate(Date incsrcModifiedDate) {
		this.incsrcModifiedDate = incsrcModifiedDate;
	}

}
