package com.fipa.dto;

// Generated May 17, 2018 11:20:36 AM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * FnaSummaryAnalysis generated by hbm2java
 */
public class FnaSummaryAnalysis implements java.io.Serializable {

	private String saId;//
	private FnaSelfspouseDets fnaSelfspouseDets;
	private Double saSelfFamprot;//
	private Double saSelfAnnldisability;//
	private Double saSelfMajorill;//
	private Double saSpsFamprot;//
	private Double saSpsAnnldisability;//
	private Double saSpsMajorill;//
	private String saSelfHosptype;//
	private String saSelfWardtype;//
	private String saSelfExisthosptype;//
	private String saSelfExistpoltype;//
	private String saSpsHosptype;//
	private String saSpsWardtype;//
	private String saSpsExisthosptype;//
	private String saSpsExistpoltype;//
	private Double saSelfLumpsumret;//
	private Double saSpsLumpsumret;//
	private Double saSelfEdntotsaving;//
	private Double saSelfEdncursaving;//
	private Double saSelfEdnestsaving;//
	private Double saSpsEdntotsaving;//
	private Double saSpsEdncursaving;//
	private Double saSpsEdnestsaving;//
	private Double saSelfOthtotsaving;//
	private Double saSelfOthcursaving;//
	private Double saSelfOthestsaving;//
	private Double saSpsOthtotsaving;//
	private Double saSpsOthcursaving;//
	private Double saSpsOthestsaving;//
	private String saCreatedBy;
	private Date saCreatedDate;
	private String saModifiedBy;
	private Date saModifiedDate;

	public FnaSummaryAnalysis() {
	}

	public FnaSummaryAnalysis(String saId) {
		this.saId = saId;
	}

	public FnaSummaryAnalysis(String saId, FnaSelfspouseDets fnaSelfspouseDets,
			Double saSelfFamprot, Double saSelfAnnldisability,
			Double saSelfMajorill, Double saSpsFamprot,
			Double saSpsAnnldisability, Double saSpsMajorill,
			String saSelfHosptype, String saSelfWardtype,
			String saSelfExisthosptype, String saSelfExistpoltype,
			String saSpsHosptype, String saSpsWardtype,
			String saSpsExisthosptype, String saSpsExistpoltype,
			Double saSelfLumpsumret, Double saSpsLumpsumret,
			Double saSelfEdntotsaving, Double saSelfEdncursaving,
			Double saSelfEdnestsaving, Double saSpsEdntotsaving,
			Double saSpsEdncursaving, Double saSpsEdnestsaving,
			Double saSelfOthtotsaving, Double saSelfOthcursaving,
			Double saSelfOthestsaving, Double saSpsOthtotsaving,
			Double saSpsOthcursaving, Double saSpsOthestsaving,
			String saCreatedBy, Date saCreatedDate, String saModifiedBy,
			Date saModifiedDate) {
		this.saId = saId;
		this.fnaSelfspouseDets = fnaSelfspouseDets;
		this.saSelfFamprot = saSelfFamprot;
		this.saSelfAnnldisability = saSelfAnnldisability;
		this.saSelfMajorill = saSelfMajorill;
		this.saSpsFamprot = saSpsFamprot;
		this.saSpsAnnldisability = saSpsAnnldisability;
		this.saSpsMajorill = saSpsMajorill;
		this.saSelfHosptype = saSelfHosptype;
		this.saSelfWardtype = saSelfWardtype;
		this.saSelfExisthosptype = saSelfExisthosptype;
		this.saSelfExistpoltype = saSelfExistpoltype;
		this.saSpsHosptype = saSpsHosptype;
		this.saSpsWardtype = saSpsWardtype;
		this.saSpsExisthosptype = saSpsExisthosptype;
		this.saSpsExistpoltype = saSpsExistpoltype;
		this.saSelfLumpsumret = saSelfLumpsumret;
		this.saSpsLumpsumret = saSpsLumpsumret;
		this.saSelfEdntotsaving = saSelfEdntotsaving;
		this.saSelfEdncursaving = saSelfEdncursaving;
		this.saSelfEdnestsaving = saSelfEdnestsaving;
		this.saSpsEdntotsaving = saSpsEdntotsaving;
		this.saSpsEdncursaving = saSpsEdncursaving;
		this.saSpsEdnestsaving = saSpsEdnestsaving;
		this.saSelfOthtotsaving = saSelfOthtotsaving;
		this.saSelfOthcursaving = saSelfOthcursaving;
		this.saSelfOthestsaving = saSelfOthestsaving;
		this.saSpsOthtotsaving = saSpsOthtotsaving;
		this.saSpsOthcursaving = saSpsOthcursaving;
		this.saSpsOthestsaving = saSpsOthestsaving;
		this.saCreatedBy = saCreatedBy;
		this.saCreatedDate = saCreatedDate;
		this.saModifiedBy = saModifiedBy;
		this.saModifiedDate = saModifiedDate;
	}

	public String getSaId() {
		return this.saId;
	}

	public void setSaId(String saId) {
		this.saId = saId;
	}

	public FnaSelfspouseDets getFnaSelfspouseDets() {
		return this.fnaSelfspouseDets;
	}

	public void setFnaSelfspouseDets(FnaSelfspouseDets fnaSelfspouseDets) {
		this.fnaSelfspouseDets = fnaSelfspouseDets;
	}

	public Double getSaSelfFamprot() {
		return this.saSelfFamprot;
	}

	public void setSaSelfFamprot(Double saSelfFamprot) {
		this.saSelfFamprot = saSelfFamprot;
	}

	public Double getSaSelfAnnldisability() {
		return this.saSelfAnnldisability;
	}

	public void setSaSelfAnnldisability(Double saSelfAnnldisability) {
		this.saSelfAnnldisability = saSelfAnnldisability;
	}

	public Double getSaSelfMajorill() {
		return this.saSelfMajorill;
	}

	public void setSaSelfMajorill(Double saSelfMajorill) {
		this.saSelfMajorill = saSelfMajorill;
	}

	public Double getSaSpsFamprot() {
		return this.saSpsFamprot;
	}

	public void setSaSpsFamprot(Double saSpsFamprot) {
		this.saSpsFamprot = saSpsFamprot;
	}

	public Double getSaSpsAnnldisability() {
		return this.saSpsAnnldisability;
	}

	public void setSaSpsAnnldisability(Double saSpsAnnldisability) {
		this.saSpsAnnldisability = saSpsAnnldisability;
	}

	public Double getSaSpsMajorill() {
		return this.saSpsMajorill;
	}

	public void setSaSpsMajorill(Double saSpsMajorill) {
		this.saSpsMajorill = saSpsMajorill;
	}

	public String getSaSelfHosptype() {
		return this.saSelfHosptype;
	}

	public void setSaSelfHosptype(String saSelfHosptype) {
		this.saSelfHosptype = saSelfHosptype;
	}

	public String getSaSelfWardtype() {
		return this.saSelfWardtype;
	}

	public void setSaSelfWardtype(String saSelfWardtype) {
		this.saSelfWardtype = saSelfWardtype;
	}

	public String getSaSelfExisthosptype() {
		return this.saSelfExisthosptype;
	}

	public void setSaSelfExisthosptype(String saSelfExisthosptype) {
		this.saSelfExisthosptype = saSelfExisthosptype;
	}

	public String getSaSelfExistpoltype() {
		return this.saSelfExistpoltype;
	}

	public void setSaSelfExistpoltype(String saSelfExistpoltype) {
		this.saSelfExistpoltype = saSelfExistpoltype;
	}

	public String getSaSpsHosptype() {
		return this.saSpsHosptype;
	}

	public void setSaSpsHosptype(String saSpsHosptype) {
		this.saSpsHosptype = saSpsHosptype;
	}

	public String getSaSpsWardtype() {
		return this.saSpsWardtype;
	}

	public void setSaSpsWardtype(String saSpsWardtype) {
		this.saSpsWardtype = saSpsWardtype;
	}

	public String getSaSpsExisthosptype() {
		return this.saSpsExisthosptype;
	}

	public void setSaSpsExisthosptype(String saSpsExisthosptype) {
		this.saSpsExisthosptype = saSpsExisthosptype;
	}

	public String getSaSpsExistpoltype() {
		return this.saSpsExistpoltype;
	}

	public void setSaSpsExistpoltype(String saSpsExistpoltype) {
		this.saSpsExistpoltype = saSpsExistpoltype;
	}

	public Double getSaSelfLumpsumret() {
		return this.saSelfLumpsumret;
	}

	public void setSaSelfLumpsumret(Double saSelfLumpsumret) {
		this.saSelfLumpsumret = saSelfLumpsumret;
	}

	public Double getSaSpsLumpsumret() {
		return this.saSpsLumpsumret;
	}

	public void setSaSpsLumpsumret(Double saSpsLumpsumret) {
		this.saSpsLumpsumret = saSpsLumpsumret;
	}

	public Double getSaSelfEdntotsaving() {
		return this.saSelfEdntotsaving;
	}

	public void setSaSelfEdntotsaving(Double saSelfEdntotsaving) {
		this.saSelfEdntotsaving = saSelfEdntotsaving;
	}

	public Double getSaSelfEdncursaving() {
		return this.saSelfEdncursaving;
	}

	public void setSaSelfEdncursaving(Double saSelfEdncursaving) {
		this.saSelfEdncursaving = saSelfEdncursaving;
	}

	public Double getSaSelfEdnestsaving() {
		return this.saSelfEdnestsaving;
	}

	public void setSaSelfEdnestsaving(Double saSelfEdnestsaving) {
		this.saSelfEdnestsaving = saSelfEdnestsaving;
	}

	public Double getSaSpsEdntotsaving() {
		return this.saSpsEdntotsaving;
	}

	public void setSaSpsEdntotsaving(Double saSpsEdntotsaving) {
		this.saSpsEdntotsaving = saSpsEdntotsaving;
	}

	public Double getSaSpsEdncursaving() {
		return this.saSpsEdncursaving;
	}

	public void setSaSpsEdncursaving(Double saSpsEdncursaving) {
		this.saSpsEdncursaving = saSpsEdncursaving;
	}

	public Double getSaSpsEdnestsaving() {
		return this.saSpsEdnestsaving;
	}

	public void setSaSpsEdnestsaving(Double saSpsEdnestsaving) {
		this.saSpsEdnestsaving = saSpsEdnestsaving;
	}

	public Double getSaSelfOthtotsaving() {
		return this.saSelfOthtotsaving;
	}

	public void setSaSelfOthtotsaving(Double saSelfOthtotsaving) {
		this.saSelfOthtotsaving = saSelfOthtotsaving;
	}

	public Double getSaSelfOthcursaving() {
		return this.saSelfOthcursaving;
	}

	public void setSaSelfOthcursaving(Double saSelfOthcursaving) {
		this.saSelfOthcursaving = saSelfOthcursaving;
	}

	public Double getSaSelfOthestsaving() {
		return this.saSelfOthestsaving;
	}

	public void setSaSelfOthestsaving(Double saSelfOthestsaving) {
		this.saSelfOthestsaving = saSelfOthestsaving;
	}

	public Double getSaSpsOthtotsaving() {
		return this.saSpsOthtotsaving;
	}

	public void setSaSpsOthtotsaving(Double saSpsOthtotsaving) {
		this.saSpsOthtotsaving = saSpsOthtotsaving;
	}

	public Double getSaSpsOthcursaving() {
		return this.saSpsOthcursaving;
	}

	public void setSaSpsOthcursaving(Double saSpsOthcursaving) {
		this.saSpsOthcursaving = saSpsOthcursaving;
	}

	public Double getSaSpsOthestsaving() {
		return this.saSpsOthestsaving;
	}

	public void setSaSpsOthestsaving(Double saSpsOthestsaving) {
		this.saSpsOthestsaving = saSpsOthestsaving;
	}

	public String getSaCreatedBy() {
		return this.saCreatedBy;
	}

	public void setSaCreatedBy(String saCreatedBy) {
		this.saCreatedBy = saCreatedBy;
	}

	public Date getSaCreatedDate() {
		return this.saCreatedDate;
	}

	public void setSaCreatedDate(Date saCreatedDate) {
		this.saCreatedDate = saCreatedDate;
	}

	public String getSaModifiedBy() {
		return this.saModifiedBy;
	}

	public void setSaModifiedBy(String saModifiedBy) {
		this.saModifiedBy = saModifiedBy;
	}

	public Date getSaModifiedDate() {
		return this.saModifiedDate;
	}

	public void setSaModifiedDate(Date saModifiedDate) {
		this.saModifiedDate = saModifiedDate;
	}

}
