package com.fipa.dto;
// Generated Mar 10, 2017 1:07:02 PM by Hibernate Tools 3.2.0.CR1


import java.util.Date;

/**
 * MasterCpfIntrates generated by hbm2java
 */
public class MasterCpfIntrates  implements java.io.Serializable {


     private String txtFldCpfIntId;
     private String selCpfAccount;
     private String txtFldCpfIntRate;
     private String txtFldCpfIntMonth;
     private String txtFldCpfCreatedBy;
     private Date txtFldCpfCreatedDate;
     private String txtFldCpfModifiedBy;
     private Date txtFldCpfModifiedDate;

    public MasterCpfIntrates() {
    }

	
    public MasterCpfIntrates(String txtFldCpfIntId, String selCpfAccount, String txtFldCpfIntRate, String txtFldCpfCreatedBy, Date txtFldCpfCreatedDate) {
        this.txtFldCpfIntId = txtFldCpfIntId;
        this.selCpfAccount = selCpfAccount;
        this.txtFldCpfIntRate = txtFldCpfIntRate;
        this.txtFldCpfCreatedBy = txtFldCpfCreatedBy;
        this.txtFldCpfCreatedDate = txtFldCpfCreatedDate;
    }
    public MasterCpfIntrates(String txtFldCpfIntId, String selCpfAccount, String txtFldCpfIntRate, String txtFldCpfIntMonth, String txtFldCpfCreatedBy, Date txtFldCpfCreatedDate, String txtFldCpfModifiedBy, Date txtFldCpfModifiedDate) {
       this.txtFldCpfIntId = txtFldCpfIntId;
       this.selCpfAccount = selCpfAccount;
       this.txtFldCpfIntRate = txtFldCpfIntRate;
       this.txtFldCpfIntMonth = txtFldCpfIntMonth;
       this.txtFldCpfCreatedBy = txtFldCpfCreatedBy;
       this.txtFldCpfCreatedDate = txtFldCpfCreatedDate;
       this.txtFldCpfModifiedBy = txtFldCpfModifiedBy;
       this.txtFldCpfModifiedDate = txtFldCpfModifiedDate;
    }
   
    public String getTxtFldCpfIntId() {
        return this.txtFldCpfIntId;
    }
    
    public void setTxtFldCpfIntId(String txtFldCpfIntId) {
        this.txtFldCpfIntId = txtFldCpfIntId;
    }
    public String getSelCpfAccount() {
        return this.selCpfAccount;
    }
    
    public void setSelCpfAccount(String selCpfAccount) {
        this.selCpfAccount = selCpfAccount;
    }
    public String getTxtFldCpfIntRate() {
        return this.txtFldCpfIntRate;
    }
    
    public void setTxtFldCpfIntRate(String txtFldCpfIntRate) {
        this.txtFldCpfIntRate = txtFldCpfIntRate;
    }
    public String getTxtFldCpfIntMonth() {
        return this.txtFldCpfIntMonth;
    }
    
    public void setTxtFldCpfIntMonth(String txtFldCpfIntMonth) {
        this.txtFldCpfIntMonth = txtFldCpfIntMonth;
    }


	public String getTxtFldCpfCreatedBy() {
		return txtFldCpfCreatedBy;
	}


	public void setTxtFldCpfCreatedBy(String txtFldCpfCreatedBy) {
		this.txtFldCpfCreatedBy = txtFldCpfCreatedBy;
	}


	public Date getTxtFldCpfCreatedDate() {
		return txtFldCpfCreatedDate;
	}


	public void setTxtFldCpfCreatedDate(Date txtFldCpfCreatedDate) {
		this.txtFldCpfCreatedDate = txtFldCpfCreatedDate;
	}


	public String getTxtFldCpfModifiedBy() {
		return txtFldCpfModifiedBy;
	}


	public void setTxtFldCpfModifiedBy(String txtFldCpfModifiedBy) {
		this.txtFldCpfModifiedBy = txtFldCpfModifiedBy;
	}


	public Date getTxtFldCpfModifiedDate() {
		return txtFldCpfModifiedDate;
	}


	public void setTxtFldCpfModifiedDate(Date txtFldCpfModifiedDate) {
		this.txtFldCpfModifiedDate = txtFldCpfModifiedDate;
	}
    



}


