package com.fipa.dto;
// Generated Apr 11, 2017 6:38:14 PM by Hibernate Tools 3.2.0.CR1


import java.util.Date;

/**
 * MasterCpfAllocRates generated by hbm2java
 */
public class MasterCpfAllocRates  implements java.io.Serializable {


     private String txtFldCPFAllocId;
     private String txtFldCPFAllocEffFrom;
     private String selCPFAllocAgeGrp;
     private String selCPFAllocAccType;
     private String txtFldCPFAllocRate;
     private String txtFldCPFAllocRemarks;
     private String txtFldCPFCreatedBy;
     private Date txtFldCPFCreatedDate;
     private String txtFldCPFModifiedBy;
     private Date txtFldCPFModifiedDate;

    public MasterCpfAllocRates() {
    }

	
    public MasterCpfAllocRates(String txtFldCPFAllocId) {
        this.txtFldCPFAllocId = txtFldCPFAllocId;
    }
    public MasterCpfAllocRates(String txtFldCPFAllocId, String txtFldCPFAllocEffFrom, String selCPFAllocAgeGrp, String selCPFAllocAccType, String txtFldCPFAllocRate, String txtFldCPFAllocRemarks, String txtFldCPFCreatedBy, Date txtFldCPFCreatedDate, String txtFldCPFModifiedBy, Date txtFldCPFModifiedDate) {
       this.txtFldCPFAllocId = txtFldCPFAllocId;
       this.txtFldCPFAllocEffFrom = txtFldCPFAllocEffFrom;
       this.selCPFAllocAgeGrp = selCPFAllocAgeGrp;
       this.selCPFAllocAccType = selCPFAllocAccType;
       this.txtFldCPFAllocRate = txtFldCPFAllocRate;
       this.txtFldCPFAllocRemarks = txtFldCPFAllocRemarks;
       this.txtFldCPFCreatedBy = txtFldCPFCreatedBy;
       this.txtFldCPFCreatedDate = txtFldCPFCreatedDate;
       this.txtFldCPFModifiedBy = txtFldCPFModifiedBy;
       this.txtFldCPFModifiedDate = txtFldCPFModifiedDate;
    }
   
    public String getTxtFldCPFAllocId() {
        return this.txtFldCPFAllocId;
    }
    
    public void setTxtFldCPFAllocId(String txtFldCPFAllocId) {
        this.txtFldCPFAllocId = txtFldCPFAllocId;
    }
    public String getTxtFldCPFAllocEffFrom() {
        return this.txtFldCPFAllocEffFrom;
    }
    
    public void setTxtFldCPFAllocEffFrom(String txtFldCPFAllocEffFrom) {
        this.txtFldCPFAllocEffFrom = txtFldCPFAllocEffFrom;
    }
    public String getSelCPFAllocAgeGrp() {
        return this.selCPFAllocAgeGrp;
    }
    
    public void setSelCPFAllocAgeGrp(String selCPFAllocAgeGrp) {
        this.selCPFAllocAgeGrp = selCPFAllocAgeGrp;
    }
    public String getSelCPFAllocAccType() {
        return this.selCPFAllocAccType;
    }
    
    public void setSelCPFAllocAccType(String selCPFAllocAccType) {
        this.selCPFAllocAccType = selCPFAllocAccType;
    }
    public String getTxtFldCPFAllocRate() {
        return this.txtFldCPFAllocRate;
    }
    
    public void setTxtFldCPFAllocRate(String txtFldCPFAllocRate) {
        this.txtFldCPFAllocRate = txtFldCPFAllocRate;
    }
    public String getTxtFldCPFAllocRemarks() {
        return this.txtFldCPFAllocRemarks;
    }
    
    public void setTxtFldCPFAllocRemarks(String txtFldCPFAllocRemarks) {
        this.txtFldCPFAllocRemarks = txtFldCPFAllocRemarks;
    }
    public String getTxtFldCPFCreatedBy() {
        return this.txtFldCPFCreatedBy;
    }
    
    public void setTxtFldCPFCreatedBy(String txtFldCPFCreatedBy) {
        this.txtFldCPFCreatedBy = txtFldCPFCreatedBy;
    }
    public Date getTxtFldCPFCreatedDate() {
        return this.txtFldCPFCreatedDate;
    }
    
    public void setTxtFldCPFCreatedDate(Date txtFldCPFCreatedDate) {
        this.txtFldCPFCreatedDate = txtFldCPFCreatedDate;
    }
    public String getTxtFldCPFModifiedBy() {
        return this.txtFldCPFModifiedBy;
    }
    
    public void setTxtFldCPFModifiedBy(String txtFldCPFModifiedBy) {
        this.txtFldCPFModifiedBy = txtFldCPFModifiedBy;
    }
    public Date getTxtFldCPFModifiedDate() {
        return this.txtFldCPFModifiedDate;
    }
    
    public void setTxtFldCPFModifiedDate(Date txtFldCPFModifiedDate) {
        this.txtFldCPFModifiedDate = txtFldCPFModifiedDate;
    }




}


