package com.fipa.dto;

// Generated Mar 5, 2019 9:27:03 AM by Hibernate Tools 3.4.0.CR1

/**
 * MasterCpflifePlans generated by hbm2java
 */
public class MasterCpflifePlans implements java.io.Serializable {

	private String planId;
	private String planName;
	private String planCode;
	private String planDesc;
	private String remarks;

	public MasterCpflifePlans() {
	}

	public MasterCpflifePlans(String planId, String planCode) {
		this.planId = planId; 
		this.planCode = planCode;
	}

	public MasterCpflifePlans(String planId,  String planCode ,
			String planName, String planDesc,
			String remarks) {
		this.planId   = planId;
		this.planCode = planCode;
		this.planName = planName;
		this.planDesc = planDesc;
		this.remarks = remarks;
	}

	
	public String getPlanCode() {
		return this.planCode;
	}

	public void setPlanCode(String planCode) {
		this.planCode = planCode;
	}

	public String getPlanId() {
		return this.planId;
	}

	public void setPlanId(String planId) {
		this.planId = planId;
	}

	public String getPlanName() {
		return this.planName;
	}

	public void setPlanName(String planName) {
		this.planName = planName;
	}

	public String getPlanDesc() {
		return this.planDesc;
	}

	public void setPlanDesc(String planDesc) {
		this.planDesc = planDesc;
	}

	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

}
