package com.fipa.dto;

// Generated Mar 5, 2019 9:27:03 AM by Hibernate Tools 3.4.0.CR1

/**
 * MasterCpflifePayout generated by hbm2java
 */
public class MasterCpflifePayout implements java.io.Serializable {

	private String pid;
	private String payoutYear;
	private String retScheme;
	private Double monthlyAmt;
	private Double yearlyAmt;

	public MasterCpflifePayout() {
	}

	public MasterCpflifePayout(String pid) {
		this.pid = pid;
	}

	public MasterCpflifePayout(String pid, String payoutYear, String retScheme,
			Double monthlyAmt, Double yearlyAmt) {
		this.pid = pid;
		this.payoutYear = payoutYear;
		this.retScheme = retScheme;
		this.monthlyAmt = monthlyAmt;
		this.yearlyAmt = yearlyAmt;
	}

	public String getPid() {
		return this.pid;
	}

	public void setPid(String pid) {
		this.pid = pid;
	}

	public String getPayoutYear() {
		return this.payoutYear;
	}

	public void setPayoutYear(String payoutYear) {
		this.payoutYear = payoutYear;
	}

	public String getRetScheme() {
		return this.retScheme;
	}

	public void setRetScheme(String retScheme) {
		this.retScheme = retScheme;
	}

	public Double getMonthlyAmt() {
		return this.monthlyAmt;
	}

	public void setMonthlyAmt(Double monthlyAmt) {
		this.monthlyAmt = monthlyAmt;
	}

	public Double getYearlyAmt() {
		return this.yearlyAmt;
	}

	public void setYearlyAmt(Double yearlyAmt) {
		this.yearlyAmt = yearlyAmt;
	}

}
