package com.fipa.dto;

// Generated Jul 16, 2018 10:05:31 AM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * MasterCpfAcctype generated by hbm2java
 */
public class MasterCpfAcctype implements java.io.Serializable {

	private String cpfAcId;
	private String accType;
	private String accCrtdBy;
	private Date accCrtdDate;
	private String accModBy;
	private Date accModDate;
	private String accCode;
	private String accCommAge;
	private String accWithdrawAge;
	private Double accTopuplimit;
 

	public MasterCpfAcctype() {
	}

	public MasterCpfAcctype(String cpfAcId, String accType) {
		this.cpfAcId = cpfAcId;
		this.accType = accType;
	}

	public MasterCpfAcctype(String cpfAcId, String accType, String accCrtdBy,
			Date accCrtdDate, String accModBy, Date accModDate, String accCode,
			String accCommAge, String accWithdrawAge,Double accTopuplimit,
			Set<FnaCpfBalanceDets> fnaCpfBalanceDetses,
			Set<FnaCpfDeductions> fnaCpfDeductionses
			) {
		this.cpfAcId = cpfAcId;
		this.accType = accType;
		this.accCrtdBy = accCrtdBy;
		this.accCrtdDate = accCrtdDate;
		this.accModBy = accModBy;
		this.accModDate = accModDate;
		this.accCode = accCode;
		this.accCommAge = accCommAge;
		this.accWithdrawAge = accWithdrawAge; 
		this.accTopuplimit  = accTopuplimit;
		
	}

	public String getCpfAcId() {
		return this.cpfAcId;
	}

	public void setCpfAcId(String cpfAcId) {
		this.cpfAcId = cpfAcId;
	}

	public String getAccType() {
		return this.accType;
	}

	public void setAccType(String accType) {
		this.accType = accType;
	}

	public Double getAccTopuplimit() {
		return accTopuplimit;
	}

	public void setAccTopuplimit(Double accTopuplimit) {
		this.accTopuplimit = accTopuplimit;
	}

	public String getAccCrtdBy() {
		return this.accCrtdBy;
	}

	public void setAccCrtdBy(String accCrtdBy) {
		this.accCrtdBy = accCrtdBy;
	}

	public Date getAccCrtdDate() {
		return this.accCrtdDate;
	}

	public void setAccCrtdDate(Date accCrtdDate) {
		this.accCrtdDate = accCrtdDate;
	}

	public String getAccModBy() {
		return this.accModBy;
	}

	public void setAccModBy(String accModBy) {
		this.accModBy = accModBy;
	}

	public Date getAccModDate() {
		return this.accModDate;
	}

	public void setAccModDate(Date accModDate) {
		this.accModDate = accModDate;
	}

	public String getAccCode() {
		return this.accCode;
	}

	public void setAccCode(String accCode) {
		this.accCode = accCode;
	}

	public String getAccCommAge() {
		return this.accCommAge;
	}

	public void setAccCommAge(String accCommAge) {
		this.accCommAge = accCommAge;
	}

	public String getAccWithdrawAge() {
		return this.accWithdrawAge;
	}

	public void setAccWithdrawAge(String accWithdrawAge) {
		this.accWithdrawAge = accWithdrawAge;
	}

	  

}
