package com.fipa.dto;

/**
 * FnaCpfDeductions generated by hbm2java
 */
public class MasterRetSchemeLimits  implements java.io.Serializable{
	
	private Double schId;
	private Double brthYr;
	private Double brsLimit;
	private Double frsLimit;
	private Double ersLimit;
	private Double bhcSum; 
	
	public MasterRetSchemeLimits() {  
	}


	public MasterRetSchemeLimits(Double schId) { 
		this.schId = schId;
	}


	public MasterRetSchemeLimits(Double schId, Double brthYr,
			Double brsLimit, Double frsLimit, Double ersLimit, Double bhcSum) { 
		this.schId = schId;
		this.brthYr = brthYr;
		this.brsLimit = brsLimit;
		this.frsLimit = frsLimit;
		this.ersLimit = ersLimit;
		this.bhcSum = bhcSum;
	}
	
	
	public Double getSchId() {
		return this.schId;
	}
	public void setSchId(Double schId) {
		this.schId = schId;
	}
	public Double getBrthYr() {
		return this.brthYr;
	}
	public void setBrthYr(Double brthYr) {
		this.brthYr = brthYr;
	}
	public Double getBrsLimit() {
		return this.brsLimit;
	}
	public void setBrsLimit(Double brsLimit) {
		this.brsLimit = brsLimit;
	}
	public Double getFrsLimit() {
		return this.frsLimit;
	}
	public void setFrsLimit(Double frsLimit) {
		this.frsLimit = frsLimit;
	}
	public Double getErsLimit() {
		return this.ersLimit;
	}
	public void setErsLimit(Double ersLimit) {
		this.ersLimit = ersLimit;
	}
	public Double getBhcSum() {
		return this.bhcSum;
	}
	public void setBhcSum(Double bhcSum) {
		this.bhcSum = bhcSum;
	}

	 
	
}
