package com.fipa.dto;

// Generated May 25, 2018 4:51:29 PM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * MasterPropertykv generated by hbm2java
 */
public class MasterPropertykv implements java.io.Serializable {

	private String propId;
	private String propKey;
	private String propValue;
	private String propStatus;
	private String propRemarks;
	private Date propCrtdDate;
	private String propCrtdBy;
	private String propModBy;
	private Date propModDate;

	public MasterPropertykv() {
	}

	public MasterPropertykv(String propId) {
		this.propId = propId;
	}

	public MasterPropertykv(String propId, String propKey, String propValue,
			String propStatus, String propRemarks, Date propCrtdDate,
			String propCrtdBy, String propModBy, Date propModDate) {
		this.propId = propId;
		this.propKey = propKey;
		this.propValue = propValue;
		this.propStatus = propStatus;
		this.propRemarks = propRemarks;
		this.propCrtdDate = propCrtdDate;
		this.propCrtdBy = propCrtdBy;
		this.propModBy = propModBy;
		this.propModDate = propModDate;
	}

	public String getPropId() {
		return this.propId;
	}

	public void setPropId(String propId) {
		this.propId = propId;
	}

	public String getPropKey() {
		return this.propKey;
	}

	public void setPropKey(String propKey) {
		this.propKey = propKey;
	}

	public String getPropValue() {
		return this.propValue;
	}

	public void setPropValue(String propValue) {
		this.propValue = propValue;
	}

	public String getPropStatus() {
		return this.propStatus;
	}

	public void setPropStatus(String propStatus) {
		this.propStatus = propStatus;
	}

	public String getPropRemarks() {
		return this.propRemarks;
	}

	public void setPropRemarks(String propRemarks) {
		this.propRemarks = propRemarks;
	}

	public Date getPropCrtdDate() {
		return this.propCrtdDate;
	}

	public void setPropCrtdDate(Date propCrtdDate) {
		this.propCrtdDate = propCrtdDate;
	}

	public String getPropCrtdBy() {
		return this.propCrtdBy;
	}

	public void setPropCrtdBy(String propCrtdBy) {
		this.propCrtdBy = propCrtdBy;
	}

	public String getPropModBy() {
		return this.propModBy;
	}

	public void setPropModBy(String propModBy) {
		this.propModBy = propModBy;
	}

	public Date getPropModDate() {
		return this.propModDate;
	}

	public void setPropModDate(Date propModDate) {
		this.propModDate = propModDate;
	}

}
