package com.fipa.dto;

// Generated Jun 4, 2018 12:24:13 PM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * MasterCpfContribRates generated by hbm2java
 */
public class MasterCpfContribRates implements java.io.Serializable {

	private String contrId;
	private Date effFrom;
	private Date effTo;
	private String ageGrp;
	private String wageGrp;
	private Double totBaseValue;
	private String totBaseOn;
	private Double totBonusValue;
	private String totBonusOn;
	private Double totBonusLess;
	private String totMaxLimit;
	private Double empBaseVal;
	private String empBaseOn;
	private Double empBonusValue;
	private String empBonusOn;
	private Double empBonusLess;
	private String empMaxLimit;
	private String remarks;
	private String crtdBy;
	private Date crtdDate;

	public MasterCpfContribRates() {
	}

	public MasterCpfContribRates(String contrId) {
		this.contrId = contrId;
	}

	public MasterCpfContribRates(String contrId, Date effFrom, Date effTo,
			String ageGrp, String wageGrp, Double totBaseValue,
			String totBaseOn, Double totBonusValue, String totBonusOn,
			Double totBonusLess, String totMaxLimit, Double empBaseVal,
			String empBaseOn, Double empBonusValue, String empBonusOn,
			Double empBonusLess, String empMaxLimit, String remarks,
			String crtdBy, Date crtdDate) {
		this.contrId = contrId;
		this.effFrom = effFrom;
		this.effTo = effTo;
		this.ageGrp = ageGrp;
		this.wageGrp = wageGrp;
		this.totBaseValue = totBaseValue;
		this.totBaseOn = totBaseOn;
		this.totBonusValue = totBonusValue;
		this.totBonusOn = totBonusOn;
		this.totBonusLess = totBonusLess;
		this.totMaxLimit = totMaxLimit;
		this.empBaseVal = empBaseVal;
		this.empBaseOn = empBaseOn;
		this.empBonusValue = empBonusValue;
		this.empBonusOn = empBonusOn;
		this.empBonusLess = empBonusLess;
		this.empMaxLimit = empMaxLimit;
		this.remarks = remarks;
		this.crtdBy = crtdBy;
		this.crtdDate = crtdDate;
	}

	public String getContrId() {
		return this.contrId;
	}

	public void setContrId(String contrId) {
		this.contrId = contrId;
	}

	public Date getEffFrom() {
		return this.effFrom;
	}

	public void setEffFrom(Date effFrom) {
		this.effFrom = effFrom;
	}

	public Date getEffTo() {
		return this.effTo;
	}

	public void setEffTo(Date effTo) {
		this.effTo = effTo;
	}

	public String getAgeGrp() {
		return this.ageGrp;
	}

	public void setAgeGrp(String ageGrp) {
		this.ageGrp = ageGrp;
	}

	public String getWageGrp() {
		return this.wageGrp;
	}

	public void setWageGrp(String wageGrp) {
		this.wageGrp = wageGrp;
	}

	public Double getTotBaseValue() {
		return this.totBaseValue;
	}

	public void setTotBaseValue(Double totBaseValue) {
		this.totBaseValue = totBaseValue;
	}

	public String getTotBaseOn() {
		return this.totBaseOn;
	}

	public void setTotBaseOn(String totBaseOn) {
		this.totBaseOn = totBaseOn;
	}

	public Double getTotBonusValue() {
		return this.totBonusValue;
	}

	public void setTotBonusValue(Double totBonusValue) {
		this.totBonusValue = totBonusValue;
	}

	public String getTotBonusOn() {
		return this.totBonusOn;
	}

	public void setTotBonusOn(String totBonusOn) {
		this.totBonusOn = totBonusOn;
	}

	public Double getTotBonusLess() {
		return this.totBonusLess;
	}

	public void setTotBonusLess(Double totBonusLess) {
		this.totBonusLess = totBonusLess;
	}

	public String getTotMaxLimit() {
		return this.totMaxLimit;
	}

	public void setTotMaxLimit(String totMaxLimit) {
		this.totMaxLimit = totMaxLimit;
	}

	public Double getEmpBaseVal() {
		return this.empBaseVal;
	}

	public void setEmpBaseVal(Double empBaseVal) {
		this.empBaseVal = empBaseVal;
	}

	public String getEmpBaseOn() {
		return this.empBaseOn;
	}

	public void setEmpBaseOn(String empBaseOn) {
		this.empBaseOn = empBaseOn;
	}

	public Double getEmpBonusValue() {
		return this.empBonusValue;
	}

	public void setEmpBonusValue(Double empBonusValue) {
		this.empBonusValue = empBonusValue;
	}

	public String getEmpBonusOn() {
		return this.empBonusOn;
	}

	public void setEmpBonusOn(String empBonusOn) {
		this.empBonusOn = empBonusOn;
	}

	public Double getEmpBonusLess() {
		return this.empBonusLess;
	}

	public void setEmpBonusLess(Double empBonusLess) {
		this.empBonusLess = empBonusLess;
	}

	public String getEmpMaxLimit() {
		return this.empMaxLimit;
	}

	public void setEmpMaxLimit(String empMaxLimit) {
		this.empMaxLimit = empMaxLimit;
	}

	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	public String getCrtdBy() {
		return this.crtdBy;
	}

	public void setCrtdBy(String crtdBy) {
		this.crtdBy = crtdBy;
	}

	public Date getCrtdDate() {
		return this.crtdDate;
	}

	public void setCrtdDate(Date crtdDate) {
		this.crtdDate = crtdDate;
	}

	 
}
